import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT10")
st.write("##### Former name: Agr_C15-TPS02")
st.write("##### TPS original information: Agr_C15-TPS02_(+)-Aristolochene_10.710min_standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Abies grandis_")
st.write("##### UniProt ID or NCBI ID: [Q03471](https://www.uniprot.org/uniprotkb/Q03471/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT10\nMATSTETISSLAQPFVHLENPINSPLVKETIRPRNDTTITPPPTQWSYLCHPRVKEVQDEVDGYFLENWKFPSFKAVRTFLDAKFSEVTCLYFPLALDDRIHFACRLLTVLFLIDDVLEHMSFADGEAYNNRLIPISRGDVLPDRTKPEEFILYDLWESMRAHDAELANEVLEPTFVFMRAQTDRARLSIHELGHYLEYREKDVGKALLSALMRFSMGLRLSADELQDMKALEANCAKQLSVVNDIYSYDKEEEASRTGHKEGAFLCSAVKVLAEESKLGIPATKRVLWSMTREWETVHDEIVAEKIASPDGCSEAAKAYMKGLEYQMSGNEQWSKTTRRYN")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT10\nATGGCTACATCTACTGAAACTATTTCTTCTTTGGCTCAACCATTTGTTCATTTAGAAAATCCAATCAACTCCCCATTAGTTAAAGAAACTATTAGACCAAGAAACGATACTACTATTACTCCACCACCAACTCAATGGTCTTATTTATGTCATCCAAGAGTTAAAGAGGTTCAAGATGAAGTTGATGGTTATTTTTTGGAAAACTGGAAATTCCCATCTTTTAAAGCTGTTAGAACATTTTTGGACGCTAAATTTTCTGAAGTTACATGTTTGTACTTCCCATTGGCTTTGGATGATAGAATACATTTTGCTTGTAGATTGTTGACAGTTTTATTCTTGATCGATGATGTTTTGGAACACATGTCTTTTGCTGATGGTGAAGCTTATAATAATAGATTAATCCCAATCTCCAGGGGTGATGTTTTGCCAGATAGAACAAAACCAGAAGAATTTATTCTGTACGATTTGTGGGAATCTATGAGAGCTCATGATGCTGAATTAGCTAATGAAGTTTTGGAACCAACTTTTGTTTTCATGAGAGCTCAAACTGATAGAGCTAGATTGTCTATTCATGAATTGGGTCATTATTTGGAATACAGAGAAAAAGATGTCGGTAAAGCTTTGTTGTCTGCTTTGATGAGATTTTCTATGGGTTTGAGATTGTCTGCTGATGAATTACAAGATATGAAAGCTTTAGAGGCTAATTGTGCTAAACAATTGTCTGTTGTTAACGATATTTACTCTTACGATAAGGAAGAAGAAGCTTCTAGAACTGGTCATAAAGAAGGTGCTTTTTTATGTTCTGCTGTTAAAGTTTTGGCTGAAGAATCTAAATTGGGTATTCCAGCTACTAAAAGAGTTTTGTGGTCTATGACAAGAGAATGGGAAACTGTTCATGATGAAATTGTTGCTGAAAAAATCGCTTCTCCAGATGGTTGTTCTGAAGCTGCTAAAGCTTATATGAAAGGTTTAGAATACCAGATGTCTGGTAATGAACAATGGTCTAAAACTACTAGAAGATATAACTAA")

st.write("##### TIC:")
st.image('image/LT10.png')

st.write("##### Doi: [10.1021/ja0499593](https://doi.org/10.1021/ja0499593)")
st.write("##### Cite: Felicetti, B., and Cane, D.E. (2004). Aristolochene synthase: mechanistic analysis of active site residues by site-directed mutagenesis. Journal of the American Chemical Society 126:7212-7221.")