import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT11")
st.write("##### Former name: Svi_C15-TPS03")
st.write("##### TPS original information: Svi_C15-TPS03_(-)-伪-Amorphene_10.6min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces viridochromogenes_")
st.write("##### UniProt ID or NCBI ID: [D9XDR8](https://www.uniprot.org/uniprotkb/D9XDR8/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT11\nMAKMSTTHEEIALAGPDGIPAVDLRDLIDAQLYMPFPFERNPHASEAAAGVDHWLSTWGLTDDPAVAAMISCTRPAELAAFNGPDMDSGLLQIAANQIAYQFVFDDRAEDIGRHSPGRLLPMLSESVAILRDGQPPTTPLGAALADLHRQVQERCTPAQAARWAWNSREYVHGLLYEAVAQAHPAPVESGLCRSIRSLIAGVEPFYPLCEAAQRCELAPEELHHPAMRRLSRLSADAAVWIPDLFSAVKEQRAGGMINLALAYRRTHRCSLPAAVTLAVRHINSTIREFEDLYGEVRPELSPSGIGYVEGMAGWIRGCYFWSRTVPRYADTLTAPAGL")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT11\nATGGCTAAAATGTCTACAACTCATGAAGAAATTGCTTTAGCTGGTCCAGATGGTATTCCAGCTGTTGATTTGAGAGATTTGATTGATGCTCAATTATACATGCCATTTCCATTTGAAAGAAACCCACATGCTTCTGAAGCTGCTGCTGGTGTTGATCATTGGTTGTCTACTTGGGGTTTAACAGATGATCCAGCTGTTGCTGCTATGATTTCTTGTACAAGACCAGCTGAATTAGCTGCTTTTAATGGTCCAGATATGGATTCTGGTTTGTTGCAAATTGCTGCTAATCAAATTGCTTATCAATTCGTTTTCGACGATAGAGCTGAAGATATTGGTAGACATTCTCCAGGTAGATTATTGCCAATGTTGTCTGAATCTGTTGCTATTTTAAGAGATGGTCAACCACCAACTACACCATTGGGTGCTGCTTTGGCTGATTTGCATAGACAAGTTCAAGAAAGATGTACACCAGCTCAAGCTGCTAGATGGGCTTGGAATAGTAGAGAATATGTTCATGGTTTGTTGTATGAAGCTGTTGCTCAAGCTCATCCAGCTCCAGTTGAATCTGGTTTATGTAGATCTATTAGATCTTTGATCGCTGGTGTTGAACCATTTTATCCATTGTGTGAAGCTGCTCAAAGATGTGAATTGGCTCCAGAAGAATTGCATCATCCAGCTATGAGAAGATTGTCTAGATTATCTGCTGATGCTGCTGTTTGGATTCCAGATTTATTTTCTGCTGTTAAAGAGCAAAGAGCTGGTGGTATGATTAATTTAGCTTTAGCTTATAGGAGGACTCATAGATGTTCTTTGCCAGCTGCTGTTACTTTAGCTGTTAGACATATTAATTCCACTATCAGAGAATTTGAGGATTTGTATGGTGAAGTTAGACCAGAATTGTCTCCATCTGGTATTGGTTATGTTGAAGGTATGGCTGGTTGGATTAGAGGTTGTTATTTTTGGTCTAGAACAGTTCCAAGATATGCTGATACATTAACTGCTCCAGCTGGTTTGTAA")

st.write("##### TIC:")
st.image('image/LT11.png')

st.write("##### Doi: [10.1002/anie.201209103](https://doi.org/10.1002/anie.201209103)")
st.write("##### Cite: Rabe, P., and Dickschat, J.S. (2013). Rapid chemical characterization of bacterial terpene synthases. Angewandte Chemie International Edition 52.")