import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT12")
st.write("##### Former name: Ddi_C15-TPS06")
st.write("##### TPS original information: Ddi_C15-TPS06_(-)-尾-Barbatene_10.325min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Dictyostelium discoideum_")
st.write("##### UniProt ID or NCBI ID: [Q54YE2](https://www.uniprot.org/uniprotkb/Q54YE2/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT12\nMYSLHDFKFPEDWIEPPANDKCIYTCYKEVVDFKLFEENKKTLEYYYGTISSTIYLYPLCNYEQLLVASRYLTVCFVVDDFLESKLTNPDDSRELIKKLEHIFMDGNFYDSNNISNIEKYVLYFRETTKQFVGEKIEFFNQFLKFIIDWINSINPFNRADNLNNYDSYNFFKRTNSGTYVSLSVAMLLYPNSKIDPKIWINPRFDRFATNGGYQMATMNDCASYAKEIRNNNHLTNPLHFLQNQVGSFDNVYKVILKFNDEIMNQICEDERILLLECPIEQRDDLKLLTRSMKLILGGNYLWSLQCSRYVDINSPFIEQRSNDPNVIAYEKIVDKILLK")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT12\nATGTACTCTTTGCATGATTTCAAGTTCCCAGAAGATTGGATTGAACCACCAGCTAATGATAAATGTATTTATACATGCTACAAGGAGGTTGTTGATTTTAAATTATTCGAGGAAAACAAGAAGACCTTAGAATATTATTACGGTACTATCTCTTCCACAATTTATTTATACCCATTGTGTAACTACGAGCAATTATTGGTTGCTTCTAGATATTTAACCGTTTGTTTTGTTGTCGATGATTTTTTAGAGTCTAAGTTAACAAACCCAGATGATTCTAGAGAATTGATTAAAAAGCTGGAACATATCTTCATGGATGGTAATTTTTACGATTCTAACAACATCTCTAACATCGAAAAATACGTTTTGTACTTCAGAGAAACAACAAAACAATTCGTTGGTGAAAAAATCGAATTTTTCAACCAATTCCTGAAGTTTATCATCGATTGGATTAATTCTATCAACCCATTTAACAGAGCTGATAATTTAAACAACTACGATTCTTACAACTTCTTCAAAAGAACTAACTCTGGTACTTATGTTTCTTTGTCTGTTGCTATGTTGTTGTATCCAAATTCTAAAATCGACCCAAAAATCTGGATTAATCCAAGATTTGATAGGTTTGCTACTAATGGTGGTTATCAAATGGCTACTATGAATGATTGTGCTTCTTATGCTAAAGAAATCAGAAATAACAACCACTTGACTAATCCATTACATTTTTTGCAAAACCAGGTTGGTTCTTTTGATAATGTTTATAAGGTCATCCTGAAGTTTAACGATGAAATTATGAACCAAATCTGCGAAGATGAAAGAATTTTGTTATTGGAATGCCCAATTGAACAAAGAGATGATTTAAAACTGCTGACTAGATCTATGAAATTGATTTTGGGTGGTAATTACTTGTGGTCTTTGCAATGTTCTAGATATGTTGATATCAACTCTCCATTTATCGAACAAAGATCTAATGATCCAAACGTTATTGCTTATGAAAAGATTGTTGACAAGATCTTGTTGAAATAA")

st.write("##### TIC:")
st.image('image/LT12.png')

st.write("##### Doi: [10.1073/pnas.1610379113](https://doi.org/10.1073/pnas.1610379113)")
st.write("##### Cite: Chen, X., K?llner, T.G., Jia, Q., Norris, A., Santhanam, B., Rabe, P., Dickschat, J.S., Shaulsky, G., Gershenzon, J., and Chen, F. (2016). Terpene synthase genes in eukaryotes beyond plants and fungi: Occurrence in social amoebae. Proceedings of the National Academy of Sciences 113:12132-12137.")