import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT18")
st.write("##### Former name: Afu_C15-TPS13")
st.write("##### TPS original information: Afu_C15-TPS13_(-)-尾-trans-Bergamotene_10.645min_NMR")
st.write("##### TPS type: TPS-b")

st.write("##### Species: _Aspergillus fumigatus_")
st.write("##### UniProt ID or NCBI ID: [M4VQY9](https://www.uniprot.org/uniprotkb/M4VQY9/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT18\nMDRVLSLGKLPISFLKTLYLFSKSDIPAATLPSMAVALVLAAPCSFHLIIKGFLWNQLHLLTFQVKNQIDGIDEDSIAKPHRPLPSGRITPGQATLLYRVLFFLMWVAAVYTNTISCTLVYSIAIVVYNEGGLAAIPVVKNLIGAIGLGCYCWGTTIIFDGGKELHGLKAVAVLMIVGIFATTGHAQDFRDRTADATRGRKTIPLLLSQPVARWSLATITAAWTIGLIALWKPPAIVTLAYVAASLRCLDGFLSSYDEKDDYVSYCWYGFWLLGSNILPIFPRLRGELP")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT18\nATGGATAGAGTTTTGTCTTTGGGTAAATTACCAATTTCTTTCTTGAAGACTCTGTATTTATTCTCTAAGTCTGATATCCCAGCTGCTACATTGCCATCTATGGCTGTTGCTTTGGTTTTGGCTGCTCCATGTTCTTTTCATTTGATTATTAAGGGTTTCCTGTGGAATCAATTGCATTTATTGACATTTCAGGTCAAAAACCAAATCGATGGTATTGATGAAGATTCTATTGCTAAACCACATAGACCATTACCATCTGGTAGAATTACACCAGGTCAAGCTACTTTGTTATATAGAGTTTTGTTCTTCCTGATGTGGGTTGCTGCTGTTTATACTAATACTATTTCTTGTACCCTGGTTTATTCTATTGCTATTGTTGTTTACAACGAGGGTGGTTTAGCTGCTATTCCAGTTGTTAAAAATTTGATTGGTGCTATTGGTTTGGGTTGTTATTGTTGGGGTACTACAATTATTTTCGATGGTGGTAAAGAATTGCATGGTTTAAAAGCTGTTGCTGTTTTAATGATTGTCGGTATTTTTGCTACAACAGGTCATGCTCAAGATTTTAGAGATAGAACAGCTGATGCTACTAGAGGTAGAAAAACTATTCCATTATTGTTGTCTCAGCCAGTTGCTAGATGGTCTTTGGCTACAATTACAGCTGCTTGGACTATTGGTTTGATTGCTTTATGGAAACCACCAGCTATTGTTACTTTAGCTTATGTTGCTGCTTCTTTAAGATGTTTGGATGGTTTTTTGTCTTCTTATGATGAAAAGGATGACTATGTTTCTTACTGTTGGTATGGTTTTTGGTTGTTAGGTTCTAATATCTTGCCAATTTTCCCAAGATTAAGAGGTGAATTGCCATAA")

st.write("##### TIC:")
st.image('image/LT18.png')

st.write("##### Doi: [10.1021/ja312503y](https://doi.org/10.1021/ja312503y)")
st.write("##### Cite: Lin, H.-C., Chooi, Y.-H., Dhingra, S., Xu, W., Calvo, A.M., and Tang, Y. (2013). The fumagillin biosynthetic gene cluster in Aspergillus fumigatus encodes a cryptic terpene cyclase involved in the formation of β-trans-bergamotene. Journal of the American Chemical Society 135:4616-4619.")