import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT22")
st.write("##### Former name: Sro_C15-TPS19")
st.write("##### TPS original information: Sro_C15-TPS19_4-epi-cubebol_10.81min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptosporangium roseum (strain ATCC 12428 / DSM 43021 / JCM 3005 / NI 9100)_")
st.write("##### UniProt ID or NCBI ID: [D2B747](https://www.uniprot.org/uniprotkb/D2B747/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT22\nMGTTTTHKFDRPLRLPPLPCPFPSEVNPYVEQVDKETLEWLIDSEMLDDAETVERYRQAKYGWLSARTYPYAEHHTLRLVSDWCVWLFAFDDAFCESDRRAAEIARALPQLYAVLEDLDVGSEVDDVFAKSLLEIKGRIAAYGDDEQLDRWRNVTKDYLFAQVWEAANREDEVVPSLEDYIFMRRRTGAMLTVFALIDVASGRSLSADEWRHPGMRAITESANDVVVWDNDLISYAKESNSGNSRNNLVNVLAEHRHYSRQEAMEEIGEMRNQAIADMVAVRPSLEALGSDAVLAYVRGLEFWISGSVDYSLTSSRYTDAWRTARQPSIR")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT22\nATGGGTACTACAACTACACATAAATTCGATAGACCATTAAGATTGCCACCATTGCCATGTCCATTTCCATCTGAAGTTAATCCATACGTTGAACAAGTTGATAAAGAAACATTGGAATGGTTAATCGATTCTGAAATGTTAGATGATGCTGAAACAGTTGAAAGATATAGACAAGCTAAATACGGTTGGTTGTCTGCTAGAACATATCCATACGCTGAACATCATACTTTGAGATTGGTTTCTGATTGGTGTGTTTGGTTATTTGCTTTTGATGATGCTTTTTGTGAGTCTGATAGAAGAGCTGCTGAAATTGCTAGAGCTTTGCCACAATTGTATGCTGTTTTGGAAGATTTGGATGTTGGTTCTGAAGTTGATGATGTTTTTGCTAAATCTTTGTTGGAAATCAAGGGTAGAATTGCTGCTTATGGTGATGATGAACAATTGGATAGATGGAGAAATGTTACTAAAGATTACTTGTTCGCTCAAGTTTGGGAAGCTGCTAATAGAGAAGATGAAGTTGTTCCATCTTTGGAAGATTATATTTTCATGAGAAGGAGAACTGGTGCTATGTTAACAGTTTTTGCTTTAATTGACGTCGCTTCTGGTAGATCTTTGTCTGCTGATGAATGGAGACATCCAGGTATGAGAGCTATTACAGAATCTGCTAATGATGTTGTTGTTTGGGATAATGATTTGATTTCTTACGCTAAAGAGTCTAATTCTGGTAATTCTAGAAACAATCTGGTTAATGTTCTGGCTGAACATAGACATTATTCTAGACAAGAAGCTATGGAAGAAATTGGTGAAATGAGAAATCAAGCTATTGCTGATATGGTTGCTGTTAGACCATCTTTGGAGGCTTTGGGTTCTGATGCTGTTTTGGCTTATGTTAGAGGTTTAGAATTTTGGATTTCCGGTTCTGTTGATTATTCTTTGACTTCTTCTAGATACACTGATGCTTGGAGAACAGCTAGACAACCATCTATTAGATAA")

st.write("##### TIC:")
st.image('image/LT22.png')

st.write("##### Doi: [10.3762/bjoc.12.173](https://doi.org/10.3762/bjoc.12.173)")
st.write("##### Cite: Rabe, P., Schmitz, T., and Dickschat, J.S. (2016). Mechanistic investigations on six bacterial terpene cyclases. Beilstein Journal of Organic Chemistry 12:1839-1850.")