import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT23")
st.write("##### Former name: Sce_C15-TPS20")
st.write("##### TPS original information: Sce_C15-TPS20_10-epi-cubebol_11.245min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Sorangium cellulosum Soce56_")
st.write("##### UniProt ID or NCBI ID: [A9GK58](https://www.uniprot.org/uniprotkb/A9GK58/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT23\nMHRALLCPFPATTPHPQAAQLANDCLEWTRKCGLLPDESPRTLDKVRSYSALAAHCYPDAHFERLRAICDYYSWLFFFDDVCENTSLNGAEPKVVSSLLFDVYGVLRGPTAAVGHAPFAQALADIWRRIGDGCPGFWRRRLIRHVENYIDGCVWEAQNRQLDRVPSRAVFEGMRMHTSTMYEFWDFIEYAGDLFLPDEVVEHPLVAEVRRAGNAIASFANDIYSLRKETSNRDVHNLVVVLMHEERIELEAAYARAAGIHDAQVEHFLDLVKHLPTFSATIDRNLARYVEGIRIWIRANHDWSIVTPRYNEPDAR")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT23\nATGCATAGAGCTTTGTTATGTCCATTTCCAGCTACAACACCACATCCACAAGCTGCTCAATTGGCTAATGATTGTTTAGAATGGACTAGAAAATGCGGTTTGTTACCAGATGAATCTCCAAGAACTTTGGATAAAGTTAGATCTTATTCCGCTTTGGCTGCTCATTGTTATCCAGATGCTCATTTTGAAAGATTAAGAGCTATTTGTGACTACTATTCTTGGTTATTTTTCTTCGATGACGTTTGTGAAAACACATCTTTGAATGGTGCTGAACCAAAAGTTGTTTCTTCTTTGTTGTTTGATGTCTATGGTGTTTTAAGAGGTCCAACTGCTGCTGTTGGTCATGCTCCATTTGCTCAAGCTTTGGCTGATATTTGGAGAAGAATTGGTGATGGTTGTCCAGGTTTTTGGAGAAGAAGATTAATTAGACATGTCGAAAACTACATCGATGGTTGTGTTTGGGAAGCTCAAAATAGACAATTGGATAGAGTTCCATCTAGAGCTGTTTTTGAAGGTATGAGAATGCATACATCTACTATGTATGAATTTTGGGATTTCATCGAATACGCTGGTGATTTATTTTTACCAGATGAGGTTGTTGAACATCCATTGGTTGCTGAAGTTAGAAGAGCTGGTAATGCTATTGCTTCTTTTGCTAATGATATCTATTCCTTAAGGAAGGAAACTTCTAATAGAGATGTTCATAACTTGGTTGTTGTTTTAATGCATGAAGAAAGAATCGAATTGGAAGCTGCTTATGCTAGAGCTGCTGGTATTCATGATGCTCAAGTTGAACATTTTTTGGATTTGGTTAAGCATTTGCCAACTTTTTCTGCTACAATTGATAGAAATCTGGCTAGATATGTTGAAGGTATTAGAATTTGGATCAGAGCTAATCATGATTGGTCTATTGTTACACCAAGATATAATGAACCAGATGCTAGATAA")

st.write("##### TIC:")
st.image('image/LT23.png')

st.write("##### Doi: [10.1039/c6ob00130k](https://doi.org/10.1039/c6ob00130k)")
st.write("##### Cite: Schifrin, A., Khatri, Y., Kirsch, P., Thiel, V., Schulz, S., and Bernhardt, R. (2016). A single terpene synthase is responsible for a wide variety of sesquiterpenes in Sorangium cellulosum Soce56. Organic & biomolecular chemistry 14:3385-3393.")