import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT24")
st.write("##### Former name: Sgr_C15-TPS21")
st.write("##### TPS original information: Sgr_C15-TPS21_(+)-Caryolan-1-ol_11.845min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces griseus_")
st.write("##### UniProt ID or NCBI ID: [B1W019](https://www.uniprot.org/uniprotkb/B1W019/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT24\nMSQITLPAFHMPFQSAGCHPGLAETREAAWEWAAAEGLDLSVPARRKMIRTRPELWISLIFPQATQAHLDLFCQWLFWAFLVDDEFDDGPAGRDPLMCERAIARLVDVFDGAAPNGPMERALAGLRDRTCRGRSPQWNRQFRRDTAAWLWTYYAEAVERAAGQVPSRAEFAKHRRDSVAMQPFLCLHEITAGIDLPDSARSLPAYIALRNAVTDHSGLCNDICSFEKEAALGYEHNAVRLIQRDRGSTLQEAVDEAGIQLARIAERVQRAERELIEEIEAAGIDGPTRTALERCVRDYRGLVRGDFDYHARAERYTRPDLVELDERDSLSRHFAA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT24\nATGTCTCAAATCACTTTGCCAGCTTTTCACATGCCATTTCAATCTGCTGGTTGTCATCCAGGTTTAGCTGAAACTAGAGAAGCTGCTTGGGAATGGGCTGCTGCTGAAGGTTTGGATTTGTCTGTTCCAGCTAGAAGAAAAATGATTAGAACTAGACCAGAATTGTGGATTTCTTTAATTTTCCCACAAGCTACTCAAGCTCATTTAGATTTGTTTTGTCAATGGTTATTCTGGGCTTTTTTGGTTGATGATGAATTTGATGATGGTCCAGCTGGTAGAGATCCATTAATGTGTGAAAGAGCTATTGCTAGATTGGTTGATGTTTTTGATGGTGCTGCTCCAAATGGTCCAATGGAAAGAGCTTTAGCTGGTTTAAGAGATAGAACTTGTAGAGGTAGATCTCCACAATGGAATAGACAATTTAGAAGAGATACTGCTGCTTGGTTATGGACATATTATGCTGAAGCTGTTGAAAGAGCTGCTGGTCAAGTTCCATCTAGAGCTGAATTTGCTAAACATAGAAGAGATTCTGTTGCTATGCAACCATTTTTATGTTTACATGAAATCACCGCTGGTATTGATTTACCAGATTCTGCTAGATCTTTACCAGCTTATATTGCTTTGAGAAATGCTGTTACTGATCATTCTGGTTTGTGTAATGATATTTGTTCTTTCGAAAAGGAGGCTGCTTTGGGTTATGAACATAATGCTGTTAGATTAATCCAGAGAGATAGAGGTTCTACTTTACAAGAAGCTGTTGATGAAGCTGGTATTCAATTGGCTAGAATTGCTGAAAGAGTTCAAAGAGCTGAAAGAGAATTAATTGAAGAAATCGAAGCTGCTGGTATTGACGGTCCAACAAGAACAGCTTTGGAAAGATGTGTTAGAGATTATAGAGGTTTAGTTAGAGGTGATTTTGATTATCATGCTAGAGCTGAAAGGTATACAAGACCAGATTTGGTTGAATTGGATGAAAGAGATTCTTTATCTAGACATTTCGCTGCT")

st.write("##### TIC:")
st.image('image/LT24.png')

st.write("##### Doi: [10.1074/jbc.M111.265652](https://doi.org/10.1074/jbc.M111.265652)")
st.write("##### Cite: Nakano, C., Horinouchi, S., and Ohnishi, Y. (2011). Characterization of a novel sesquiterpene cyclase involved in (+)-caryolan-1-ol biosynthesis in Streptomyces griseus. Journal of Biological Chemistry 286:27980-27987.")