import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT25")
st.write("##### Former name: Kse_C15-TPS22")
st.write("##### TPS original information: Kse_C15-TPS22_(+)-corvoletherB_9.865min_NMR; Kse_C15-TPS22_(+)-corvoletherA_10.730min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Kitasatospora setae_")
st.write("##### UniProt ID or NCBI ID: [E4N7E5](https://www.uniprot.org/uniprotkb/E4N7E5/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT25\nMIPRFDFPWPSACHPHARQAEQGALAFAERHGLVPTAAYRSRLERTRYGWLAARCYPDADDVLLQLCADYFIWFFIVDDLFVDRVDTLSERTIPNLTAMIDVLDHHRPGAEPVFGEHAWLDVCTRLRAYLSDEHFQRFAHGMRMWAATAGLQIANHLGADTVDVAPYETIRRHTSGTNPCLALADAAKHGPVTPAEYHSPPVQRLVLHANNVVCWSNDVQSLKMELNQPGQYWNMAAIYAHRGLSLQQAVDLVALRVRGEIASFQSLALTLEPHASRPLRGFVDGLRHWMRGYQDWVENDTLRYADAFIAEDADDTAVRT")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT25\nATGATCCCAAGATTTGATTTCCCATGGCCATCTGCTTGTCATCCACATGCTAGACAAGCTGAACAAGGTGCTTTAGCTTTTGCTGAAAGACATGGTTTAGTTCCAACAGCTGCTTATAGATCTAGATTGGAAAGAACTAGATACGGTTGGTTGGCTGCTAGATGTTATCCAGATGCTGATGATGTTTTGTTACAATTGTGTGCTGATTATTTCATCTGGTTTTTTATCGTTGACGATTTATTCGTTGACAGAGTTGATACATTGTCTGAAAGAACAATTCCAAATTTGACTGCTATGATTGATGTTTTGGATCATCATAGACCAGGTGCTGAACCAGTTTTTGGTGAACATGCTTGGTTGGATGTTTGTACTAGATTGAGAGCTTATTTATCTGATGAACATTTCCAAAGATTCGCTCATGGTATGAGAATGTGGGCTGCTACTGCTGGTTTGCAAATTGCTAATCATTTGGGTGCTGATACAGTTGATGTTGCTCCATACGAAACTATTAGAAGACATACTTCTGGTACTAATCCATGTTTAGCTTTAGCTGATGCTGCTAAACATGGTCCAGTTACTCCAGCTGAATATCATTCTCCACCAGTTCAAAGATTAGTTTTACATGCTAATAACGTCGTTTGTTGGTCTAATGATGTTCAATCTTTAAAGATGGAGTTGAATCAACCAGGTCAATATTGGAATATGGCTGCTATTTATGCTCATAGAGGTTTGTCTTTGCAACAAGCTGTTGATTTGGTTGCTTTGAGAGTTAGAGGTGAAATTGCTTCTTTTCAATCTTTGGCTTTAACTTTAGAGCCACATGCTTCTAGACCATTGAGAGGTTTTGTTGATGGTTTAAGACATTGGATGAGAGGTTATCAAGATTGGGTTGAAAATGATACTTTGAGATATGCTGATGCTTTTATTGCTGAAGATGCTGATGACACTGCTGTTAGAACTTAA")

st.write("##### TIC:")
st.image('image/LT25.png')

st.write("##### Doi: [10.1002/anie.201501119](https://doi.org/10.1002/anie.201501119)")
st.write("##### Cite: Rabe, P., Pahirulzaman, K.A., and Dickschat, J.S. (2015). Structures and biosynthesis of corvol ethers—Sesquiterpenes from the actinomycete kitasatospora setae. Angewandte Chemie International Edition 54:6041-6045.")