import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT27")
st.write("##### Former name: Scl_C15-TPS26")
st.write("##### TPS original information: Scl_C15-TPS26_(5S,7S,10R,11S)-cucumene_7.650min__NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces clavuligerus_")
st.write("##### UniProt ID or NCBI ID: [D5SLU6](https://www.uniprot.org/uniprotkb/D5SLU6/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT27\nMPQDVVFDLPWPLRKHPGVAGAREHCLGWLAAQGLADRRGLTAETFVTWQLDELAGYFFPRATQEGLELATDLMVWYFAPFDDQFDGALGRDPRRTAGVCAGLAEVLYGVPEPGPVASSPVGRALGDLWRRSCTGMSPFWRTRARHNWTGYLAAHTAESVPRYHGRTVDAAYCVRQRGYATSSHVIMDLIERTGGFEVPAMVWHHPVLVELRTLTSEMIGISNDLCSAEKEEADGDLSNNLLLVLENHEGLDRPEAIERARALTAERVARFLDVERAVTDVDCLLDGAGREAVRRFVEGLHDLVRGDNEWERTTGRYQPAISGLQDLADLMSSGWDPLASGTAAGHGGHTR")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT27\nATGCCACAAGATGTTGTTTTTGATTTGCCATGGCCATTGAGAAAACATCCAGGTGTTGCTGGTGCTAGAGAACATTGTTTGGGTTGGTTGGCTGCTCAAGGTTTGGCTGATAGAAGAGGTTTAACAGCTGAAACTTTTGTTACTTGGCAATTGGATGAATTGGCTGGTTATTTTTTTCCAAGAGCTACACAAGAAGGTTTGGAATTGGCTACAGATTTAATGGTTTGGTATTTTGCTCCATTTGATGATCAATTTGACGGTGCTTTGGGTAGAGATCCAAGAAGAACAGCTGGTGTTTGTGCTGGTTTGGCTGAAGTTTTATATGGTGTTCCAGAACCAGGTCCAGTTGCTTCTTCTCCAGTTGGTAGAGCTTTGGGTGATTTATGGAGAAGATCTTGTACTGGTATGTCTCCATTTTGGAGAACAAGAGCTAGACATAATTGGACAGGTTATTTAGCTGCTCATACAGCTGAATCTGTTCCAAGATATCATGGTAGAACAGTTGATGCTGCTTATTGTGTTAGACAAAGAGGTTATGCTACTTCTTCTCATGTTATTATGGATTTGATCGAAAGAACTGGTGGTTTTGAAGTTCCAGCTATGGTTTGGCATCATCCAGTTTTGGTTGAATTGAGAACATTGACTTCTGAAATGATTGGTATTTCTAACGATTTGTGTTCTGCTGAAAAAGAAGAAGCTGATGGTGATTTGTCTAATAATTTGTTGTTGGTTCTGGAAAACCATGAAGGTTTGGATAGACCAGAAGCTATTGAAAGAGCTAGAGCTTTAACTGCTGAAAGAGTTGCTAGATTTTTAGATGTTGAAAGAGCTGTTACAGATGTTGATTGTTTGTTGGATGGTGCTGGTAGAGAAGCTGTTAGAAGATTTGTTGAAGGTTTACATGATTTGGTTAGAGGTGATAATGAATGGGAAAGAACAACAGGTAGATATCAACCAGCTATTTCTGGTTTACAAGATTTAGCTGATTTGATGTCTTCTGGTTGGGATCCATTGGCTTCTTAA")

st.write("##### TIC:")
st.image('image/LT27.png')

st.write("##### Doi: [10.1021/acs.biochem.8b00899](https://doi.org/10.1021/acs.biochem.8b00899)")
st.write("##### Cite: Blank, P.N., Pemberton, T.A., Chow, J.-Y., Poulter, C.D., and Christianson, D.W. (2018). Crystal structure of cucumene synthase, a terpenoid cyclase that generates a linear triquiNo informatione sesquiterpene. Biochemistry 57:6326-6335.")