import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT28")
st.write("##### Former name: Cpi_C15-TPS27")
st.write("##### TPS original information: Cpi_C15-TPS27_(1S,6S,7R)-(-)-纬-cadinene_11.025min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Chitinophaga pinensis _")
st.write("##### UniProt ID or NCBI ID: [C7PLV2](https://www.uniprot.org/uniprotkb/C7PLV2/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT28\nMPTITLPRIIYPFPSLINQFVTAAHEQNRQWVADFGFITTPEAMARFDRSRFAWLAARAFPHAGFHELCTIANFNTWLFMLDDQCDEAQLGKKAVYLEHVTDGFMNILKHNTPVDTVLGRSFTDIWERMQALGDTAWQTRFIRSMEEYFTSCHWEAGNRAADIVPTVAEYVTMRPYTGALFADVEAIEIIEKVYLPAHILQHFIVQRLVLACNNIVCWANDIFSCAKEARQGDVHNLVLVLQHERNSTLQEAVNETARMHNEEVKLFTALEKLLPSFGAEMDRELERFMAVLRSWITANYDWSYHDTGRYQVKEVEVVINS")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT28\nATGCCAACTATTACTTTGCCAAGAATTATTTACCCATTCCCATCTTTAATCAACCAATTTGTTACTGCTGCTCATGAACAAAATAGACAATGGGTTGCTGATTTTGGTTTTATTACTACACCAGAAGCTATGGCTAGATTTGATAGATCTAGATTTGCTTGGTTGGCTGCTAGAGCTTTTCCACATGCTGGTTTTCATGAATTGTGTACTATTGCTAATTTCAACACATGGTTGTTTATGTTAGACGATCAATGTGATGAAGCTCAATTGGGTAAAAAAGCTGTTTATTTGGAACATGTTACCGATGGTTTTATGAATATTTTGAAGCATAACACCCCAGTTGATACAGTTTTGGGTAGATCTTTTACAGATATTTGGGAAAGAATGCAAGCTTTAGGTGATACTGCTTGGCAAACAAGATTTATTAGATCTATGGAAGAGTACTTCACTTCTTGTCATTGGGAAGCTGGTAATAGAGCTGCTGATATTGTTCCAACTGTTGCTGAATATGTTACTATGAGACCATATACTGGTGCTTTATTTGCTGATGTTGAAGCTATTGAAATCATTGAAAAGGTTTACTTGCCAGCTCATATTTTGCAACATTTTATTGTTCAGAGGTTGGTTTTGGCTTGTAATAATATTGTTTGCTGGGCTAATGATATCTTTTCTTGTGCTAAAGAAGCTAGACAAGGTGATGTTCATAATTTAGTTTTGGTTTTGCAGCATGAAAGAAATTCTACTTTGCAAGAAGCTGTTAATGAAACAGCTAGAATGCATAATGAAGAAGTTAAATTGTTCACCGCTTTAGAAAAATTGTTGCCATCTTTTGGTGCTGAAATGGATAGAGAATTGGAAAGATTTATGGCTGTTTTAAGATCTTGGATTACTGCTAATTACGATTGGTCTTATCATGATACTGGTAGATATCAAGTTAAGGAAGTTGAAGTTGTTATCAATTCTTAA")

st.write("##### TIC:")
st.image('image/LT28.png')

st.write("##### Doi: [10.3762/bjoc.12.173](https://doi.org/10.3762/bjoc.12.173)")
st.write("##### Cite: Rabe, P., Schmitz, T., and Dickschat, J.S. (2016). Mechanistic investigations on six bacterial terpene cyclases. Beilstein Journal of Organic Chemistry 12:1839-1850.")