import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT29")
st.write("##### Former name: Phy_C15-TPS29")
st.write("##### TPS original information: Phy_C15-TPS29_(-)-drimenol_14.085min_Standard")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Persicaria hydropiper _")
st.write("##### UniProt ID or NCBI ID: [W0FFD7](https://www.uniprot.org/uniprotkb/W0FFD7/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT29\nMSTAVNVPSAVRPADKRPIASFHPSPWGDYFLKYVPCDQVTQAKMEDEVKKVEEDVKKELRKLAKAVGKPLELLNFIDVVERLGVGYRLEQEIEDLVQAIFDNDKFGVDEFDLYHTSLWFRLLRQHGFHVSCDVFGKFKGRNGRFKDSLASDVKGILGLYEASHVRTHGDDTLDEALVFTTTHLKAVVTNQPNHPLVPQVTHALMQPYHKGMPRLESRHFIAFYEKDPYHDKTLLKFGKLDFNLVQALHKKELKDLSRWWKDLDMHAKMPFPSRDRVPEGYFWTLGPFYEPQFALCRKFFLQVFKVTSIVDDIYDAYGTIDELTAFTKAAERWDRSCLDELPEYMKVSYASLIDTFEEFERDLAPQGRSWSVKYAREEMIQMCRVYYQEAKWCHEKYSPTCDEYLEKASIVSFGYNLGTVVCFLGMGDVATKEAFEWARGNPKVVRAAGIIGRLMDDIGSHHFEQGRDHVPSAVECYIRQHGVDEVTAQRELGKRVESSWKDINEMMLKPYMMPKPLLTRILNECRIVDVIYKGEDSYTFSNTTMKKNISHILTDPIPI")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT29\nATGTCTACAGCTGTTAATGTTCCATCTGCTGTTAGACCAGCTGATAAAAGACCAATTGCTTCTTTTCATCCATCTCCATGGGGTGATTATTTTTTAAAATACGTTCCATGCGACCAAGTTACTCAAGCTAAAATGGAAGATGAAGTTAAAAAGGTTGAGGAAGATGTTAAAAAGGAATTAAGAAAGCTGGCTAAAGCTGTTGGTAAACCATTAGAATTGTTAAATTTCATCGACGTTGTCGAAAGATTAGGTGTTGGTTATAGATTAGAACAAGAAATTGAGGATCTGGTTCAAGCTATTTTTGATAATGATAAGTTCGGTGTTGACGAATTTGATTTATATCATACATCCTTGTGGTTCAGATTATTAAGACAACATGGTTTTCACGTTTCTTGTGATGTTTTTGGTAAATTTAAGGGTAGAAACGGTAGATTTAAGGATTCTTTGGCTTCTGATGTTAAAGGTATTTTAGGTTTATACGAGGCTTCTCATGTTAGAACTCATGGTGATGATACTTTGGATGAAGCTTTAGTTTTTACTACAACTCATTTGAAGGCTGTTGTTACTAATCAACCAAATCATCCATTAGTTCCACAAGTTACACATGCTTTGATGCAACCATATCATAAAGGTATGCCAAGATTGGAATCTAGACATTTTATTGCTTTCTACGAAAAGGATCCATATCATGATAAAACTTTGTTGAAGTTCGGTAAATTGGATTTTAACTTGGTTCAAGCTTTGCATAAAAAGGAATTGAAAGATTTGTCCAGATGGTGGAAAGATTTAGATATGCATGCTAAAATGCCATTTCCATCTAGAGATAGAGTTCCAGAAGGTTATTTTTGGACTTTGGGTCCATTTTATGAACCACAATTTGCTTTGTGTAGAAAATTTTTCCTGCAAGTTTTCAAGGTTACTTCTATTGTTGATGATATCTACGATGCTTATGGTACAATTGATGAATTAACAGCTTTCACTAAGGCTGCTGAAAGATGGGATAGATCTTGTTTGGATGAATTGCCAGAATATATGAAAGTTTCTTACGCTTCTTTGATCGATACTTTTGAAGAATTTGAGAGAGATTTGGCTCCACAAGGTAGATCTTGGTCTGTTAAATATGCTAGAGAAGAAATGATCCAAATGTGTAGAGTTTATTACCAAGAAGCTAAATGGTGTCATGAAAAATATTCTCCAACTTGTGATGAATACTTGGAAAAAGCTTCTATTGTTTCTTTCGGTTATAACTTGGGTACTGTTGTTTGTTTTTTGGGTATGGGTGATGTTGCTACTAAAGAAGCTTTTGAATGGGCTAGAGGTAATCCAAAAGTTGTTAGAGCTGCTGGTATTATTGGTAGATTAATGGATGATATCGGTTCTCATCATTTTGAACAAGGTAGAGATCATGTTCCATCTGCAGTTGAATGTTATATTAGACAACATGGAGTTGATGAAGTTACAGCTCAAAGAGAATTGGGTAAAAGAGTTGAATCTTCTTGGAAAGATATCAATGAAATGATGTTGAAGCCATATATGATGCCAAAACCATTATTGACAAGAATTTTGAACGAGTGTAGAATTGTTGATGTTATTTACAAGGGTGAAGATTCTTATACTTTCTCTAATACTACCATGAAGAAGAATATCTCTCATATTTTGACCGATCCAATTCCAATTTAA")

st.write("##### TIC:")
st.image('image/LT29.png')

st.write("##### Doi: [10.1111/tpj.13527](https://doi.org/10.1111/tpj.13527)")
st.write("##### Cite: Henquet, M.G., Prota, N., van der Hooft, J.J., Varbanova‐Herde, M., Hulzink, R.J., de Vos, M., Prins, M., de Both, M.T., Franssen, M.C., and Bouwmeester, H. (2017). Identification of a drimenol synthase and drimenol oxidase from Persicaria hydropiper, involved in the biosynthesis of insect deterrent drimanes. The Plant Journal 90:1052-1063.")