import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT30")
st.write("##### Former name: Ama_C15-TPS30")
st.write("##### TPS original information: Ama_C15-TPS30_dauca-4,7-diene_11.585min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Aspergillus aculeatus_")
st.write("##### UniProt ID or NCBI ID: [A0A1L9WUI2](https://www.uniprot.org/uniprotkb/A0A1L9WUI2/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT30\nMTPDLVARFWLVELHVRLPAWLRGITSASASVAVKRPGSSKKPLEPAPQPAPYKPTHYRHIIYAYDVMEEKCEIPVLEHDPFDFLDPQKTLVPPENTILIDPVAVGLPWFSTMKGTPQCIHWREAEAAGLELIEQVMAARGAGAVIPEKLKTSDQRRKMMELVETAVTICIYLYAVSDAARIRVLTKSIVFLFLHDDVMESKANAEGNSILEGWDTDTFKANELEGESRNDIFLDFCREAIALDPVLGLELMQDTVRWARYSRVNSTKADKTHATWQDFRDFRELDIAYDFMITAVRFGAAILYDPAERPVFEWIEKLYIRHCLYINDLYSYEKEFREHQQEGAPLHNSVHMIEQVLSVPPGSAKAILRSVLWDCERQVREEYVRLMQLPELTHTQKVYLQRLIESFAGNYMYSMSTYRYARLSGKLIGPPPEDCLLKNYVQ")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT30\nATGACACCAGATTTGGTTGCTAGATTTTGGTTGGTTGAATTGCATGTTAGATTACCAGCTTGGTTAAGAGGTATTACTTCTGCTTCTGCTTCTGTTGCTGTTAAAAGACCAGGTTCTTCTAAAAAACCATTGGAACCAGCTCCACAACCAGCTCCATATAAACCAACACATTATAGACATATCATCTACGCTTATGATGTTATGGAAGAAAAATGTGAAATCCCAGTTTTAGAACATGATCCATTTGATTTTCTGGATCCACAAAAAACTTTGGTTCCACCAGAAAATACAATTTTAATCGATCCAGTTGCTGTTGGTTTACCATGGTTTTCTACTATGAAAGGTACTCCACAATGTATTCATTGGAGAGAAGCTGAAGCTGCTGGTTTAGAATTAATTGAACAAGTTATGGCTGCTAGAGGTGCTGGTGCTGTTATTCCAGAAAAATTGAAAACATCTGACCAAAGAAGAAAGATGATGGAATTAGTTGAAACAGCTGTTACTATTTGTATCTATTTGTACGCTGTTTCTGATGCTGCTAGAATTAGAGTTTTGACTAAATCTATCGTCTTCTTGTTTTTGCATGATGATGTTATGGAGTCTAAAGCTAATGCTGAAGGTAATTCTATTTTGGAAGGTTGGGATACAGATACATTTAAAGCTAATGAACTGGAAGGTGAATCTAGAAATGATATTTTTCTGGATTTCTGCAGAGAAGCTATTGCTTTAGATCCAGTTTTGGGTTTGGAATTAATGCAAGATACTGTTAGATGGGCTAGATATTCTAGAGTTAATTCTACAAAGGCTGATAAAACTCATGCTACATGGCAAGATTTTAGAGATTTTAGAGAATTGGACATCGCTTATGATTTTATGATTACAGCTGTTAGATTCGGTGCTGCTATTTTATATGATCCAGCTGAAAGACCAGTTTTTGAATGGATTGAAAAATTGTACATCAGGCATTGTTTGTATATCAATGATTTGTACTCCTACGAAAAGGAATTTAGAGAACATCAACAAGAAGGTGCTCCATTGCATAATTCTGTTCACATGATTGAACAAGTCTTGTCTGTTCCACCAGGTTCTGCTAAAGCTATTTTGAGATCTGTTTTGTGGGATTGTGAAAGACAAGTTAGAGAAGAATATGTTAGATTGATGCAATTGCCAGAATTAACACATACACAAAAAGTTTACCTGCAAAGATTAATCGAATCTTTTGCTGGTAATTACATGTATTCTATGTCTACTTACAGGTATGCTAGATTGTCTGGTAAATTAATTGGTCCACCACCAGAAGATTGTTTGTTGAAAAATTATGTCCAGTAA")

st.write("##### TIC:")
st.image('image/LT30.png')

st.write("##### Doi: [10.1002/anie.201910200](https://doi.org/10.1002/anie.201910200)")
st.write("##### Cite: Lee, C.F., Chen, L.X., Chiang, C.Y., Lai, C.Y., and Lin, H.C. (2019). The biosynthesis of norsesquiterpene aculenes requires three cytochrome P450 enzymes to catalyze a stepwise demethylation process. Angewandte Chemie International Edition 58:18414-18418.")