import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT32")
st.write("##### Former name: Gfu_C15-TPS32")
st.write("##### TPS original information: Gfu_C15-TPS32_(+)-Eremophilene_10.740min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Gibberella fujikuroi_")
st.write("##### UniProt ID or NCBI ID: [S0DX56](https://www.uniprot.org/uniprotkb/S0DX56/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT32\nMIATINGDTKINGKGHPTEVRIPDMFGSIMSATPMVNPHHFKVKAAADAFIADYLKMDKHEATKNRKADFCFCASAMAPHADAEALRTMVDWLNWIFYFDDDFDEGQLDRDPVAAEKEIRHTLAVLEEGAEIPDRELHPLRYLFRTIWDRVKERAYPDVQTQFKITHKRYLDGLLHQVEATRDGNGQPRTEEDYIRMRRRTVGGYPCISLIAYAHNVDLSQEAFEHPSVQECIAVGCDLAWIHNDIVSYKKDVKSGIEHNFITVLKKNGFTTQQAMDRAGELQDECYRRWYLALASMPIWGESIDREVLRYIEACHSFPLGDLLWSFQTGRYLGATEGYKLHETRVLDLSDLEPIAV")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT32\nATGATCGCTACTATTAACGGTGATACAAAAATTAACGGTAAGGGTCATCCAACTGAAGTTAGAATACCTGATATGTTTGGTTCTATTATGTCTGCTACACCAATGGTTAATCCACATCATTTTAAAGTTAAGGCTGCTGCTGATGCTTTTATTGCTGATTATTTGAAAATGGACAAGCATGAAGCTACAAAAAATAGAAAAGCTGATTTCTGTTTCTGCGCTTCTGCTATGGCTCCACATGCTGATGCTGAAGCTTTAAGAACAATGGTTGATTGGTTAAATTGGATTTTCTACTTCGATGATGACTTTGATGAAGGTCAATTAGATAGAGATCCAGTTGCTGCTGAAAAAGAAATTAGACATACTTTGGCTGTTTTGGAAGAAGGTGCTGAAATTCCAGATAGAGAATTGCATCCATTGAGATATTTATTCAGAACTATCTGGGATAGAGTTAAAGAAAGAGCTTATCCAGATGTTCAAACACAATTTAAAATCACTCACAAGAGATACTTGGATGGTTTGTTACATCAAGTTGAAGCTACAAGAGATGGTAATGGTCAACCAAGAACAGAAGAAGATTATATTAGAATGAGGAGAAGAACAGTTGGTGGTTATCCATGTATTTCTTTAATTGCTTACGCTCATAACGTTGATTTATCTCAAGAAGCTTTTGAACATCCATCTGTTCAAGAATGTATTGCTGTTGGTTGTGATTTAGCTTGGATTCATAATGATATCGTTTCTTATAAGAAGGACGTTAAATCTGGTATTGAACATAATTTCATCACCGTTTTGAAGAAAAACGGTTTTACAACACAACAAGCTATGGATAGAGCTGGTGAATTGCAAGATGAATGTTATAGAAGATGGTATTTGGCTTTAGCTTCTATGCCAATTTGGGGTGAATCTATTGATAGAGAAGTTTTGAGATACATCGAAGCTTGTCATTCTTTTCCATTAGGTGATTTGTTATGGTCTTTTCAAACAGGTAGATATTTGGGTGCTACTGAAGGTTATAAATTACATGAAACTAGGGTTTTGGACTTATCTGATTTAGAACCAATTGCTGTTTAA")

st.write("##### TIC:")
st.image('image/LT32.png')

st.write("##### Doi: [10.1002/anie.201603782](https://doi.org/10.1002/anie.201603782)")
st.write("##### Cite: Burkhardt, I., Siemon, T., Henrot, M., Studt, L., R?sler, S., Tudzynski, B., Christmann, M., and Dickschat, J.S. (2016). Mechanistic characterisation of two sesquiterpene cyclases from the plant pathogenic fungus Fusarium fujikuroi. Angewandte Chemie International Edition 55:8748-8751.")