import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT34")
st.write("##### Former name: Mpo_C15-TPS35")
st.write("##### TPS original information: Mpo_C15-TPS35_伪-gurjunene_9.725min_Standard; Mpo_C15-TPS35_5-Hydroxy-a-Gurjunene_11.720min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Marchantia polymorpha_")
st.write("##### UniProt ID or NCBI ID: [A0A1L5YKS7](https://www.uniprot.org/uniprotkb/A0A1L5YKS7/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT34\nMAPTLDSDSTVLSIRSDFRQGRVQRQLKSELYRNDNRMSVENDFRAPYIQLPYPQARLNPKTTECMNITFDWLSSMGIDKQVDPSVWQAFVASRLSDIVGYSCNEDIEPEDFLWLCKFTTWLFIFDSMMDDGHWAENICMSSHAILEMNLILMWNDPENERLLECSKSILDLVMAIDASGSRLQLDKFHADMVDARKKSKSLLDVKMGVFTSAFRDCWMEYVEDVPAEYTTRIAQTFQRYISSCLWEEKNRKEQAECMNVADYVTLRRFSGCVEPYFVYVDRIIEHKRRKSPISHIPNTLFYGEHMQNMLAAATDVICWHNDIFSFPKETIREGDKHNLVYTVFQQYNCHSCTQAGELIVELLHDRIAEMEFAYEKLRSAAAPEFHPAIDVYIKNCRDWISGSHEFHMNSSRYNVRSFSGPPENVKHINSV")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT34\nATGGCTCCAACTTTGGATTCTGATTCTACTGTTTTATCTATCAGATCTGATTTCAGACAAGGTAGAGTTCAAAGACAATTAAAATCTGAACTGTACAGAAACGATAACAGAATGTCTGTTGAAAATGATTTCAGAGCTCCATATATTCAATTGCCATATCCACAAGCTAGATTAAATCCAAAAACTACAGAATGTATGAACATCACTTTCGATTGGTTGTCTTCTATGGGTATTGATAAACAAGTTGATCCATCTGTTTGGCAAGCTTTTGTTGCTTCTAGATTGTCTGATATTGTTGGTTATTCTTGTAACGAAGATATCGAACCAGAAGATTTTTTGTGGTTGTGTAAATTTACCACTTGGTTGTTTATCTTCGATTCTATGATGGATGATGGTCATTGGGCTGAAAATATTTGTATGTCTTCTCATGCTATCTTGGAAATGAATTTAATCTTGATGTGGAACGATCCAGAAAATGAAAGATTATTGGAATGTTCTAAGTCCATTTTGGATTTAGTTATGGCTATTGATGCTTCTGGTTCTAGATTGCAATTGGATAAATTTCATGCTGATATGGTTGATGCTAGAAAAAAATCTAAGTCTTTGTTGGATGTCAAGATGGGTGTTTTTACTTCTGCTTTTAGAGATTGTTGGATGGAATATGTTGAAGATGTTCCAGCTGAATATACTACTAGAATTGCTCAAACATTCCAAAGATATATCTCTTCTTGTTTGTGGGAAGAAAAAAATAGAAAGGAACAAGCTGAATGTATGAATGTTGCTGATTATGTTACTTTGAGAAGATTTTCTGGTTGTGTTGAACCATATTTTGTTTATGTTGACAGAATCATCGAGCATAAAAGAAGAAAATCTCCAATTTCTCACATCCCAAATACTTTGTTTTACGGTGAACACATGCAAAATATGTTAGCTGCTGCTACTGATGTTATTTGTTGGCATAATGATATCTTCTCTTTCCCAAAAGAAACAATTAGAGAAGGTGATAAACACAATTTGGTTTATACTGTTTTCCAGCAATACAATTGTCATTCTTGTACTCAAGCTGGTGAATTGATTGTTGAATTATTGCATGATAGGATCGCTGAAATGGAATTTGCTTATGAAAAATTGAGGTCTGCTGCTGCTCCAGAATTTCATCCAGCTATTGATGTTTATATCAAGAATTGTAGGGACTGGATTTCTGGTTCTCATGAATTTCACATGAATAGTTCTAGATACAACGTTAGATCTTTCTCTGGTCCACCAGAAAATGTTAAACATATTAATTCCGTCTAA")

st.write("##### TIC:")
st.image('image/LT34.png')

st.write("##### Doi: [10.1105/tpc.16.00062](https://doi.org/10.1105/tpc.16.00062)")
st.write("##### Cite: Kumar, S., Kempinski, C., Zhuang, X., Norris, A., Mafu, S., Zi, J., Bell, S.A., Nybo, S.E., Kinison, S.E., and Jiang, Z. (2016). Molecular diversity of terpene synthases in the liverwort Marchantia polymorpha. The Plant Cell 28:2632-2650.")