import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT36")
st.write("##### Former name: Spr_C15-TPS41")
st.write("##### TPS original information: Spr_C15-TPS41_(+)-(1(10)E,4E,6S,7R)-Germacradien-6-ol_13.225min_NMR; Spr_C15-TPS41_Shyobunol_11.115min_NMR; Spr_C15-TPS41_5,10-di-epi-shyobunol_11.175min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces pratensis_")
st.write("##### UniProt ID or NCBI ID: [E8W6C7](https://www.uniprot.org/uniprotkb/E8W6C7/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT36\nMTSQASAPKIPQLWVPLPSGIHPSWREIDQGSAAWLDRFGLYSDHAQRERLTRISVGEITGRGGPDGRLAALQWTADFLMWLFAFDDEYCDEGPAAASPDATLLIITKLQRIVEVPWAAPADDNYSAALLELRLRLDDLTTPVQTARWAASFRAYLQGQIWMAANSTYGRIPTLSDHLAVRLDSSGVKIFSTLSEIIHGYDLPAADYDRHDVRGFVEVFAAIIGWSNDLVSYHKERRRSQDSYGNVVDLIAHERQCSVEEAVSETATMHTRAMALYLRLRDQILRDAEPELRKWITDCDSWIRADYDWSLTTHRYVNPDDPADLPVGSAEAPFRAREADQPLPIASVSWWWTLLKD")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT36\nATGACTTCTCAAGCTTCTGCTCCAAAAATTCCACAATTGTGGGTTCCATTGCCATCTGGTATTCATCCATCTTGGAGAGAAATTGATCAAGGTTCTGCTGCTTGGTTAGATAGATTTGGTTTGTATTCTGATCACGCTCAAAGAGAAAGATTGACAAGAATTTCTGTTGGTGAAATTACAGGTAGAGGTGGTCCAGATGGTAGATTGGCTGCTTTACAATGGACTGCTGATTTTTTAATGTGGTTGTTTGCTTTTGACGATGAATATTGTGATGAAGGTCCAGCTGCTGCTTCTCCAGATGCTACATTATTGATTATTACAAAGCTGCAAAGGATCGTTGAAGTTCCATGGGCTGCTCCAGCTGATGATAATTATTCTGCTGCTTTATTAGAGTTGAGATTAAGATTAGACGACTTGACAACTCCAGTTCAAACTGCTAGATGGGCTGCTTCTTTTAGAGCTTATTTACAAGGTCAAATCTGGATGGCTGCTAATTCTACTTATGGTAGAATACCTACATTGTCTGATCATTTAGCTGTTAGATTAGATTCTTCTGGTGTTAAAATCTTCTCTACTTTATCTGAAATCATCCATGGTTATGATTTGCCAGCTGCTGATTATGATAGACATGATGTTAGAGGTTTTGTTGAAGTTTTTGCTGCTATTATTGGTTGGTCTAATGATTTGGTTTCTTATCATAAGGAGAGAAGAAGATCTCAAGATTCTTATGGTAATGTTGTTGATTTGATCGCTCATGAAAGACAATGTTCTGTTGAAGAAGCTGTTTCTGAAACTGCTACAATGCATACTAGAGCTATGGCTTTGTATTTGAGATTAAGGGATCAAATTCTGAGAGATGCTGAACCAGAATTAAGAAAATGGATTACTGATTGTGACTCTTGGATTAGAGCTGATTATGACTGGTCTTTAACAACTCATAGATATGTTAACCCAGATGATCCAGCTGATTTGCCAGTTGGTTCTGCTGAAGCTCCATTTAGAGCTAGAGAAGCTGATCAACCATTACCAATTGCTTCTGTTTCTTGGTGGTGGACTTTATTGAAAGATTAA")

st.write("##### TIC:")
st.image('image/LT36.png')

st.write("##### Doi: [10.1002/anie.201507615](https://doi.org/10.1002/anie.201507615)")
st.write("##### Cite: Rabe, P., Barra, L., Rinkel, J., Riclea, R., Citron, C.A., Klapschinski, T.A., Janusko, A., and Dickschat, J.S. (2015). Conformational Analysis, Thermal Rearrangement, and EI‐MS Fragmentation Mechanism of (1 (10) E, 4E, 6S, 7R)‐Germacradien‐6‐ol by 13C‐Labeling Experiments. Angewandte Chemie International Edition 54:13448-13451.")