import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT37")
st.write("##### Former name: Zze_C15-TPS42")
st.write("##### TPS original information: Zze_C15-TPS42_a-Humulene_10.35min_Standard")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _ Zingiber zerumbet_")
st.write("##### UniProt ID or NCBI ID: [B1B1U3](https://www.uniprot.org/uniprotkb/B1B1U3/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT37\nMERQSMALVGDKEEIIRKSFEYHPTVWGDYFIRNYSCLPLEKECMIKRVEELKDRVRNLFEETHDVLQIMILVDSIQLLGLDYHFEKEITAALRLIYEADVENYGLYEVSLRFRLLRQHGYNLSPDVFNKFKDDKGRFLPTLNGDAKGLLNLYNAAYLGTHEETILDEAISFTKCQLESLLGELEQPLAIEVSLFLETPLYRRTRRLLVRKYIPIYQEKVMRNDTILELAKLDFNLLQSLHQEEVKKITIWWNDLALTKSLKFARDRVVECYYWIVAVYFEPQYSRARVITSKAISLMSIMDDIYDNYSTLEESRLLTEAIERWEPQAVDCVPEYLKDFYLKLLKTYKDFEDELEPNEKYRIPYLQEEIKVLSRAYFQEAKWGVERYVPALEEHLLVSLITAGYFAVACASYVGLGEDATKETFEWVASSPKILKSCSIHCRLMDDITSHQREQERDHFASTVESYMKEHGTSAKVACEKLQVMVEQKWKDLNEECLRPTQVARPLIEIILNLSRAMEDIYKHKDTYTNSNTRMKDNVSLIFVESFLI")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT37\nATGGAAAGACAATCTATGGCTTTAGTTGGTGATAAAGAAGAAATTATCAGGAAATCTTTCGAGTATCATCCAACAGTTTGGGGTGATTATTTTATTAGAAACTACTCTTGCCTGCCATTAGAAAAAGAATGTATGATTAAGAGGGTCGAAGAATTAAAAGATAGAGTTAGAAACCTGTTCGAAGAAACTCATGATGTTTTGCAAATTATGATCTTGGTTGATTCTATCCAATTGTTGGGTTTGGATTATCATTTTGAAAAGGAAATCACCGCTGCTTTGAGATTGATTTATGAAGCTGATGTTGAAAACTACGGTTTATATGAAGTTTCTTTGAGATTCAGACTGTTAAGACAACATGGTTATAATTTGTCTCCAGATGTTTTTAACAAGTTCAAAGATGATAAGGGTAGATTTTTGCCAACATTAAATGGTGATGCTAAAGGTTTATTGAACTTGTATAACGCTGCTTATTTGGGTACACATGAAGAAACAATTTTGGATGAAGCTATTTCTTTCACAAAGTGTCAATTGGAATCTTTGTTGGGTGAATTAGAACAACCATTGGCTATTGAAGTTTCTTTATTTTTGGAGACACCATTATACAGAAGAACAAGAAGATTGTTGGTTAGAAAATACATCCCAATTTACCAAGAAAAGGTTATGAGAAATGACACAATTTTGGAATTGGCTAAATTGGATTTCAACTTATTGCAATCTCTGCATCAAGAAGAAGTTAAAAAAATCACAATCTGGTGGAATGATTTGGCTTTGACTAAATCTTTGAAGTTTGCTAGAGATAGAGTTGTTGAATGTTATTATTGGATCGTTGCTGTTTATTTCGAACCACAATATTCTAGAGCTAGAGTTATTACTTCTAAGGCTATTTCTTTGATGTCTATTATGGATGATATCTACGATAACTACTCTACATTAGAAGAATCTAGATTGTTGACAGAAGCTATTGAAAGATGGGAACCACAAGCTGTTGATTGTGTTCCAGAATATTTGAAAGATTTCTACTTGAAGCTGTTGAAAACTTATAAGGATTTCGAAGATGAGTTGGAACCAAATGAAAAATATAGAATCCCATACTTGCAGGAAGAAATTAAAGTTTTATCCAGAGCTTACTTCCAAGAAGCTAAATGGGGTGTTGAAAGATATGTTCCAGCTTTAGAAGAACATTTATTGGTTTCTTTGATCACTGCTGGTTATTTTGCTGTTGCTTGTGCTTCTTATGTTGGTTTAGGTGAAGATGCTACTAAAGAAACATTTGAATGGGTTGCTTCTTCTCCAAAAATTTTGAAATCTTGTTCCATCCATTGCAGATTGATGGATGATATTACTTCTCATCAAAGAGAACAAGAAAGAGATCATTTTGCTTCTACAGTTGAATCTTATATGAAGGAACATGGTACTTCTGCTAAAGTTGCTTGTGAAAAATTACAAGTTATGGTTGAACAGAAGTGGAAAGATTTGAATGAAGAATGTTTGAGACCAACTCAAGTTGCTAGACCATTGATTGAAATTATTTTGAACCTGTCTAGGGCTATGGAAGATATTTATAAACATAAGGACACCTACACTAACTCTAATACAAGAATGAAAGACAACGTTTCTTTGATTTTCGTTGAATCTTTCTTGATCTAA")

st.write("##### TIC:")
st.image('image/LT37.png')

st.write("##### Doi: [10.1007/s00425-008-0700-x](https://doi.org/10.1007/s00425-008-0700-x)")
st.write("##### Cite: Yu, F., Okamto, S., Nakasone, K., Adachi, K., Matsuda, S., Harada, H., Misawa, N., and Utsumi, R. (2008). Molecular cloning and functional characterization of α-humulene synthase, a possible key enzyme of zerumbone biosynthesis in shampoo ginger (Zingiber zerumbet Smith). Planta 227:1291-1299.")