import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT38")
st.write("##### Former name: Kse_C15-TPS43")
st.write("##### TPS original information: Kse_C15-TPS43_(2Z,6E)-hedycaryol_11.425min")
st.write("##### TPS type: No information")

st.write("##### Species: _Kitasatospora setae_")
st.write("##### UniProt ID or NCBI ID: [E4MYY0](https://www.uniprot.org/uniprotkb/E4MYY0/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT38\nMAEFEIPDFYVPFPLECNPHLEEASRAMWEWIDANGLAPTERARDRMRRTGADLSGAYVWPRADLDTLTIGLKWIALTFRIDDQIDEDDTAERLPARMTAIDELRGTLHGLPVSGRSPTARALGALWQETALGRPATWCDAFIGHFEAFLQTYTTEAGLNAHGAGLRLDDYLDRRMYSVGMPWLWDLDELRLPIFLPGSVRTCGPMNKLRRAGALHIALVNDVFSVERETLVGYQHNAVTIIREAQGCSLQEAVDQVAVLVEAQLHTVLQARQELLEELDRQALPSRAREAAVDYAANVAANLSGQLVWHSSVERYAVDDLQSAADPRATPTTSSLGI")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT38\nATGGCTGAATTTGAAATCCCAGATTTTTATGTTCCATTCCCATTGGAATGTAATCCACATTTAGAAGAAGCTTCTAGAGCTATGTGGGAATGGATTGATGCTAATGGTTTAGCTCCAACAGAAAGAGCTAGAGATAGAATGAGAAGAACAGGTGCTGATTTGTCTGGTGCTTATGTTTGGCCAAGAGCTGATTTAGATACATTGACAATTGGTTTGAAGTGGATTGCTTTGACTTTTAGAATTGATGATCAGATTGACGAAGATGATACAGCTGAAAGATTACCAGCTAGAATGACTGCTATTGATGAATTGAGAGGTACTTTGCATGGTTTGCCAGTTTCTGGTAGATCTCCAACTGCTAGAGCTTTGGGTGCTTTATGGCAAGAAACTGCTTTAGGTAGACCAGCTACTTGGTGTGATGCTTTTATTGGTCATTTTGAAGCTTTTTTGCAGACTTATACAACTGAAGCTGGTTTGAATGCTCATGGTGCTGGTTTAAGATTAGATGATTATTTAGACAGGAGGATGTATTCTGTTGGTATGCCATGGTTGTGGGATTTAGATGAATTGAGGTTGCCAATTTTTTTGCCAGGTTCTGTTAGAACATGTGGTCCAATGAATAAATTAAGAAGAGCTGGTGCTTTGCATATTGCTTTAGTTAATGATGTTTTCTCCGTTGAAAGAGAAACTTTAGTTGGTTATCAACATAACGCTGTTACAATTATTAGGGAAGCTCAAGGTTGTTCTTTACAAGAAGCTGTTGATCAAGTTGCTGTTTTGGTTGAAGCTCAATTGCATACAGTTTTACAAGCTAGACAAGAATTATTGGAAGAATTAGATAGGCAAGCTTTGCCATCTAGAGCTAGAGAAGCTGCTGTTGATTATGCTGCTAATGTTGCTGCTAATTTGTCTGGTCAATTAGTTTGGCATTCTTCTGTTGAAAGATATGCTGTTGATGATTTGCAATCTGCTGCTGATCCAAGAGCTACTCCAACTACATCTTCTTTGGGTATTTAA")

st.write("##### TIC:")
st.image('image/LT38.png')

st.write("##### Doi: [10.1002/cbic.201300708](https://doi.org/10.1002/cbic.201300708)")
st.write("##### Cite: Baer, P., Rabe, P., Citron, C.A., de Oliveira Mann, C.C., Kaufmann, N., Groll, M., and Dickschat, J.S. (2014). Hedycaryol synthase in complex with nerolidol reveals terpene cyclase mechanism. ChemBioChem 15:213-216.")