import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT39")
st.write("##### Former name: Spr_C15-TPS44")
st.write("##### TPS original information: Spr_C15-TPS44_(+)-IIsoafricanol_11.300min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces malaysiensis_")
st.write("##### UniProt ID or NCBI ID: [A0A291SJC7](https://www.uniprot.org/uniprotkb/A0A291SJC7/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT39\nMHTHASRPHARQSALPRRAALFDFPASADLSPDTGAARQHTIQWLSRFRVFENHASVEEYDALRFDVLTGLFYPRATGADLNLGSDLVGWYFVFDDQFDGELGCRPEEVARLVADVIRVTEEDMAPGGTGGGEGPLLESFRDLWHRINSGRPRVWRDRFRHHWLEYLHSYHREALERTGAAPADGGGDAPRSVEDVLALRRHSIGVQPCLDLNEPFGGYTLPSALHGGFPLARMREATDDVVVFTNDIASLDKELAVGDVHNSVIVQWKLAGGGVEDAVRHIAGLANARYGWFEETAARLPELLAEAGADPGTHRAVGRYVDGMRHVMTGNLGWSLRTARYDERGTEAVSGGRERPWARLTGAEDLIRAGRGAPPPPGSGPDTRQPMPSEPSQLA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT39\nATGCATACACATGCTTCTAGACCACATGCTAGACAATCTGCTTTGCCAAGAAGAGCTGCTTTATTTGATTTTCCAGCTTCTGCTGATTTGTCTCCAGATACTGGTGCTGCTAGACAACATACAATTCAATGGTTGTCTAGATTTAGAGTTTTCGAAAATCACGCTTCTGTTGAAGAATATGATGCTTTGAGATTTGATGTTTTGACAGGTTTATTCTACCCAAGAGCTACTGGTGCTGATTTAAATTTGGGTTCTGATTTGGTTGGTTGGTATTTTGTTTTTGATGATCAATTCGACGGTGAATTGGGTTGTAGACCAGAAGAAGTTGCTAGATTGGTTGCTGATGTTATTAGAGTTACTGAAGAAGATATGGCTCCAGGTGGTACTGGTGGTGGTGAAGGTCCATTATTGGAATCTTTTAGAGATTTATGGCACAGAATTAACTCTGGTAGACCAAGAGTTTGGAGAGATAGATTTAGACATCATTGGTTGGAATATTTGCATTCTTATCATAGAGAGGCTTTGGAAAGAACTGGTGCTGCACCAGCTGATGGTGGTGGTGATGCTCCAAGATCTGTTGAAGATGTTTTGGCTTTAAGAAGACATTCTATTGGTGTTCAACCATGTTTGGATTTGAATGAACCATTTGGTGGTTATACATTACCATCTGCTTTACATGGTGGTTTTCCATTGGCTAGAATGAGAGAAGCTACTGATGATGTTGTTGTTTTTACAAATGACATCGCTTCTTTGGATAAAGAATTGGCTGTTGGTGATGTTCATAATTCTGTTATTGTTCAATGGAAGTTGGCTGGTGGTGGTGTTGAAGATGCTGTTAGACATATTGCTGGTTTAGCTAATGCTAGATATGGTTGGTTTGAAGAAACTGCTGCTAGATTACCAGAATTGTTGGCTGAAGCTGGTGCTGATCCAGGTACTCATAGAGCTGTTGGTAGATATGTTGATGGTATGAGACATGTTATGACTGGTAATTTAGGTTGGTCTTTAAGAACTGCTAGATATGATGAAAGAGGTACTGAAGCTGTTTCTGGTGGTAGAGAAAGACCATGGGCTAGATTGACTGGTGCTGAAGATTTAATTAGAGCTGGTAGAGGTGCTCCACCACCACCAGGTTCTGGTCCAGATACTAGACAACCAATGCCATCTGAACCATCTCAATTAGCT")

st.write("##### TIC:")
st.image('image/LT39.png')

st.write("##### Doi: [10.1039/c7ob00234c](https://doi.org/10.1039/c7ob00234c)")
st.write("##### Cite: Rabe, P., Samborskyy, M., Leadlay, P.F., and Dickschat, J.S. (2017). Isoafricanol synthase from Streptomyces malaysiensis. Organic & Biomolecular Chemistry 15:2353-2358.")