import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT40")
st.write("##### Former name: Bfu_C15-TPS46")
st.write("##### TPS original information: Bfu_C15-TPS46_(2Z,4E)-伪-Ionylideneethane_9.60min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Botryotinia fuckeliana_")
st.write("##### UniProt ID or NCBI ID: [A0A384JQC9](https://www.uniprot.org/uniprotkb/A0A384JQC9/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT40\nMQQVITQTLVDDRFIQISDSKKSEGLATDSTKRQSQEQPIHDKDPIKAATAAMAATPLVKEHQDTWYYPPDIANDLQSINLPAELKGEIFACAWEYTRCVIPNYTNWNRYVAFMRIIIMGIIAEFRGEMVDVTASNNLLGYDLDATLAALFEGTPGHKEMAREYKTFLLITADKASERRDGELFRRYVNALAQSPRHWFRMRDCDALARFTIASALACNDLDDIWFTEDQFEILTEIGDTLYDAVAFYKHRAEGETNSTFAYMPEDLRIKAYSECREILWALDAAWARNPKLANVINFVRFFGGPIHMMMRRYRFVEENLTIGKSETDKVVDQTRKNFKLWNRVDANKRSVLNTQRYKALIARSEELMFPGLAEFLEMGGDGICDKCKYRESYGAELSHQFGGVELCSECRLSWRKYLECFVERATKVFPELKTHFEVPV")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT40\nATGCAACAAGTTATCACTCAAACTTTGGTTGATGATAGATTTATCCAAATCTCTGATTCTAAGAAGTCTGAAGGTTTGGCTACAGATTCTACAAAAAGACAATCTCAAGAACAACCAATTCATGATAAAGATCCAATTAAGGCTGCTACTGCTGCTATGGCTGCTACTCCATTAGTTAAAGAACATCAAGATACTTGGTACTATCCACCAGATATTGCTAATGATTTACAATCTATCAACCTGCCAGCTGAATTGAAAGGTGAAATTTTTGCTTGTGCTTGGGAATATACAAGATGTGTTATTCCAAATTACACCAATTGGAATAGATACGTTGCTTTTATGAGAATTATCATCATGGGTATTATCGCTGAATTTAGAGGTGAAATGGTTGATGTTACTGCTTCTAATAATTTGTTGGGTTATGATTTGGACGCTACTTTGGCTGCTTTATTTGAAGGTACTCCAGGTCATAAAGAAATGGCTAGAGAATATAAAACCTTCTTATTGATCACCGCTGATAAAGCTTCTGAAAGAAGAGATGGTGAATTGTTTAGAAGATATGTTAACGCTTTGGCTCAATCTCCAAGACATTGGTTTAGAATGAGAGATTGTGATGCTTTGGCTAGATTTACTATTGCTTCTGCTTTAGCTTGTAATGATTTAGATGATATCTGGTTTACCGAAGATCAATTTGAAATTTTGACCGAAATCGGTGATACATTATATGATGCTGTTGCTTTTTACAAGCATAGAGCTGAAGGTGAAACTAATTCTACATTTGCTTATATGCCAGAAGATTTGAGAATTAAAGCTTATTCTGAGTGTAGAGAAATCTTATGGGCTTTAGATGCTGCTTGGGCTAGAAATCCAAAATTGGCTAATGTTATTAACTTCGTTAGGTTTTTCGGTGGTCCAATTCACATGATGATGAGAAGATATAGATTCGTTGAAGAAAACTTGACTATCGGTAAATCTGAAACTGATAAAGTTGTTGATCAGACTAGAAAAAACTTCAAATTGTGGAATAGGGTTGATGCTAATAAAAGATCTGTTTTGAACACTCAAAGGTATAAAGCTTTAATCGCTAGATCTGAAGAATTAATGTTCCCAGGTTTAGCTGAATTTTTGGAAATGGGTGGTGATGGTATTTGTGATAAATGTAAATACAGGGAATCCTATGGTGCTGAATTGTCTCATCAATTTGGTGGTGTTGAATTGTGTTCTGAATGTAGATTATCTTGGAGAAAATACTTGGAATGTTTCGTTGAAAGAGCTACTAAAGTTTTTCCAGAATTAAAGACACACTTCGAAGTTCCAGTTTAA")

st.write("##### TIC:")
st.image('image/LT40.png')

st.write("##### Doi: [10.1021/jacs.8b08925](https://doi.org/10.1021/jacs.8b08925)")
st.write("##### Cite: Takino, J., Kozaki, T., Sato, Y., Liu, C., Ozaki, T., Minami, A., and Oikawa, H. (2018). Unveiling Biosynthesis of the Phytohormone Abscisic Acid in Fungi: Unprecedented Mechanism of Core Scaffold Formation Catalyzed by an Unusual Sesquiterpene Synthase. Journal of the American Chemical Society 140:12392-12395.")