import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT42")
st.write("##### Former name:  Fgr_C15-TPS49")
st.write("##### TPS original information: Fgr_C15-TPS49_Longiborneol_12.2miin_NIST")
st.write("##### TPS type: No information")

st.write("##### Species: _Fusarium graminearum_")
st.write("##### UniProt ID or NCBI ID: [I1S104](https://www.uniprot.org/uniprotkb/I1S104/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT42\nMLATPTLSNFDKPSLPSSEGGDPALAARLQPLYSRFLTDLDLQPEYRRHESEKLMEEVLKFAKSTGVPHDLNSHSYQSLMVGYTYADNCLPYHDIEVKVYVAIYTWLATICDDAEALGIIDDVQLFEQRFILGEEQPTVLLRAFADQLKLTYKLYHPLVANLILCSSLNLLTSTSLVARKGIKEKGDHPSKGGNYFAWYIRERDGVGEAYSWFTFPKRQFPNLDIPIEAIEDMTRFIAYLNDVLSFYKESLAGETHNYINHTAAYEGVDSDAALHKTAQDTIDCARRIESVLAGKGEYEKAWRLHASGYLQMHVQRGRYRLIEVGVGDAPDVHEVIKKI")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT42\nATGTTGGCTACTCCAACTTTATCTAATTTTGATAAGCCATCTCTGCCATCTTCTGAAGGTGGTGATCCAGCTTTAGCTGCTAGATTACAACCATTGTATTCTAGATTTCTGACAGATTTAGACTTGCAACCAGAATATAGAAGACATGAATCTGAAAAACTGATGGAAGAAGTTTTGAAATTCGCTAAATCTACTGGTGTTCCACATGATTTGAATAGTCATTCTTATCAATCCTTGATGGTTGGTTATACATACGCTGATAATTGTTTGCCATATCATGATATTGAGGTTAAAGTTTACGTCGCTATTTATACTTGGTTAGCTACAATTTGTGACGATGCTGAAGCTTTGGGTATTATTGATGATGTTCAATTGTTCGAACAGAGATTTATTTTGGGTGAAGAACAACCAACAGTTTTGTTGAGAGCTTTTGCTGATCAATTAAAATTGACATACAAGTTGTACCACCCATTGGTTGCTAATTTAATTTTGTGTTCTTCCTTGAACCTGTTAACATCTACATCTTTGGTTGCTAGAAAAGGTATTAAAGAAAAGGGTGATCATCCATCTAAAGGTGGTAATTATTTTGCTTGGTATATCAGAGAAAGGGATGGTGTTGGTGAAGCTTATTCTTGGTTTACTTTTCCAAAAAGACAGTTTCCAAACTTAGATATTCCAATTGAAGCTATTGAGGATATGACAAGATTTATTGCTTACTTGAACGATGTTTTGTCTTTTTATAAGGAGTCTTTGGCTGGTGAAACTCATAATTATATTAACCATACCGCTGCTTATGAAGGTGTTGATTCTGATGCTGCTTTGCATAAAACTGCTCAAGATACAATTGATTGTGCTAGAAGAATTGAATCTGTTTTAGCTGGTAAAGGTGAATATGAAAAAGCTTGGAGATTACATGCTTCTGGTTATTTACAAATGCATGTTCAAAGAGGTAGATATAGATTGATTGAAGTTGGTGTTGGTGATGCTCCAGATGTTCATGAAGTTATTAAAAAAATCTAA")

st.write("##### TIC:")
st.image('image/LT42.png')

st.write("##### Doi: [10.1128/AEM.02017-09](https://doi.org/10.1128/AEM.02017-09)")
st.write("##### Cite: McCormick, S.P., Alexander, N.J., and Harris, L.J. (2010). CLM1 of Fusarium graminearum Encodes a Longiborneol Synthase Required for Culmorin Production. Applied and Environmental Microbiology 76:136-141.")