import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT43")
st.write("##### Former name: Rca_C15-TPS50")
st.write("##### TPS original information: Rca_C15-TPS50_(1R,6S,7R,10R)-(+)-T-muurolol_12.595min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Roseiflexus castenholzii_")
st.write("##### UniProt ID or NCBI ID: [A7NH01](https://www.uniprot.org/uniprotkb/A7NH01/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT43\nMDQDYRARLVYPFSGAISPHADIVDQATLAWAAMFGLLTDSLRHKSRRLQYGLLAARAYPRADREMLQIAADWIAWLFFMDDQCDETGIGRDLQRMIALHERFLAILDGATPEAHDCALTYALADLRRRLALRAPDNWLRRFSEHVRLYFTANRWETVNRQRGATPNVATYCAARLFSGAVYACFDLIELAEQIELPFYARHHSIVQQLEQAANNIICWCNDVLSYPKEMQHGDRHNLVLVIQGEHQCSLPEAIDRALDLHAREVATFVRKRTCVPYFDAAVNTALEKYVTGLQFWICANRDWSLTATRYAPTHKSQEMVMAVAQQ")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT43\nATGGATCAAGATTACAGAGCTAGATTGGTTTATCCATTTTCTGGTGCTATTTCTCCACATGCTGATATTGTTGATCAAGCTACTTTGGCTTGGGCTGCTATGTTTGGTTTGTTGACTGATTCTTTAAGACATAAATCCAGAAGATTGCAATACGGTTTATTAGCTGCTAGAGCTTATCCAAGAGCTGATAGAGAAATGTTACAAATTGCTGCTGATTGGATTGCTTGGTTGTTTTTTATGGATGATCAATGTGATGAGACTGGTATTGGTAGAGATTTACAAAGAATGATTGCTTTACACGAAAGATTTTTGGCTATTTTAGACGGTGCTACACCAGAAGCTCATGATTGTGCTTTAACATACGCTTTAGCTGATTTAAGAAGAAGATTGGCTTTAAGAGCTCCAGATAATTGGTTGAGAAGATTTTCTGAACATGTTAGATTGTACTTCACTGCTAATAGATGGGAAACTGTTAATAGACAAAGAGGTGCTACACCTAATGTTGCTACATATTGTGCTGCTAGATTATTTTCTGGTGCAGTTTATGCTTGTTTTGATTTAATTGAGCTGGCTGAACAAATTGAATTGCCATTTTATGCTAGACATCATTCTATTGTTCAGCAATTAGAACAAGCTGCTAATAATATTATCTGCTGGTGTAATGATGTCTTATCTTATCCAAAAGAGATGCAACATGGTGATAGACATAATTTGGTTTTGGTTATTCAGGGTGAACATCAATGTTCTTTGCCAGAAGCTATTGATAGAGCTTTAGATTTACATGCTAGAGAAGTTGCTACATTTGTTAGAAAAAGAACATGTGTTCCATACTTTGATGCTGCTGTTAATACTGCTTTAGAAAAATATGTCACCGGTTTACAATTCTGGATTTGTGCTAATAGAGATTGGTCTTTGACTGCTACAAGATATGCTCCAACTCATAAATCTCAAGAAATGGTTATGGCTGTTGCTCAACAATAA")

st.write("##### TIC:")
st.image('image/LT43.png')

st.write("##### Doi: [10.3762/bjoc.12.173](https://doi.org/10.3762/bjoc.12.173)")
st.write("##### Cite: Rabe, P., Schmitz, T., and Dickschat, J.S. (2016). Mechanistic investigations on six bacterial terpene cyclases. Beilstein Journal of Organic Chemistry 12:1839-1850.")