import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT44")
st.write("##### Former name: Cci_C15-TPS51")
st.write("##### TPS original information: Cci_C15-TPS51_伪-muurolene_10.830min_Standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Basidiomycete Coprinopsis cinerea_")
st.write("##### UniProt ID or NCBI ID: [A8NE23](https://www.uniprot.org/uniprotkb/A8NE23/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT44\nMSTPSSSLTTDESPASFILPDLVSHCPFPLRYHPKGDEVAKQTVHWLDSNCPDLTAKERKAMYGLQAGELTGYCYPYTTPERLRVVADFLNYLFHLDNISDGMMTRETAVLADVVMNALWFPEDYRPTKGQAAEELNPGKLARDFWSRCIPDCGPGTQARFKETFGSFFEAVNIQARARDEGVIPDLESYIDVRRDTSGCKPCWVLIEYALGIDLPDFVVEHPVIAALNQGTNDLVTWSNDIFSYNVEQSKGDTHNMIIILMEHHGHTLQSAVDYVGSLCQQTINTFCENKQQLPSWGPEIDDMVAKYVQGLEDWIVGSLHWSFQTRRYFGDEGQEIKQHRLVKLLTVAPPPPPPPPTPPPQSSDADTKKQKVKAQDGKGPVSDEEVWALVRAEQSKGSILESLFGFLTTSLSRIFFGYFFAYSH")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT44\nATGTCTACTCCATCTTCTTCTTTAACTACTGATGAATCTCCAGCTTCTTTTATTTTACCAGATTTGGTTTCTCACTGTCCATTTCCATTAAGATATCATCCAAAAGGTGATGAAGTTGCTAAACAAACAGTTCATTGGTTAGATTCTAACTGTCCAGATTTAACTGCTAAAGAAAGAAAAGCTATGTACGGTTTACAAGCTGGTGAATTAACTGGTTATTGTTATCCATATACCACTCCAGAAAGATTAAGAGTTGTTGCTGATTTTTTGAACTACTTATTCCATTTGGACAACATTTCTGATGGTATGATGACTAGAGAAACAGCTGTTTTAGCTGATGTTGTTATGAATGCTTTGTGGTTTCCAGAAGATTATAGACCAACTAAAGGTCAAGCTGCTGAAGAATTGAATCCAGGTAAATTGGCTAGAGATTTTTGGTCTAGATGTATTCCAGATTGTGGTCCAGGTACTCAAGCTAGATTTAAAGAAACATTTGGTTCTTTCTTCGAGGCTGTTAATATTCAAGCTAGAGCTAGAGATGAAGGTGTTATTCCAGATTTAGAATCTTATATCGACGTTAGAAGAGATACATCTGGTTGTAAACCATGTTGGGTTTTGATTGAATATGCTTTAGGTATTGACTTGCCAGATTTTGTTGTTGAACATCCAGTTATTGCTGCTTTGAATCAAGGTACAAATGATTTGGTTACTTGGTCTAATGATATCTTTTCTTACAACGTTGAGCAATCTAAAGGTGATACACATAATATGATCATCATCTTGATGGAACATCATGGTCATACTTTACAATCTGCTGTTGATTATGTTGGTTCTTTATGTCAACAAACTATCAATACTTTCTGCGAAAATAAGCAACAATTGCCATCTTGGGGTCCAGAAATTGATGATATGGTTGCTAAATATGTCCAAGGTTTGGAAGATTGGATTGTTGGTTCTTTGCATTGGTCTTTTCAAACTAGAAGATATTTCGGTGATGAAGGTCAAGAAATTAAACAACATAGATTGGTTAAGCTGTTGACAGTTGCTCCACCACCACCACCTCCACCACCAACTCCACCACCACAATCTTCTGATGCTGATACAAAAAAACAAAAGGTTAAGGCTCAAGATGGTAAAGGTCCAGTTTCTGATGAAGAAGTTTGGGCTTTGGTTAGAGCTGAACAATCTAAAGGATCTATTTTAGAATCCTTGTTCGGTTTTTTGACTACATCTTTGTCTAGAATTTTCTTCGGTTATTTCTTCGCTTATTCTCATTAA")

st.write("##### TIC:")
st.image('image/LT44.png')

st.write("##### Doi: [10.1111/j.1365-2958.2009.06717.x](https://doi.org/10.1111/j.1365-2958.2009.06717.x)")
st.write("##### Cite: Agger, S., Lopez-Gallego, F., and Schmidt-Dannert, C. (2009). Diversity of sesquiterpene synthases in the basidiomycete Coprinus cinereus. Mol Microbiol 72:1181-1195.")