import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT45")
st.write("##### Former name: Zma_C15-TPS53")
st.write("##### TPS original information: Zma_C15-TPS53_(S)-尾-Macrocarpene_10.920min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Zea mays_")
st.write("##### UniProt ID or NCBI ID: [Q5GJ60](https://www.uniprot.org/uniprotkb/Q5GJ60/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT45\nMAAPTLTADGPRLGQQEMKKMSPSFHPTLWGDFFLSYEAPTEAQEAQMREKAAVLKEEVRNMIKGSHDVPEIVDLIITLQRLNLDYHYEDEINEKLTVVYKSNYDGGNLDLVSRRFYLLRKCGYDVSSDVFLKFKDQLGNFVEADTRSLLSLYNAAFLRIHGETVLDEAISFTMRVLQDRLEHLESPLAEEVSSALDTPLFRRVGTLEMKDYIPIYEKDAKQNKSILEFAKLNFNLLQLRYSSELKECTTWWKELRVESNLSFVRDRIVEVYFWMSGGCYDPQYSHSRIILTKIVAFITILDDTLDSHATSCESMQLAEAIERWDESAVSLLPEYMKDFYMYLLKTFSSFENELGPDKSYRVFYLKEAVKELVREYTKEIKWRDEDYVPKTLKEHLKVSLISIGGTLVLCSAFVGMGDVVTKKIMKWVMSDAELVKSFGIFVRLSNDIVSTKREQREKHCVSTVQCYMKQHEITMDEACEQIKELTEDSWKFMIEQGLALKEYPIIVPRTVLEFARTVDYMYKEADKYTVSHTIKDMLTSLYVKPVLM")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT45\nATGGCTGCTCCAACATTGACTGCTGATGGTCCAAGATTGGGTCAACAAGAAATGAAAAAAATGTCTCCATCTTTCCATCCAACATTGTGGGGTGATTTTTTTTTGTCTTATGAAGCTCCAACTGAAGCTCAAGAAGCTCAAATGAGAGAAAAAGCTGCTGTTTTGAAAGAAGAAGTTAGAAATATGATCAAGGGTTCTCATGATGTTCCAGAAATTGTTGATTTGATTATCACTTTGCAGAGATTGAATTTGGATTATCATTACGAAGACGAAATCAATGAAAAGTTAACAGTTGTTTACAAGTCCAATTACGATGGTGGTAATTTGGATTTAGTTTCTAGAAGATTCTACTTGTTGAGAAAATGTGGTTATGATGTTTCTTCTGATGTTTTTTTGAAGTTCAAGGATCAATTGGGTAATTTTGTTGAAGCTGATACTAGATCTTTGTTGTCTTTGTATAACGCTGCTTTTTTGAGAATACATGGTGAAACAGTTTTGGATGAAGCTATTTCTTTTACAATGAGAGTTTTGCAAGACAGATTGGAACATTTAGAATCTCCATTAGCTGAAGAAGTTTCTTCTGCTTTAGATACTCCATTATTTAGAAGAGTTGGTACATTGGAAATGAAAGATTATATCCCAATCTACGAAAAGGATGCTAAACAAAATAAGTCTATCTTGGAATTTGCCAAATTGAATTTCAACTTGTTGCAATTGAGGTATTCTTCTGAATTGAAAGAATGTACAACCTGGTGGAAAGAATTGAGAGTTGAATCTAATTTGTCCTTTGTTAGAGATAGAATCGTTGAAGTTTACTTTTGGATGTCTGGTGGTTGTTATGATCCACAATATTCTCATTCTAGAATCATTTTGACCAAGATTGTTGCTTTTATCACTATTTTGGACGATACTTTGGATTCTCATGCTACATCTTGTGAATCTATGCAATTAGCTGAAGCTATTGAAAGATGGGATGAATCTGCTGTTTCTTTATTACCAGAATATATGAAGGACTTCTACATGTATTTGTTGAAAACTTTCTCCTCTTTCGAAAATGAATTGGGTCCAGATAAATCTTATAGAGTTTTTTACCTGAAGGAGGCTGTTAAAGAATTAGTTAGAGAATATACCAAGGAGATTAAGTGGAGAGATGAAGATTATGTTCCAAAAACTTTGAAGGAACATTTGAAAGTTTCCTTAATCTCTATCGGTGGTACTTTAGTTTTGTGTTCTGCTTTTGTTGGTATGGGTGATGTTGTTACTAAAAAAATTATGAAGTGGGTCATGTCTGATGCTGAATTGGTTAAATCTTTTGGTATTTTCGTCAGATTGTCTAATGATATTGTCTCTACAAAGAGAGAACAAAGAGAAAAACATTGTGTTTCTACAGTTCAATGTTACATGAAACAACATGAAATCACTATGGATGAAGCTTGTGAACAAATTAAAGAATTGACTGAAGACTCTTGGAAATTTATGATTGAACAAGGTTTGGCTTTGAAAGAATATCCAATTATTGTCCCAAGAACTGTTTTAGAATTTGCTAGAACAGTTGATTACATGTATAAGGAAGCTGATAAATACACTGTTTCTCATACTATTAAGGACATGTTGACTTCTTTATACGTTAAACCAGTTTTGATGTAA")

st.write("##### TIC:")
st.image('image/LT45.png')

st.write("##### Doi: [10.1074/jbc.M802682200](https://doi.org/10.1074/jbc.M802682200)")
st.write("##### Cite: K?llner, T.G., Schnee, C., Li, S., Svato?, A., Schneider, B., Gershenzon, J., and Degenhardt, J. (2008). Protonation of a Neutral (S)-β-Bisabolene Intermediate Is Involved in (S)-β-Macrocarpene Formation by the Maize Sesquiterpene Synthases TPS6 and TPS11*. Journal of Biological Chemistry 283:20779-20788.")