import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT47")
st.write("##### Former name: Spr_C15-TPS56")
st.write("##### TPS original information: Spr_C15-TPS56_(+)-(2S,3S,9R)-pristinol_12.57min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces pristinaespiralis (strain ATCC 25486 / DSM 40338 / CBS 914.69 / JCM 4507 / NBRC 13074 / NRRL 2958 / 5647)_")
st.write("##### UniProt ID or NCBI ID: [B5H7H3](https://www.uniprot.org/uniprotkb/B5H7H3/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT47\nMAHETTSGRRLPDPTSPSDPTRRTAAIRIPFPARLNPHAERARQHTLQWVQETGLLTGDEATAEYDTLRLERLMAYFYPDASAGDLELAADFNAWFFIFDDQFDGGLGTRPHEIRGVVDALVGTMTTDGAPRPADVRDTPLVRAFRDIWLRSTAGAPYAWRLRFRDHWQAYLAAHVGEAHHRNADRLPSLEQFLEVRRHSIGVQPCLDFTERCGGYALPDELYRSFPLREMREITGDVVIFVNDIVSLVKELAAGDINNSVVIEREHKGCTLEESVEHITALANARTARFARLAASLPGTLADLGVPAPSREHVSHYVDGMRHVMAGNLSWSLATSRYDETGIAAVSGGRRRPWDGLTTATGTASPRHPRRA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT47\nATGGAATTGTACGCTCAATCTGTTGGTGTTGGTGCTGCTTCTAGACCATTGGCTAATTTTCATCCATGTGTTTGGGGTGATAAATTTATTGTTTACAACCCACAATCCTGTCAAGCTGGTGAAAGAGAAGAAGCTGAAGAATTAAAAGTTGAATTGAAGAGAGAGTTGAAGGAAGCTTCTGATAATTATATGAGACAATTGAAGATGGTCGATGCTATTCAAAGATTAGGTATTGATTACTTGTTCGTTGAAGATGTTGATGAAGCTTTGAAAAATTTGTTCGAAATGTTCGATGCTTTCTGTAAAAATAACCATGATATGCATGCTACAGCTTTATCTTTTAGATTGTTAAGACAGCATGGTTATAGAGTTTCTTGTGAAGTTTTTGAAAAGTTCAAGGATGGTAAAGATGGTTTTAAAGTTCCAAATGAAGACGGTGCTGTTGCTGTTTTAGAATTTTTTGAAGCTACACATCTGAGAGTTCATGGTGAAGATGTTTTGGATAATGCTTTTGATTTCACTAGAAACTACTTGGAATCTGTTTATGCTACATTAAACGATCCAACAGCTAAACAAGTTCATAATGCTTTGAATGAATTTTCCTTCAGAAGAGGTTTACCAAGAGTTGAAGCTAGAAAATATATCTCTATCTACGAACAATACGCTTCTCATCATAAAGGTTTATTGAAATTGGCTAAGTTGGATTTTAACTTGGTTCAAGCTTTACATAGAAGAGAATTATCTGAAGATTCCAGATGGTGGAAAACATTACAAGTTCCAACTAAATTGTCCTTTGTTAGAGATAGATTGGTTGAATCTTACTTTTGGGCTTCTGGTTCTTATTTTGAACCAAATTATTCCGTTGCTAGAATGATTTTGGCTAAAGGTTTGGCTGTTTTATCTTTAATGGATGATGTTTACGACGCTTATGGTACATTTGAAGAATTGCAAATGTTCACAGATGCTATTGAAAGATGGGATGCTTCTTGTTTGGATAAATTACCAGATTATATGAAGATCGTCTACAAAGCTTTATTGGATGTTTTTGAAGAGGTTGATGAAGAATTAATCAAGTTAGGTGCTCCATATAGAGCTTATTATGGTAAAGAAGCTATGAAATACGCTGCTAGAGCTTATATGGAAGAAGCTCAATGGAGAGAACAAAAACATAAACCAACAACTAAGGAATACATGAAATTGGCTACAAAAACTTGTGGTTATATCACATTAATCATCTTGTCTTGTCTGGGTGTTGAAGAAGGTATTGTTACAAAAGAAGCTTTTGATTGGGTTTTTTCTAGACCACCATTTATTGAAGCTACTTTGATTATTGCTAGGTTGGTTAATGATATCACAGGTCATGAATTTGAAAAGAAAAGAGAACATGTCAGAACTGCTGTTGAATGTTATATGGAAGAGCATAAAGTTGGTAAACAAGAAGTTGTTTCTGAATTTTACAACCAAATGGAATCTGCTTGGAAAGATATTAATGAAGGTTTTTTGAGGCCAGTTGAATTTCCAATTCCATTGTTGTATTTGATCTTGAATAGCGTTAGAACATTGGAAGTTATTTACAAAGAGGGTGATTCTTATACACATGTTGGTCCAGCTATGCAAAATATTATTAAACAACTGTACCTGCACCCAGTTCCATATTAA")

st.write("##### TIC:")
st.image('image/LT47.png')

st.write("##### Doi: [10.1002/anie.201605425](https://doi.org/10.1002/anie.201605425)")
st.write("##### Cite: Klapschinski, T.A., Rabe, P., and Dickschat, J.S. (2016). Pristinol, a sesquiterpene alcohol with an unusual skeleton from Streptomyces pristinaespiralis. Angewandte Chemie International Edition 55:10141-10144.")