import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT49")
st.write("##### Former name: Bfu_C15-TPS60")
st.write("##### TPS original information: Bfu_C15-TPS60_Presilphiperfolan-8-尾-ol_12.085min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Botryotinia fuckeliana_")
st.write("##### UniProt ID or NCBI ID: [Q6WP50](https://www.uniprot.org/uniprotkb/Q6WP50/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT49\nMAIPALEPQLHDADTSSNNMSSNSTDSGYDTNSTTPLEKSEKPNTQELKQQQLDPKRPPFVRVPDLFGSIMSTKPVVNPNYFAAKARGDRWIARVMNFNKAVAARNSKVDLCFLASMWAPDAPEDRLVMMLDWNHWVFLFDDQFDEGHLKEDPAAAAEEVKQTIAIMGGNAPRYTAESNPIRYVFQQCWDRLKAVSSQEMQQRWIDQHKRYFDQLLVQVDQQVGGENFTRDVEAYMDLRRGTIGVYPAISLSEYGAGVNVPQHVYDHPSLQECMKVSADLVTLVNDVLSYRKDLELGVDHNLMSLLMQRDNLSAQQAVDVIGDMVNECYRRWYLALAELPSYGEKIDYNVMKFVEICRAVAQGNLYWSFQTGRYLGPEGHEVHETGIMYLPPAANLVVA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT49\nATGGCTATTCCAGCTTTAGAACCACAATTACATGATGCTGATACTTCTTCTAATAACATGTCTTCTAACTCTACAGATTCTGGTTATGATACAAATTCTACAACACCATTGGAAAAATCTGAAAAACCAAATACTCAGGAATTGAAACAACAACAATTGGATCCAAAAAGACCACCATTTGTTAGAGTTCCAGATTTATTTGGTTCTATTATGTCTACTAAGCCAGTTGTTAATCCAAATTATTTCGCTGCTAAAGCTAGAGGTGATAGATGGATTGCTAGAGTTATGAATTTTAACAAGGCTGTTGCTGCTAGAAATTCTAAAGTTGATTTATGTTTCCTGGCTTCTATGTGGGCTCCAGATGCTCCAGAAGATAGATTGGTTATGATGTTAGATTGGAATCATTGGGTTTTTTTGTTCGATGATCAATTTGATGAGGGTCATTTAAAAGAAGATCCAGCTGCTGCTGCTGAAGAAGTTAAACAAACAATTGCTATTATGGGTGGTAATGCTCCAAGATATACAGCTGAATCTAATCCAATTAGATACGTTTTTCAGCAATGTTGGGATAGATTAAAAGCTGTTTCTTCTCAAGAAATGCAACAAAGATGGATTGATCAACATAAAAGATACTTCGATCAGTTGTTAGTTCAAGTTGATCAACAAGTTGGTGGTGAAAATTTTACAAGAGATGTTGAAGCTTACATGGATTTAAGAAGAGGTACAATTGGTGTTTATCCAGCTATTTCTTTGTCTGAATATGGTGCTGGTGTTAATGTTCCACAACATGTTTATGATCATCCATCTTTACAAGAATGTATGAAAGTTTCTGCTGATTTAGTTACATTGGTTAATGATGTTCTGTCTTATAGAAAGGATTTGGAATTGGGTGTTGATCATAATTTAATGTCTTTGTTGATGCAGAGAGATAATTTGTCTGCTCAACAAGCTGTTGATGTTATTGGTGATATGGTTAATGAATGTTACAGAAGATGGTATTTGGCTTTAGCTGAATTGCCATCTTATGGTGAAAAAATTGATTACAACGTCATGAAATTCGTCGAAATTTGTAGAGCTGTTGCTCAAGGTAATTTGTATTGGTCTTTTCAAACTGGTAGATATTTGGGTCCAGAAGGTCATGAAGTTCATGAAACTGGTATTATGTATTTGCCACCAGCTGCTAATTTAGTTGTTGCTTAA")

st.write("##### TIC:")
st.image('image/LT49.png')

st.write("##### Doi: [10.1021/cb800225v](https://doi.org/10.1021/cb800225v)")
st.write("##### Cite: Pinedo, C., Wang, C.-M., Pradier, J.-M., Dalmais, B., Choquer, M., Le Pêcheur, P., Morgant, G., Collado, I.G., Cane, D.E., and Viaud, M. (2008). Sesquiterpene Synthase from the Botrydial Biosynthetic Gene Cluster of the Phytopathogen Botrytis cinerea. ACS Chemical Biology 3:791-801.")