import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT52")
st.write("##### Former name: Sbi_C15-TPS63")
st.write("##### TPS original information: Sbi_C15-TPS63_尾-Sesquiphellandrene_11.1min_Standard")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Sorghum bicolor_")
st.write("##### UniProt ID or NCBI ID: [C5YHI2](https://www.uniprot.org/uniprotkb/C5YHI2/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT52\nMALTPSVCSISDVQGLQKDRTFHPSLWGDFFLTYQPPTAPKHAYMAERAEVLKEEVRKMVKSANEIQNILDLILTLQRLGLDNHYENEINELLSFVHDSDYDDKDLNLVSLRFYLLRKHGYDVSSDVFKCFQDKEGNFVVKDTKSLLSLYNAAHLRIHGEEVLDEAIIFTRGKLESVLDSLETTLADEVTLALQTPLFRRVRILETRNYIPIYEKEVARNEVILEFAKLNFNLLQLLYCEELKMITLWWKQLNVETNLSFIRDRIVEMHFWMTGACSEKKYSLTRTITTKMTAYITILDDIMDTHSTTEEAMLLAEAIYRCEENAAELLPEYMKDFYLYLLKTFDSVKHELGPNRSFRVFYLKELLKILVRGYSQEIKWRDEHYVPETIDEHLEVSKATVGAFQVACSSFVGMGDIITKEILDWLLSYPKLLKSMTTFVRLSNDIASTKREQTGGHHASTVQCYMMQHGTTIHDACEKIKELTEDTWKDMMKLYLTPTEQPKVIIQTVLDFARTAEFMYKKTDAFTFSHTIKDTIALLFVEPTLV")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT52\nATGGCTTTGACTCCATCTGTTTGTTCTATTTCTGATGTTCAAGGTTTGCAAAAAGATAGAACTTTTCATCCATCTTTGTGGGGTGATTTTTTTTTAACTTACCAACCACCAACTGCTCCAAAACATGCTTATATGGCTGAAAGAGCTGAAGTTTTAAAAGAAGAAGTTAGAAAGATGGTCAAGTCTGCTAATGAAATTCAAAATATCCTGGATTTGATCTTGACATTACAAAGATTGGGTTTAGATAACCATTACGAAAATGAAATCAACGAATTGTTGTCTTTCGTTCATGATTCTGATTATGATGATAAGGATTTGAACTTGGTTTCTTTGAGATTTTACTTGTTGAGAAAGCATGGTTATGATGTTTCTTCTGATGTTTTTAAGTGCTTTCAAGATAAGGAAGGTAATTTTGTTGTCAAAGATACTAAGTCTCTGTTATCTTTGTACAATGCTGCTCATTTAAGAATACATGGTGAAGAAGTTTTGGATGAAGCTATTATTTTCACAAGAGGTAAATTGGAATCCGTTTTGGATTCTTTGGAAACAACATTAGCTGATGAAGTTACATTAGCTTTGCAAACTCCATTGTTTAGAAGAGTTAGAATTTTGGAAACCAGAAATTACATCCCAATTTATGAAAAGGAGGTTGCTAGAAATGAAGTTATTTTAGAATTTGCCAAGCTGAATTTCAACTTATTACAATTGCTGTACTGCGAAGAATTAAAAATGATTACTCTGTGGTGGAAACAATTGAATGTTGAAACTAATCTGTCCTTTATCAGAGATAGAATTGTTGAAATGCACTTTTGGATGACAGGTGCTTGTTCTGAAAAAAAATATTCTTTGACCAGGACAATCACAACAAAAATGACAGCTTATATCACAATCTTGGATGATATTATGGACACTCATTCTACTACTGAAGAAGCTATGTTGTTGGCTGAAGCTATTTATAGATGTGAAGAAAATGCTGCTGAATTGTTACCAGAATATATGAAAGATTTCTACCTGTATCTGTTGAAAACATTTGATTCTGTTAAGCATGAGTTGGGTCCAAATAGATCTTTTAGAGTTTTTTACCTGAAGGAATTGTTGAAGATTTTGGTTAGAGGTTATTCTCAAGAAATCAAATGGAGAGATGAACATTATGTTCCAGAAACTATTGATGAACATTTGGAAGTTTCTAAGGCTACTGTTGGTGCTTTTCAAGTTGCTTGTTCTTCTTTTGTTGGTATGGGTGATATTATTACAAAGGAAATTCTGGATTGGTTGTTATCTTATCCAAAATTGTTGAAGTCCATGACTACTTTTGTTAGATTGTCTAATGACATCGCTTCTACAAAAAGAGAACAAACAGGTGGTCATCATGCTTCTACAGTTCAATGTTATATGATGCAACATGGTACAACAATTCATGATGCTTGTGAAAAAATCAAGGAATTGACAGAAGATACTTGGAAAGATATGATGAAATTGTACTTGACTCCAACAGAACAACCAAAAGTTATTATTCAAACCGTTTTGGATTTCGCTAGAACTGCTGAATTTATGTATAAAAAGACCGATGCTTTCACATTTTCTCATACTATTAAGGATACCATCGCTTTGTTATTTGTTGAACCAACTTTGGTTTAA")

st.write("##### TIC:")
st.image('image/LT52.png')

st.write("##### Doi: [10.1111/j.1365-313X.2011.04771.x](https://doi.org/10.1111/j.1365-313X.2011.04771.x)")
st.write("##### Cite: Zhuang, X., K?llner, T.G., Zhao, N., Li, G., Jiang, Y., Zhu, L., Ma, J., Degenhardt, J., and Chen, F. (2012). Dynamic evolution of herbivore‐induced sesquiterpene biosynthesis in sorghum and related grass crops. The Plant Journal 69:70-80.")