import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT54")
st.write("##### Former name: Spr_C15-TPS65")
st.write("##### TPS original information: Spr_C15-TPS65_Selina-4(15),7(11)-diene_11.350min")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces pristinaespiralis_")
st.write("##### UniProt ID or NCBI ID: [B5HDJ6](https://www.uniprot.org/uniprotkb/B5HDJ6/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT54\nMEPELTVPPLFSPIRQAIHPKHADIDVQTAAWAETFRIGSEELRGKLVTQDIGTFSARILPEGREEVVSLLADFILWLFGVDDGHCEEGELGHRPGDLAGLLHRLIRVAQNPEAPMMQDDPLAAGLRDLRMRVDRFGTAGQTARWVDALREYFFSVVWEAAHRRAGTVPDLNDYTLMRLYDGATSVVLPMLEMGHGYELQPYERDRTAVRAVAEMASFIITWDNDIFSYHKERRGSGYYLNALRVLEQERGLTPAQALDAAISQRDRVMCLFTTVSEQLAEQGSPQLRQYLHSLRCFIRGAQDWGISSVRYTTPDDPANMPSVFTDVPTDDSTEPLDIPAVSWWWDLLAEDARSVRRQVPAQRSA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT54\nATGGAACCAGAATTAACAGTTCCACCATTGTTTTCTCCAATTAGACAAGCTATTCATCCAAAACATGCTGATATTGATGTTCAAACTGCTGCTTGGGCTGAAACATTTAGAATTGGTTCTGAAGAATTGAGAGGTAAATTGGTTACTCAAGATATTGGTACATTCTCTGCTAGAATTTTGCCAGAAGGTAGAGAAGAAGTTGTTTCTTTGTTGGCTGATTTTATTTTGTGGTTATTCGGTGTTGATGATGGTCATTGTGAAGAAGGTGAATTAGGTCATAGACCAGGTGATTTGGCTGGTTTGTTGCATAGATTAATTAGAGTTGCTCAAAACCCAGAAGCTCCAATGATGCAAGATGATCCATTAGCTGCTGGTTTGAGAGATTTAAGAATGAGAGTTGATAGATTCGGTACAGCTGGTCAAACAGCTAGATGGGTTGATGCTTTAAGAGAATATTTTTTCTCCGTTGTTTGGGAAGCTGCTCATAGAAGAGCTGGTACAGTTCCAGATTTGAATGATTATACTTTGATGAGACTGTACGATGGTGCTACTTCTGTTGTTTTACCAATGTTGGAAATGGGTCATGGTTATGAATTGCAACCATACGAAAGAGATAGAACAGCTGTTAGAGCTGTTGCTGAAATGGCTTCTTTTATTATTACATGGGATAACGATATCTTCTCTTATCATAAAGAGAGAAGAGGTTCTGGTTATTATTTAAATGCTTTGAGAGTCTTGGAGCAAGAAAGAGGTTTAACACCAGCTCAAGCTTTGGATGCTGCTATTTCTCAAAGAGATAGAGTTATGTGTTTGTTTACAACTGTTTCTGAACAATTGGCTGAACAAGGTTCTCCACAATTGAGACAATATTTGCATTCTTTAAGGTGTTTCATCAGAGGTGCTCAAGATTGGGGTATTTCTTCTGTTAGATATACTACTCCAGATGATCCAGCTAATATGCCATCTGTTTTTACTGATGTTCCAACTGATGATTCTACAGAACCATTGGATATTCCAGCTGTTTCTTGGTGGTGGGATTTGTTAGCTGAAGATGCTAGATCTGTTAGAAGACAAGTTCCAGCTCAAAGATCTGCTTAA")

st.write("##### TIC:")
st.image('image/LT54.png')

st.write("##### Doi: [10.1002/anie.201403648](https://doi.org/10.1002/anie.201403648)")
st.write("##### Cite: Baer, P., Rabe, P., Fischer, K., Citron, C.A., Klapschinski, T.A., Groll, M., and Dickschat, J.S. (2014). Induced‐fit mechanism in class I terpene cyclases. Angewandte Chemie International Edition 53:7652-7656.")