import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT55")
st.write("##### Former name: Fsp_C15-TPS66")
st.write("##### TPS original information: Fsp_C15-TPS66_Trichodiene_11.220min_Standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Fusarium sporotrichioides_")
st.write("##### UniProt ID or NCBI ID: [P13513](https://www.uniprot.org/uniprotkb/P13513/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT55\nMENFPTEYFLNTTVRLLEYIRYRDSNYTREERIENLHYAYNKAAHHFAQPRQQQLLKVDPKRLQASLQTIVGMVVYSWAKVSKECMADLSIHYTYTLVLDDSKDDPYPTMVNYFDDLQAGREQAHPWWALVNEHFPNVLRHFGPFCSLNLIRSTLDFFEGCWIEQYNFGGFPGSHDYPQFLRRMNGLGHCVGASLWPKEQFNERSLFLEITSAIAQMENWMVWVNDLMSFYKEFDDERDQISLVKNYVVSDEISLHEALEKLTQDTLHSSKQMVAVFSDKDPQVMDTIECFMHGYVTWHLCDRRYRLSEIYEKVKEEKTEDAQKFCKFYEQAANVGAVSPSEWAYPPVAQLANVRSKDVKEVQKPFLSSIELVE")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT55\nATGGAAAACTTCCCAACTGAATATTTCTTAAACACAACTGTTAGGTTGTTGGAATATATTAGATACAGAGATTCCAACTACACTAGAGAAGAAAGAATTGAAAACTTGCATTACGCTTATAACAAGGCTGCTCATCATTTTGCTCAACCAAGACAACAACAATTGTTGAAAGTTGATCCAAAAAGATTGCAAGCTTCTTTGCAAACTATTGTTGGTATGGTTGTTTATTCTTGGGCTAAAGTTTCTAAAGAATGTATGGCTGATTTGTCTATTCATTATACTTACACTCTGGTTTTGGATGATTCTAAAGATGATCCATATCCAACTATGGTTAATTATTTCGATGACTTGCAAGCTGGTAGAGAACAAGCTCATCCATGGTGGGCTTTAGTTAATGAACATTTTCCAAATGTCCTGAGACATTTTGGTCCATTTTGTTCTTTGAATTTGATCAGATCTACCTTAGATTTCTTCGAAGGTTGTTGGATTGAACAATATAATTTCGGTGGTTTTCCAGGTTCTCATGATTATCCACAATTTTTAAGAAGGATGAACGGTTTGGGTCATTGTGTTGGTGCTTCTTTGTGGCCAAAAGAACAATTTAATGAAAGATCTCTGTTCTTGGAAATCACTTCTGCTATTGCTCAAATGGAAAATTGGATGGTTTGGGTTAATGATTTGATGTCTTTTTACAAGGAGTTCGATGATGAAAGAGATCAAATTTCTTTGGTTAAGAACTACGTTGTTTCTGATGAAATTTCTTTGCATGAAGCTTTAGAAAAGTTGACTCAAGATACTTTACACTCTTCTAAACAAATGGTTGCTGTTTTTTCTGATAAGGATCCACAAGTTATGGATACAATTGAATGTTTTATGCACGGTTATGTTACTTGGCATTTATGTGATAGAAGATATAGATTGTCCGAAATTTACGAAAAGGTTAAAGAAGAAAAGACCGAAGATGCTCAAAAATTTTGTAAATTCTACGAGCAAGCTGCTAATGTTGGTGCTGTTTCTCCATCTGAATGGGCTTATCCACCAGTTGCTCAATTGGCTAATGTTAGATCTAAAGATGTTAAGGAAGTCCAAAAACCATTTTTATCTTCTATCGAACTGGTTGAATAA")

st.write("##### TIC:")
st.image('image/LT55.png')

st.write("##### Doi: [10.1016/j.abb.2007.10.015](https://doi.org/10.1016/j.abb.2007.10.015)")
st.write("##### Cite: Vedula, L.S., Jiang, J., Zakharian, T., Cane, D.E., and Christianson, D.W. (2008). Structural and mechanistic analysis of trichodiene synthase using site-directed mutagenesis: Probing the catalytic function of tyrosine-295 and the asparagine-225/serine-229/glutamate-233–Mg2+B motif. Archives of Biochemistry and Biophysics 469:184-194.")