import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT56")
st.write("##### Former name: Vof_C15-TPS69")
st.write("##### TPS original information: Vof_C15-TPS69_Valerena-4,7(11)-diene_10.230min_NMR")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Valeriana officinalis_")
st.write("##### UniProt ID or NCBI ID: [J9R5V4](https://www.uniprot.org/uniprotkb/J9R5V4/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT56\nMESCLSFSSPPPTKKNIQEPVRPNAKFHKSVWGNHFLKYASNPEQIDYDADEQHEQLKEELRKKLVVNVTNERVEEQLKLIDAIQRLGVAYHFQREIDAVLNNLLLFRSNKDSDDIYMVSLRFRLLRQQGHNVSCSVFEKFKNIDGRFKDSLRDDVRGLLSLYEATHMRVHKEDILEEALEFTIYELEQVVKLSSNDTLLASEVIHALNMPIRKGLTRIEARHFISVYQHDKSHDETLLKFSKIDFNMLQKLHQRELADLTIWWEKLNVAEKMPYARDRFVECYFWGLGVYFEPQYSRARKMFVKVINLTSLIDDTYDSYGTFDELDLFTDAVKRWNVNETDKLPEYMRPLFMELLNVYNAMEEELKEEGVSYRVEYAKQSMIQIVTAYNDEAIWYHNGYVPTFDEYLKVALISCGYMLLSTISFVGMGVTTVTKPAFDWVTNNPLILIASCTINRLADDKVGHELEQERGHVASGVECYMKHNNATKQEVVIEFNKRISNAWKDINQECLHPLPVPLHLVVRPLYLACFMNVFYKDEDWYTHSNTQMKECINSLLVESVPY")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT56\nATGGAATCTTGTTTGTCTTTCTCTTCTCCACCACCAACAAAAAAAAATATTCAAGAACCAGTCAGGCCAAATGCTAAATTTCATAAATCTGTTTGGGGTAATCACTTTTTGAAATATGCTTCTAACCCAGAACAAATTGATTATGATGCTGATGAACAACATGAACAATTAAAAGAAGAGTTGAGAAAGAAGTTGGTTGTTAATGTTACTAACGAAAGAGTTGAAGAACAATTAAAGTTGATCGATGCTATTCAAAGATTGGGTGTTGCTTATCATTTTCAAAGAGAAATTGACGCTGTTTTGAATAATTTGTTGTTGTTTAGGTCCAACAAGGATTCTGATGATATTTATATGGTCTCTTTGAGATTCAGATTGTTAAGACAACAAGGTCATAATGTTTCTTGTTCTGTTTTTGAAAAGTTCAAGAACATCGATGGTAGATTTAAAGATTCTTTGAGAGATGATGTCAGAGGTTTGTTATCTTTGTATGAAGCTACACACATGAGAGTTCATAAAGAAGATATTTTGGAGGAAGCTTTGGAATTTACAATTTATGAACTGGAACAGGTTGTTAAATTGTCTTCTAATGATACTCTGTTGGCTTCTGAAGTTATTCATGCTTTGAATATGCCAATTAGAAAGGGTTTAACAAGAATTGAAGCTAGACATTTTATCTCTGTTTACCAACATGATAAGTCTCATGATGAAACTTTATTGAAGTTCTCTAAGATCGATTTCAACATGTTACAAAAGTTGCATCAAAGAGAATTGGCTGATTTAACTATTTGGTGGGAAAAATTGAACGTTGCTGAAAAAATGCCATACGCTAGAGATAGATTTGTTGAATGTTATTTCTGGGGTTTAGGTGTTTATTTTGAACCACAATATTCCAGAGCTAGAAAAATGTTTGTTAAGGTTATCAACCTGACATCTTTAATTGATGATACTTACGATTCCTACGGTACATTTGATGAATTAGATTTGTTCACAGACGCTGTTAAAAGATGGAATGTTAATGAAACTGACAAGTTGCCAGAATATATGAGACCATTATTTATGGAACTGTTGAATGTTTACAACGCTATGGAAGAAGAATTAAAAGAAGAAGGTGTTTCTTACAGAGTTGAATATGCTAAACAATCTATGATCCAAATCGTTACTGCTTATAATGATGAAGCTATTTGGTATCATAACGGTTATGTTCCAACTTTTGATGAATATTTGAAGGTTGCTTTGATCTCTTGTGGTTATATGTTATTATCCACTATCTCTTTCGTCGGTATGGGTGTTACAACAGTTACAAAACCAGCTTTTGATTGGGTTACTAATAATCCATTAATCTTGATCGCTTCTTGTACTATTAACAGATTAGCTGATGATAAGGTTGGTCATGAATTAGAACAAGAAAGAGGTCATGTTGCTTCTGGTGTTGAATGTTACATGAAACATAATAACGCTACTAAGCAAGAAGTTGTTATTGAATTTAACAAGAGGATCTCTAACGCTTGGAAAGATATTAATCAAGAATGTTTGCACCCATTACCAGTTCCATTACATTTGGTTGTTAGACCATTATATCTGGCTTGTTTTATGAATGTTTTCTACAAAGACGAGGATTGGTATACTCATTCTAATACACAAATGAAGGAGTGTATTAACTCTTTGTTGGTTGAATCTGTTCCATATTAA")

st.write("##### TIC:")
st.image('image/LT56.png')

st.write("##### Doi: [10.1111/j.1742-4658.2012.08692.x](https://doi.org/10.1111/j.1742-4658.2012.08692.x)")
st.write("##### Cite: Pyle, B.W., Tran, H.T., Pickel, B., Haslam, T.M., Gao, Z., MacNevin, G., Vederas, J.C., Kim, S.U., and Ro, D.K. (2012). Enzymatic synthesis of valerena‐4, 7 (11)‐diene by a unique sesquiterpene synthase from the valerian plant (Valeriana officinalis). The FEBS Journal 279:3136-3146.")