import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT57")
st.write("##### Former name: Sbi_C15-TPS70")
st.write("##### TPS original information: Sbi_C15-TPS70_Zingiberene_10.725min_Standard; Sbi_C15-TPS70_尾-sesquiphellandrene_11.105min")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Sorghum bicolor_")
st.write("##### UniProt ID or NCBI ID: [C5YHH7](https://www.uniprot.org/uniprotkb/C5YHH7/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT57\nMAALQYNCDAGLAKAPTFHPSLWGDFFLTYQPPTAPQHVYMKERAELLKEEVREIVKGTNELPKLLDLIITLQRLGLDNHYEIEIDEHLHFIYNSSCDVKDLNLVSLRFYLLRKNGYDVSSDVFLNFKDKDGNFASDDIRSLLSLYNAAYLRTHGEEVLDEAIIFTRRHLEAALTSLESKLADEVSLSLQTPLFRRVRILETRNYIPIYEMEPSRNEAMLEFAKLNFNLLQILYCEELKTVTAWWKQLNIETDLSFIRDRIVEMHFWMAGACSEPKYSLSRVILTKMTAFITILDDIIDTHSTTEEGKLLAKAIDRCSQDANEVLPDYMKHFYMFLLKTFDSCEDELGPNKRYRVFYLKEMLKILVRGYSQEIEWRDEHYVPETIDKHLEISRVTVGAFQLACSSFVGMGDIITKEVLDWLLTYPELLKCFTTFVRLSNDITSTEREQTGGHHASTVQCYMLQHSTTMHDACEKIKGLIEDSWKDMMQLYLTPTEQSKVVAQTVVDFARTGDYMYKKTDAFTFSHTIKDMIALLYVEPILF")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT57\nATGGCTGCTTTACAATATAACTGTGATGCTGGTTTGGCTAAAGCTCCAACATTTCATCCATCTTTATGGGGTGATTTTTTTTTAACATACCAGCCACCAACTGCTCCACAACATGTTTATATGAAAGAAAGAGCTGAATTGTTGAAGGAAGAAGTTAGAGAAATTGTTAAGGGTACTAATGAATTGCCAAAATTATTGGATCTGATCATTACATTGCAGAGATTGGGTTTGGATAATCATTATGAAATCGAAATCGACGAACATTTACATTTTATCTACAACTCTTCCTGTGATGTTAAAGATTTAAACTTGGTTTCCTTGAGATTCTATTTGTTGAGAAAAAACGGTTACGATGTTTCTTCTGATGTTTTTTTGAACTTCAAGGATAAGGATGGTAATTTTGCTTCTGATGATATTAGATCTCTGTTATCTTTGTACAACGCTGCTTATTTGAGAACTCATGGTGAAGAAGTTTTAGATGAAGCTATTATTTTCACCAGAAGACATTTAGAAGCTGCTTTGACATCTTTAGAATCTAAATTAGCTGACGAAGTTTCTTTATCTTTGCAAACTCCATTATTCAGAAGAGTTAGAATTTTGGAAACCAGAAATTACATCCCAATTTATGAAATGGAGCCATCTAGAAATGAAGCTATGTTGGAATTTGCTAAATTGAATTTCAACCTGTTGCAAATTCTGTATTGTGAAGAATTGAAGACAGTTACTGCTTGGTGGAAACAATTGAATATTGAAACAGATCTGTCCTTTATCAGAGATAGAATTGTTGAAATGCACTTTTGGATGGCTGGTGCTTGTTCTGAACCAAAATATTCTTTATCTAGGGTTATCTTGACCAAAATGACAGCTTTTATTACTATCTTGGACGATATTATCGACACACATTCTACAACAGAAGAAGGTAAATTATTGGCTAAAGCAATTGATAGATGCTCTCAAGATGCTAATGAAGTTTTACCAGATTATATGAAGCACTTTTACATGTTTCTGTTGAAAACATTCGACTCTTGTGAAGATGAATTAGGTCCAAATAAAAGATACAGAGTTTTCTATCTGAAGGAAATGTTAAAGATCTTGGTTAGAGGTTATTCTCAAGAAATTGAATGGAGAGATGAACATTATGTTCCAGAAACTATTGATAAGCATTTGGAAATTTCCAGAGTTACAGTTGGTGCTTTTCAATTGGCTTGTTCTTCTTTTGTTGGTATGGGTGATATTATTACAAAGGAAGTTTTGGATTGGTTGTTAACTTATCCAGAATTATTGAAGTGCTTCACAACATTTGTTAGATTGTCTAATGACATCACTTCTACTGAAAGAGAACAAACAGGTGGTCATCATGCTTCTACTGTTCAATGTTATATGTTACAACACTCTACTACTATGCATGATGCTTGTGAAAAAATTAAGGGTTTGATTGAAGACTCTTGGAAAGATATGATGCAATTGTATTTGACACCAACTGAACAATCTAAAGTTGTTGCTCAAACTGTTGTTGATTTTGCTAGAACTGGTGATTATATGTATAAGAAAACCGATGCTTTCACTTTTTCTCATACAATTAAGGATATGATCGCTTTGTTGTATGTTGAACCAATTTTATTCTAA")

st.write("##### TIC:")
st.image('image/LT57.png')

st.write("##### Doi: [10.1111/j.1365-313X.2011.04771.x](https://doi.org/10.1111/j.1365-313X.2011.04771.x)")
st.write("##### Cite: Zhuang, X., K?llner, T.G., Zhao, N., Li, G., Jiang, Y., Zhu, L., Ma, J., Degenhardt, J., and Chen, F. (2012). Dynamic evolution of herbivore‐induced sesquiterpene biosynthesis in sorghum and related grass crops. The Plant Journal 69:70-80.")