import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT59")
st.write("##### Former name: Egl_EgVS")
st.write("##### TPS original information: Egl_EgVS_(+)-Valencene_10.805min_NMR")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Eryngium glaciale_")
st.write("##### UniProt ID or NCBI ID: [(Ye, Huang et al. 2022)](https://doi.org/10.1016/j.ymben.2022.03.005)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT59\nMSLNVLSTSGSAPTTKSSEITRRSANYHPSLWGDKFLEYSSPDHLKNDSFTEKKHEQLKEEVKKMLVETVQKPQQQLNLINEIQRLGLSYLFEPEIEAALQEISVTYDEFCCSTDADDLHNVALSFRILREHGHNVSSDVFQKFMDSNGKLKDYLVNDARGLLSLYEATHFRVHNEDKLEELLSVTTSRLEHLKSRVKYPLEDEISRALKHPLHKELNRLGARYYISIYEKFDSHNKLLLEFAKLDFNRLQKMYQHELAHLTRWWKDLDFTNKLPFARDRIVEGYFWILGMYFEPERKDVREFLNKVFALITVVDDTYDVYGTFEELLLFTDAIEKWGTSDLDQLPGYMRIIYQALMDVYNQMEEKLSMKADCPTYRLEFAIETVKAMFRSYLEEARWSKEHYIPSMEEYMTVALVSVGYKTILTNSFVGMGDIATREVFEWVFNSPLIIRASDLIARLGDDIGGHEEEQKKGDAATAIECYIKENHVTKHEAYDEFQKQIDNAWKDLNKEALRPFPVPMTFITRVVHFTRAVHVIYADFSDGYTRSDKAIRGYITSLLVDPIPL")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT59\nATGTCATTGAATGTTTTATCTACATCAGGTTCTGCTCCAACTACAAAGTCTTCAGAAATCACTAGAAGATCAGCAAACTACCATCCATCTTTATGGGGTGACAAATTTTTGGAATACTCTTCACCAGATCATTTGAAAAATGATTCTTTTACAGAAAAGAAACATGAACAATTAAAAGAAGAAGTTAAGAAAATGTTGGTTGAAACTGTTCAAAAGCCACAACAACAATTGAATTTGATTAATGAAATCCAAAGATTGGGTTTGTCATACTTATTCGAACCAGAAATCGAAGCTGCATTGCAAGAAATCTCAGTTACTTACGATGAATTCTGTTGTTCTACAGATGCTGATGATTTGCATAACGTTGCATTGTCTTTTAGAATCTTGAGAGAACATGGTCATAATGTTTCTTCAGATGTTTTTCAAAAGTTTATGGATTCAAACGGTAAATTGAAGGATTATTTGGTTAATGATGCTAGAGGTTTGTTATCTTTGTACGAAGCAACACATTTTAGAGTTCATAACGAaGATAAGTTGGAAGAATTGTTGTCAGTTACTACATCTAGATTGGAACATTTGAAGTCACGTGTTAAGTACCCATTGGAAGATGAAATCTCTAGAGCTTTGAAGCATCCATTGCATAAGGAATTGAACAGATTGGGTGCAAGATACTACATCTCAATCTATGAAAAGTTTGATTCTCATAATAAGTTGTTATTGGAATTTGCTAAATTAGATTTTAATAGATTGCAAAAGATGTATCAACATGAATTGGCACATTTGACAAGATGGTGGAAGGATTTGGATTTCACTAATAAGTTGCCATTTGCTAGAGATAGAATCGTTGAAGGTTACTTCTGGATCTTGGGCATGTACTTCGAACCAGAAAGAAAGGATGTTAGAGAATTCTTGAACAAAGTTTTCGCTTTGATCACTGTTGTTGATGATACATACGATGTTTACGGTACTTTTgAAGAATTGTTGTTGTTTACTGATGCAATTGAAAaATGGGGTACTTCTGATTTGGATCAATTGCCAGGTTACATGAGAATCATCTATCAAGCTTTGATGGATGTTTACAACCAAATGGAAGAAAAGTTGTCAATGAAAGCAGATTGTCCAACATACAGATTGGAATTCGCTATCGAAACTGTTAAGGCAATGTTCAGATCTTATTTGGAAGAAGCTAGATGGTCAAAGGAACATTACATCCCATCTATGGAAGAATACATGACAGTTGCATTAGTTTCAGTTGGTTACAAGACTATCTTGACAAACTCTTTCGTTGGTATGGGTGACATTGCTACTAGAGAAGTTTTCGAATGGGTTTTTAATTCACCATTAATCATCAGAGCTTCTGATTTGATTGCAAGATTAGGTGACGATATTGGTGGTCATGAAGAAGAACAAAAGAAAGGTGACGCTGCAACAGCTATCGAATGTTACATCAAGGAAAACCATGTTACTAAGCATGAAGCATACGATGAATTCCAAAAGCAAATCGATAATGCTTGGAAAGATTTGAATAAGGAAGCATTGcGACCATTTCCAGTTCCAATGACTTTTATTACAAGAGTTGTTCATTTCACTAGAGCTGTTCATGTTATCTATGCAGATTTCTCAGATGGTTACACAAGATCTGATAAGGCTATCAGAGGTTACATCACTTCTTTGTTGGTTGATCCAATTCCATTATAA")

st.write("##### TIC:")
st.image('image/LT59.png')

st.write("##### Doi: [10.1016/j.ymben.2022.03.005](https://doi.org/10.1016/j.ymben.2022.03.005)")
st.write("##### Cite: Ye, Z., Huang, Y., Shi, B., Xiang, Z., Tian, Z., Huang, M., Wu, L., Deng, Z., Shen, K., and Liu, T. (2022). Coupling cell growth and biochemical pathway induction in Saccharomyces cerevisiae for production of (+)-valencene and its chemical conversion to (+)-nootkatone. Metabolic Engineering 72:107-115.")