import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT61")
st.write("##### Former name: Sco_5222")
st.write("##### TPS original information: Sco_5222_Epi-Isozizaene_10.25min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces coelicolor (strain ATCC BAA-471 / A3(2) / M145)_")
st.write("##### UniProt ID or NCBI ID: [WP_011030119.1](https://www.ncbi.nlm.nih.gov/protein/WP_011030119.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT61\nMHAFPHGTTATPTAIAVPPSLRLPVIEAAFPRQLHPYWPKLQETTRTWLLEKRLMPADKVEEYADGLCYTDLMAGYYLGAPDEVLQAIADYSAWFFVWDDRHDRDIVHGRAGAWRRLRGLLHTALDSPGDHLHHEDTLVAGFADSVRRLYAFLPATWNARFARHFHTVIEAYDREFHNRTRGIVPGVEEYLELRRLTFAHWIWTDLLEPSSGCELPDAVRKHPAYRRAALLSQEFAAWYNDLCSLPKEIAGDEVHNLGISLITHHSLTLEEAIGEVRRRVEECITEFLAVERDALRFADELADGTVRGKELSGAVRANVGNMRNWFSSVYWFHHESGRYMVDSWDDRSTPPYVNNEAAGEK")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT61\nATGCATGCATTTCCACATGGTACTACAGCTACTCCAACAGCTATTGCAGTTCCACCATCTTTGAGATTACCAGTTATTGAAGCTGCATTTCCAAGACAATTGCATCCATATTGGCCAAAGTTGCAAGAAACTACAAGAACTTGGTTGTTAGAAAAGAGATTGATGCCAGCAGATAAAGTTGAAGAATATGCTGATGGTTTGTGTTACACAGATTTGATGGCAGGTTATTACTTGGGTGCTCCAGATGAAGTTTTACAAGCTATTGCAGATTACTCAGCTTGGTTTTTCGTTTGGGATGATAGACATGATAGAGATATTGTTCATGGTAGAGCTGGTGCATGGAGAAGATTGAGAGGTTTGTTACATACTGCTTTAGATTCTCCAGGTGACCATTTGCATCATGAAGATACATTAGTTGCTGGTTTTGCAGACTCAGTTAGAAGATTGTACGCATTTTTGCCAGCAACTTGGAATGCTAGATTCGCAAGACATTTCCATACAGTTATTGAAGCATACGATAGAGAATTCCATAACAGAACTAGAGGTATCGTTCCAGGTGTTGAAGAATACTTGGAATTGAGAAGATTGACTTTTGCTCATTGGATTTGGACAGATTTGTTAGAACCATCTTCAGGTTGTGAATTACCAGATGCAGTTAGAAAACATCCAGCTTATAGAAGAGCTGCATTGTTATCTCAAGAATTTGCTGCATGGTACAACGATTTGTGTTCATTGCCAAAGGAAATCGCTGGTGACGAAGTTCATAATTTGGGTATCTCTTTGATCACTCATCATTCATTGACATTAGAAGAAGCAATTGGTGAAGTTAGAAGAAGAGTTGAAGAATGTATCACTGAATTCTTGGCTGTTGAAAGAGATGCTTTGAGATTTGCAGATGAATTAGCTGATGGTACAGTTAGAGGTAAAGAATTATCTGGTGCTGTTAGAGCAAACGTTGGTAACATGAGAAACTGGTTCTCTTCAGTTTACTGGTTCCATCATGAATCAGGTAGATACATGGTTGATTCTTGGGATGATAGATCAACACCACCATACGTTAATAATGAAGCTGCAGGTGAAAAATAA")

st.write("##### TIC:")
st.image('image/LT61.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")