import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT63")
st.write("##### Former name: Fgr_FgFS")
st.write("##### TPS original information: Fgr_FgFS_(-)-acoradinene_9.78min_NMR; Fgr_FgFS_Fusariumdiene_10.005min_NMR; Fgr_FgFS_Fusagramineol_11.525min_NMR; Fgr_FgFS_epi-fusagramineol_11.885min_NMR; Fgr_FgFS_(-)-伪-Acorenol_12.50min_NMR; Fgr_FgFS_(+)-伪-bisabolol_13.005min_NMR; Fgr_FgFS_trans-nerolidol_11.485min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Fusarium graminearum_")
st.write("##### UniProt ID or NCBI ID: [XP_011322218.1](https://www.ncbi.nlm.nih.gov/protein/XP_011322218.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT63\nMPHKHVPLRPVKLTFDPVGSNTLGVPTLDFESLFREDSVSEDAPLVIYPEDMGVPWNTSLPWTRQSKFWAYAEAAGYEMANGISLDKASERGTLPMELMDERRKWKIDELVEDAISCCAYLYPTSSPTRLALLTQSVLLLFLHDDVIERGATQNETTVVDEFLSMAPKNRHLKKFWSDVLECDPVLGPDLLYAIHAFVRDGRVKSPFKQDHYATLADYMLYRRNDVGKTFMIAAIRFGSGVQQTREELAPFDELADLYVRHSILINDLYSYDKEVHEVKTIDASIVNAVAVTEQLLSVSPDLAKNLTRAITFDMEKEFYGICEKFMHSPDINDRQRVFVTALFDALTGNIFHSATLSRYVRHGERPLPCKC")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT63\nATGCCTCACAAGCACGTTCCTCTTAGACCAGTCAAGTTGACATTTGATCCTGTAGGATCAAACACCCTAGGTGTGCCAACCTTGGACTTTGAGTCTCTGTTCCGGGAAGACAGCGTCTCTGAGGATGCCCCTCTTGTTATCTACCCAGAGGATATGGGTGTCCCATGGAACACCTCTCTTCCTTGGACCAGACAATCCAAGTTCTGGGCTTACGCCGAGGCAGCTGGATATGAAATGGCCAACGGAATCAGCCTTGACAAGGCATCAGAGCGTGGCACACTACCCATGGAGTTGATGGATGAGCGTCGCAAGTGGAAGATTGATGAGCTAGTTGAGGATGCCATCTCTTGCTGTGCTTATCTTTACCCTACATCATCTCCTACCAGATTGGCGTTGTTGACCCAGTCTGTTCTGCTTCTATTCCTCCACGACGATGTTATTGAGCGAGGAGCTACTCAAAACGAAACCACAGTGGTAGACGAATTTCTTAGCATGGCTCCCAAGAACAGGCATCTTAAGAAATTCTGGTCAGACGTATTGGAATGTGATCCCGTCCTTGGACCTGATCTGCTTTATGCTATCCATGCTTTCGTCCGTGATGGTCGTGTAAAGTCACCCTTTAAGCAGGATCACTATGCCACATTGGCTGATTACATGCTTTACCGTCGCAATGATGTTGGCAAGACATTTATGATTGCAGCTATCCGCTTCGGCTCTGGCGTGCAACAAACACGCGAAGAACTTGCTCCCTTTGACGAGCTTGCTGATCTTTACGTCAGACACTCAATTCTTATCAACGATCTCTACTCGTATGATAAGGAGGTGCACGAGGTCAAGACTATCGACGCGTCCATCGTGAACGCAGTTGCTGTCACAGAGCAGCTCCTTTCCGTGTCGCCTGACCTGGCCAAGAACTTAACCAGAGCTATTACCTTTGACATGGAGAAGGAGTTTTACGGCATTTGTGAGAAGTTTATGCACAGCCCTGATATCAACGATCGCCAGCGCGTGTTCGTTACTGCGCTCTTTGATGCGTTGACAGGCAATATCTTCCATTCTGCTACTTTGAGCAGATACGTTCG TCACGGCGAGAGACCACTTCCTTGCAAGTGTTAG")

st.write("##### TIC:")
st.image('image/LT63.png')

st.write("##### Doi: [10.1021/acs.orglett.8b00366](https://doi.org/10.1021/acs.orglett.8b00366)")
st.write("##### Cite: Bian, G., Hou, A., Yuan, Y., Hu, B., Cheng, S., Ye, Z., Di, Y., Deng, Z., and Liu, T. (2018). Metabolic Engineering-Based Rapid Characterization of a Sesquiterpene Cyclase and the Skeletons of Fusariumdiene and Fusagramineol from Fusarium graminearum. Organic Letters 20:1626-1629.")