import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT64")
st.write("##### Former name: Aae_C15-TPS73")
st.write("##### TPS original information: Aae_C15-TPS73_未-Cubenol_12.595min_standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Agrocybe aegerita_")
st.write("##### UniProt ID or NCBI ID: [A0A5Q0QU70](https://www.uniprot.org/uniprotkb/A0A5Q0QU70/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT64\nMNASPFLNESSPTRPTSFVLPDLVSHCKFPLSYHPNGDEIAQESVDWLDSSCPDLTAKQRRALRVLQSGELTAYCYNQATSPERLRVVSDFLTYLFHLDNISDGMMTRETDVLADVVMNAFWFTDKYMPTRGPGKEQLDEELNPGKLARDFWSRAIADCGVGVQARFKETMGLFFEAVNIQARMRDEDTIPDLESYIDVRRDTSGCKPSWVLIEYALGIDLPDHVVDHPIMQALNQGTNDLVTWSNDIFSYNVEQSRGDTHNMIVILMEYHGHTLQSAVDYVGELCAQTIDTFCENKERLPSWGPEIDDMVARYVKGLQDWIVGSLHWSFQTQRYFGKDGLDIKKHRFVKLLPLEAAK")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT64\nATGAACGCTTCCCCATTTTTGAACGAATCCTCCCCAACAAGACCAACATCCTTCGTTTTGCCAGATTTGGTTTCCCATTGTAAGTTTCCATTGTCCTACCATCCAAACGGTGATGAAATTGCTCAAGAATCTGTTGATTGGTTAGATTCTTCCTGTCCAGATTTGACTGCTAAGCAAAGAAGAGCTTTAAGAGTTTTGCAATCTGGTGAATTGACTGCTTATTGTTATAATCAAGCTACTTCTCCAGAAAGATTGAGAGTTGTTTCTGATTTTTTGACTTACTTGTTCCATTTGGATAACATTTCTGATGGTATGATGACTAGAGAAACTGATGTTTTGGCTGATGTTGTTATGAACGCTTTTTGGTTTACTGATAAGTATATGCCAACTAGAGGTCCTGGTAAAGAACAATTGGATGAAGAATTGAATCCAGGTAAGTTGGCTAGAGATTTTTGGTCTAGAGCTATTGCTGATTGTGGTGTTGGTGTTCAAGCTAGATTTAAAGAAACTATGGGTTTGTTCTTCGAAGCTGTTAATATTCAAGCTAGAATGAGAGATGAAGATACTATTCCTGATTTGGAATCTTATATTGATGTTAGAAGAGATACCTCTGGTTGTAAACCATCCTGGGTTTTGATTGAATATGCTTTGGGTATTGATTTGCCAGATCATGTTGTTGATCATCCAATTATGCAAGCTCTAAATCAAGGTACTAATGATTTGGTTACTTGGTCTAATGATATTTTCTCTTACAACGTTGAACAATCTAGAGGTGATACTCATAATATGATTGTTATTTTGATGGAATACCACGGTCATACTTTACAATCTGCAGTTGATTATGTTGGTGAATTGTGTGCTCAAACCATTGATACTTTTTGTGAAAATAAGGAAAGATTGCCTTCTTGGGGTCCAGAAATTGATGATATGGTTGCTAGATATGTTAAGGGTTTGCAAGATTGGATTGTTGGTTCTTTGCATTGGTCTTTTCAAACTCAAAGATATTTCGGTAAGGATGGTTTGGATATTAAGAAGCATAGATTTGTTAAGTTGTTGCCATTGGAAGCTGCTAAA")

st.write("##### TIC:")
st.image('image/LT64.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")