import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT68")
st.write("##### Former name: Sex_PentS")
st.write("##### TPS original information: Sex_PentS_Pentalenene_8.825min_Standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces exfoliatus_")
st.write("##### UniProt ID or NCBI ID: [Q55012](https://www.uniprot.org/uniprotkb/Q55012/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT68\nMPQDVDFHIPLPGRQSPDHARAEAEQLAWPRSLGLIRSDAAAERHLRGGYADLASRFYPHATGADLDLGVDLMSWFFLFDDLFDGPRGENPEDTKQLTDQVAAALDGPLPDTAPPIAHGFADIWRRTCEGMTPAWCARSARHWRNYFDGYVDEAESRFWNAPCDSAAQYLAMRRHTIGVQPTVDLAERAGRFEVPHRVFDSAVMSAMLQIAVDVNLLLNDIASLEKEEARGEQNNMVMILRREHGWSKSRSVSHMQNEVRARLEQYLLLESCLPKVGEIYQLDTAEREALERYRTDAVRTVIRGSYDWHRSSGRYDAEFALAAGAQGYLEELGSSAH")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT68\nATGCCACAAGATGTTGATTTTCATATTCCATTGCCAGGTAGACAATCTCCAGATCATGCTAGAGCAGAAGCTGAACAATTAGCTTGGCCAAGATCTTTGGGTTTAATTAGATCAGATGCTGCAGCTGAAAGACATTTGAGAGGTGGTTATGCAGATTTGGCTTCTAGATTTTACCCACATGCAACTGGTGCTGATTTGGATTTGGGTGTTGATTTGATGTCATGGTTTTTCTTGTTCGATGATTTGTTCGATGGTCCAAGAGGTGAAAATCCAGAAGATACTAAACAATTGACAGATCAAGTTGCAGCTGCATTGGATGGTCCATTACCAGATACAGCTCCACCAATTGCACATGGTTTTGCTGATATTTGGAGAAGAACTTGTGAGGGTATGACACCAGCATGGTGTGCTAGATCTGCAAGACATTGGAGAAACTACTTCGATGGTTACGTTGATGAAGCAGAATCTAGATTTTGGAATGCTCCATGTGATTCAGCTGCACAATATTTGGCTATGAGAAGACATACTATTGGTGTTCAACCAACAGTTGATTTGGCTGAAAGAGCAGGTAGATTTGAAGTTCCACATAGAGTTTTTGATTCTGCAGTTATGTCAGCTATGTTGCAAATCGCTGTTGATGTTAATTTGTTGTTGAACGATATCGCATCATTGGAAAAGGAAGAAGCTAGAGGTGAACAAAACAACATGGTTATGATCTTGAGAAGAGAACATGGTTGGTCTAAGTCAAGATCTGTTTCACATATGCAAAATGAAGTTAGAGCAAGATTGGAACAATATTTGTTGTTGGAATCTTGTTTGCCAAAGGTTGGTGAAATCTATCAATTGGATACTGCAGAAAGAGAAGCTTTAGAAAGATACAGAACTGATGCTGTTAGAACAGTTATTAGAGGTTCATACGATTGGCATAGATCTTCAGGTAGATACGATGCTGAATTTGCATTAGCTGCAGGTGCACAAGGTTACTTGGAAGAATTAGGTTCTTCAGCTCATTAA")

st.write("##### TIC:")
st.image('image/LT68.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")