import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT69")
st.write("##### Former name: OsaTPS02")
st.write("##### TPS original information: OsaTPS02_尾-caryophyllene_9.895min_Standard")
st.write("##### TPS type: TPS-a")

st.write("##### Species: _Ocimum sanctum L._")
st.write("##### UniProt ID or NCBI ID: [(Deng, Shi et al. 2022)](https://doi.org/10.1016/j.ymben.2021.11.005)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT69\nMAASNSNSNSRPSVTYHPNVWGDYFLSYASELTEISRAEREEHEKQKERVRNLLVQTRDDSSFKLQLIDSIQRLGVGYHFEKEIEKSLRYIYTTYYDTKDNDDLHIIALRFRLMRQQGFHVPCDVFKRFIDEEGNFKEWIKDDVEGILSLYEASHYGMHGEEILDKALEFCSSRLGQGMEDSLSVRTPISKTITRFGAKKFISGYQDISQLHHQPLLKFAISDFNMLQKVHQRELSQLTRWWKELDFGNKLPFARDRLVECYFWIVGVYFEEGYAVARRLLTKVIYLASVLDDIYDVYGTLEELTIFTAVVQRWDINGMDKLPPYMRIYYKALLDVYFEMEYEMGKIGKSYTVEYAKQEMKRLAEVYFEEAKWSFNKYKPRMEEYMNVALLSSGYMMMAVNALAVIPHHISQEEFHWVLSEPSLLRASLTITRLMDDIAGYGSEEKLSAVHYYMSENGVSETEALVELGKQVKNAWKDLNKELVEPRASSNPILRCVVNFTRVIVVLYADGDAYGNSKTKTKELIKSILVDPIII")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT69\nATGGCTGCATCTAATTCAAATTCTAATTCAAGACCATCTGTTACTTATCATCCAAATGTTTGGGGTGACTACTTTTTGTCTTACGCTTCAGAATTAACAGAAATTTCAAGAGCAGAAAGAGAAGAACATGAAAAGCAAAAGGAAAGAGTTAGAAATTTGTTGGTTCAAACTAGAGATGATTCTTCTTTTAAATTGCAATTGATCGATTCTATCCAAAGATTGGGTGTTGGTTACCATTTCGAAAAGGAAATCGAAAAATCATTAAGATATATCTATACTACATATTACGATACAAAAGATAATGATGATTTGCATATCATCGCTTTGAGATTCAGATTGATGAGACAACAAGGTTTCCATGTTCCATGTGATGTTTTTAAAAGATTCATTGATGAAGAGGGTAACTTCAAGGAATGGATCAAGGATGATGTTGAAGGTATTTTGTCTTTGTACGAAGCTTCACATTACGGTATGCATGGTGAAGAAATCTTGGATAAGGCATTGGAATTTTGTTCTTCAAGATTGGGTCAGGGTATGGAAGATTCTTTGTCAGTTAGAACTCCAATCTCTAAAACTATCACAAGATTCGGTGCTAAAAAGTTTATTTCTGGTTACCAAGATATCTCACAATTGCATCATCAACCATTGTTGAAGTTCGCAATCTCTGATTTCAATATGTTGCAAAAGGTTCATCAAAGAGAATTGTCACAATTGACAAGATGGTGGAAGGAATTGGATTTCGGTAATAAGTTGCCATTCGCTAGAGATAGATTGGTTGAATGTTACTTCTGGATCGTTGGTGTTTACTTTGAAGAAGGTTACGCTGTTGCAAGAAGATTGTTAACTAAAGTTATATATTTGGCTTCTGTTTTGGATGATATCTATGATGTTTACGGTACATTGGAAGAATTGACTATTTTTACAGCAGTTGTTCAAAGATGGGATATCAACGGTATGGATAAGTTGCCACCATACATGAGAATCTATTACAAGGCTTTGTTGGATGTTTACTTCGAAATGGAATACGAAATGGGTAAAATCGGTAAATCTTACACTGTTGAATACGCAAAGCAAGAAATGAAGAGATTGGCTGAAGTTTACTTCGAAGAAGCAAAGTGGTCTTTTAATAAGTACAAGCCAAGAATGGAAGAATACATGAACGTTGCTTTGTTATCTTCAGGTTACATGATGATGGCAGTTAATGCTTTGGCAGTTATTCCACATCATATCTCTCAAGAAGAATTTCATTGGGTTTTATCTGAACCATCATTGTTAAGAGCTTCATTGACTATCACAAGATTGATGGATGATATCGCTGGTTATGGTTCTGAAGAAAAGTTGTCAGCAGTTCATTACTACATGTCTGAAAACGGTGTTTCAGAAACTGAAGCTTTGGTTGAATTGGGTAAACAAGTTAAAAATGCATGGAAGGATTTGAATAAGGAATTGGTTGAACCAAGAGCTTCTTCAAATCCAATTTTGAGATGTGTTGTTAACTTCACAAGAGTTATTGTTGTTTTGTATGCTGATGGTGACGCATACGGTAATTCTAAAACTAAAACAAAAGAATTGATTAAATCAATTTTAGTTGATCCAATTATTATT")

st.write("##### TIC:")
st.image('image/LT69.png')

st.write("##### Doi: [10.1016/j.ymben.2021.11.005](https://doi.org/10.1016/j.ymben.2021.11.005)")
st.write("##### Cite: Deng, X., Shi, B., Ye, Z., Huang, M., Chen, R., Cai, Y., Kuang, Z., Sun, X., Bian, G., Deng, Z., et al. (2022). Systematic identification of Ocimum sanctum sesquiterpenoid synthases and (?)-eremophilene overproduction in engineered yeast. Metabolic Engineering 69:122-133.")