import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT72")
st.write("##### Former name: Cpu_Copu2")
st.write("##### TPS original information: Cpu_Copu2_尾-Copaene_10min_Standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Coniophora puteana (strain RWD-64-598)_")
st.write("##### UniProt ID or NCBI ID: [XP_007771895.1](https://www.ncbi.nlm.nih.gov/protein/XP_007771895.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT72\nMSTMDPSEFILPDFFATCPFAFGRTNPHADVVIPEAHAWIVKHVPFVDRKRDEFIQDGFQDLMPHCYPWAGKETLRTMCYLNNLLFLVDDLTDDMNSDEARGFGESFIRVLNDPAVHDSSQVMQATREFRSRITGTGVTESRWFGRFLAIFKLYINAVCAEAEDRENKRILDLDTFTVARRENSAVMVFFAITEYALGIDLPDAVYEDPTFLRVYADSADMVILVNDVFSYNREQAKGLDGNNNITVLMQTLDLDLQAAVDHVGEMFSQKMEGCMRGRAMLPSWGVKVDADVERFFDALDQWVVGNLEWSSQSPRYLGPEHEEIMRTRRVVLRKVETEIE*")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT72\nATGTCTACCATGGACCCATCTGAATTTATCTTGCCAGATTTCTTTGCCACTTGTCCTTTTGCTTTCGGTAGAACCAACCCACACGCCGACGTTGTCATTCCAGAAGCCCACGCTTGGATTGTTAAGCACGTTCCATTCGTTGACAGAAAGAGAGATGAATTTATCCAAGATGGTTTCCAAGACTTGATGCCACATTGCTACCCATGGGCTGGTAAGGAAACTCTAAGAACAATGTGTTATTTGAACAATTTGTTGTTTTTGGTCGATGATTTGACTGATGACATGAACTCCGACGAAGCTAGAGGTTTCGGCGAATCTTTCATCAGAGTTTTGAACGACCCAGCTGTTCATGACTCCTCACAAGTTATGCAAGCTACTAGAGAATTTAGATCCAGAATCACCGGTACTGGTGTTACTGAGTCCAGATGGTTCGGTCGTTTCTTGGCTATCTTCAAATTATACATCAACGCTGTCTGTGCTGAAGCTGAAGACAGAGAAAACAAGAGAATTTTGGACTTGGACACCTTCACCGTTGCAAGACGTGAAAACTCTGCCGTCATGGTCTTCTTCGCTATTACTGAATACGCCTTAGGTATTGACCTACCAGACGCTGTTTACGAAGATCCAACTTTCTTGAGAGTCTACGCTGATTCTGCTGACATGGTTATCTTAGTTAACGATGTTTTCTCTTACAACAGAGAACAAGCTAAGGGTTTGGACGGTAATAACAACATTACTGTCTTGATGCAAACTTTGGATTTAGACTTGCAAGCTGCTGTGGACCACGTCGGTGAAATGTTCTCCCAAAAGATGGAAGGTTGTATGAGAGGTAGAGCTATGTTGCCATCCTGGGGTGTCAAGGTCGATGCCGATGTCGAAAGATTCTTCGATGCTTTGGACCAATGGGTTGTCGGTAACTTGGAATGGTCTTCCCAATCTCCAAGATACTTGGGTCCAGAACACGAAGAAATCATGCGTACCAGAAGAGTTGTTTTGCGTAAAGTTGAAACCGAAATTGAATGA")

st.write("##### TIC:")
st.image('image/LT72.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")