import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT74")
st.write("##### Former name: Ool_OMP7")
st.write("##### TPS original information: Ool_OMP7_Protoilludene_9.295min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Omphalotus olearius_")
st.write("##### UniProt ID or NCBI ID: [ (Quin, Michel et al. 2015)](https://doi.org/10.1002/cbic.201500308)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT74\nMPETFYLPDCLANWKWKRALNPNYPEVKAASSEWLRSFKAFPPKAQEAYDRCDFNLLASLAYPLADKDGLRTGCDLMNMFFVFDEYSDVAHESEVQVQADIIMDALRNPHKPRPVGEWVGGEVTRQFWELAIKTASPQSQKRFIETFDTYTKSVVQQAADRTQHYVRTVDEYLEVRRDTIGAKPSFAILELTMDIPDEVIHHPTIERLAILAIDMILLGNDTASYNYEQARGDDNHNMVTIVMHQYKTDIQGALSWIEKYHKELEEEFMQLYNSLPKWGGQIDVDIARYVDGLGNWVRASDQWGFESERYFGTKAPEIQKTRWVTLMPKKRAEGVGPEIVDISEL*")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT74\nATGCCAGAAACTTTTTACTTACCAGACTGTTTGGCTAATTGGAAATGGAAGCGTGCTTTGAACCCAAACTATCCTGAAGTTAAGGCCGCTTCTTCCGAATGGTTGAGATCTTTCAAGGCTTTCCCACCTAAAGCTCAAGAAGCCTACGACAGATGTGATTTCAACTTGTTGGCTTCTCTAGCTTACCCATTGGCTGACAAGGACGGTTTACGTACTGGTTGTGACTTGATGAACATGTTCTTCGTTTTCGACGAATACTCTGATGTCGCTCACGAATCCGAAGTTCAAGTTCAAGCTGATATCATCATGGATGCTTTGAGAAACCCACACAAACCAAGACCAGTTGGTGAATGGGTCGGTGGTGAAGTCACAAGACAATTCTGGGAATTGGCCATCAAGACTGCCTCTCCACAATCTCAAAAGAGATTCATTGAAACCTTTGATACTTACACCAAGTCCGTTGTCCAACAAGCTGCTGACAGAACTCAACACTACGTTAGAACCGTCGATGAATACTTGGAAGTCAGAAGAGACACTATCGGTGCTAAGCCATCTTTTGCTATCTTGGAGTTGACCATGGACATTCCAGATGAAGTCATTCATCATCCAACCATCGAAAGATTGGCAATCTTAGCCATTGACATGATTTTGCTAGGCAACGATACTGCTTCTTACAACTACGAACAAGCCCGTGGTGACGACAACCACAACATGGTTACCATTGTTATGCACCAATACAAGACCGATATTCAAGGTGCCTTGTCGTGGATCGAAAAGTACCACAAGGAATTGGAAGAAGAATTTATGCAATTGTACAATTCCTTGCCAAAGTGGGGTGGTCAAATCGATGTTGACATTGCTAGATATGTCGATGGTTTGGGTAACTGGGTTAGAGCCAGCGACCAATGGGGTTTCGAATCTGAAAGATACTTCGGTACTAAGGCTCCAGAAATTCAAAAGACTAGATGGGTAACTTTGATGCCAAAGAAGAGAGCTGAAGGTGTTGGTCCAGAAATCGTTGACATCTCCGAATTATGA")

st.write("##### TIC:")
st.image('image/LT74.png')

st.write("##### Doi: [10.1002/cbic.201500308](https://doi.org/10.1002/cbic.201500308)")
st.write("##### Cite: Quin, M.B., Michel, S.N., and Schmidt‐Dannert, C. (2015). Moonlighting Metals: Insights into Regulation of Cyclization Pathways in Fungal Δ6‐Protoilludene Sesquiterpene Synthases. ChemBioChem 16:2191-2199.")