import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT75")
st.write("##### Former name: FgJ09920")
st.write("##### TPS original information: FgJ09920_koraiol_12.385min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _F. graminearum J1-012_")
st.write("##### UniProt ID or NCBI ID: [KAF5245951.1](https://www.ncbi.nlm.nih.gov/protein/KAF5245951.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT75\nMVPSIITPPPSCAGGPISPSSICSDHVDIPELADGRWIRLPEALFSSIMAVEPDVNPMYKTSKALSDAWLKDALRMNDKTASIWSRLDIAYMSAICAPNADLETLKLMNDWNGWVFAFDDPFDEGSFANNPIKAAEEVIYTLATLDNIHPVVSPDQNPLRHTLQSCWNRFRQRASPALQYRWKKHLTMYCIGVLQQVGVQNTASRLSVEEYMDMRAGCVGAYPCIGLMEFAEGIDLPQDVMDHPSLEAISRITCDLVTLQNDLCSYRKDLIQGEDSNIMFILRDQGMTDQEAADEIGEMLYDCYRRWHTAMANLPFWGEGVDRDVIKFVNGCRNIALGNLHWSLYTFRYLGDEGPQVKKTRMMRLP*")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT75\nATGGTTCCGAGCATCATTACCCCGCCGCCGAGCTGCGCGGGTGGCCCGATCAGCCCGAGCAGCATTTGCAGCGACCACGTGGATATTCCGGAGCTGGCGGATGGTCGTTGGATTCGTCTGCCGGAGGCGCTGTTCAGCAGCATCATGGCGGTGGAACCGGACGTTAACCCGATGTACAAGACCAGCAAAGCGCTGAGCGACGCGTGGCTGAAGGATGCGCTGCGTATGAACGATAAAACCGCGAGCATCTGGAGCCGTCTGGACATTGCGTATATGAGCGCGATCTGCGCGCCGAACGCGGATCTGGAGACCCTGAAGCTGATGAACGACTGGAACGGTTGGGTTTTCGCGTTTGACGATCCGTTCGACGAAGGCAGCTTTGCGAACAACCCGATTAAAGCGGCGGAGGAAGTGATCTACACCCTGGCGACCCTGGATAACATTCACCCGGTGGTTAGCCCGGACCAGAACCCGCTGCGTCACACCCTGCAAAGCTGCTGGAACCGTTTTCGTCAGCGTGCGAGCCCGGCGCTGCAATACCGTTGGAAGAAACACCTGACCATGTATTGCATCGGTGTTCTGCAGCAAGTGGGCGTTCAGAACACCGCGAGCCGTCTGAGCGTTGAGGAATACATGGATATGCGTGCGGGTTGCGTGGGTGCGTATCCGTGCATTGGTCTGATGGAGTTCGCGGAAGGCATCGACCTGCCGCAAGACGTTATGGATCACCCGAGCCTGGAAGCGATCAGCCGTATTACCTGCGATCTGGTGACGCTGCAGAACGACCTGTGCAGCTATCGTAAGGATCTGATTCAAGGCGAGGACAGCAACATCATGTTTATTCTGCGTGACCAGGGTATGACCGATCAAGAAGCGGCGGACGAGATCGGCGAAATGCTGTACGATTGCTATCGTCGTTGGCACACCGCGATGGCGAACCTGCCGTTCTGGGGCGAGGGCGTGGACCGTGATGTTATTAAATTTGTGAACGGTTGCCGTAACATCGCGCTGGGCAACCTGCACTGGAGCCTGTACACCTTCCGTTATCTGGGTGACGAAGGCCCGCAGGTGAAGAAAACCCGTATGATGCGTCTGCCGTAA")

st.write("##### TIC:")
st.image('image/LT75.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")