import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT76")
st.write("##### Former name: FgJ02895")
st.write("##### TPS original information: FgJ02895_guaia-6,10(14)-diene_10.595min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _F. graminearum J1-012_")
st.write("##### UniProt ID or NCBI ID: No information")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT76\nMVKFDSSSSESEMTTGDEVYIDTKHEVKLKMKNGNGVYNEPKHDQFQGRDEMEVLILPDLFSSLMSVPARENPNYASVKAEADDWISSVIKADADWTNRNKRVDFTYLANIWAPDCSAFALRTSADWNSWAFLFDDQFDEGHLCNDLEGAISEIARTREIMEGTAPRYTADSEHPIRYVFQTLCDRIKQSPEGFFIGKPSSDRFYKRWMWAHELYWQGLVDQVRTNVEGRSYTRRPEEYMAMRRGSLGAYPALVNNEWCYGIDLPEEVADHPSVFEIMVIISDQILLVNDILSYEKDLRLGVDHNMVRLLKAKGHSTQQAINEVGVMINNCYRRYYRALSKLPCFGEEADRALLGFLEVEKNHALGSLLWSYKTGRYFKSKEDGARVRKTRELLIPKSLAAL")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT76\nATGGTTAAATTCGACAGCAGCAGCAGCGAGAGCGAAATGACCACCGGCGACGAGGTGTACATCGATACCAAACACGAAGTTAAGCTGAAAATGAAGAACGGTAACGGCGTTTATAACGAACCGAAGCACGACCAGTTCCAAGGTCGTGATGAGATGGAAGTGCTGATTCTGCCGGACCTGTTTAGCAGCCTGATGAGCGTGCCGGCGCGTGAGAACCCGAACTACGCGAGCGTTAAGGCGGAAGCGGACGATTGGATCAGCAGCGTGATTAAAGCGGACGCGGATTGGACCAACCGTAACAAGCGTGTGGACTTCACCTATCTGGCGAACATCTGGGCGCCGGATTGCAGCGCGTTTGCGCTGCGTACCAGCGCGGACTGGAACAGCTGGGCGTTCCTGTTTGACGATCAGTTTGACGAGGGCCACCTGTGCAACGATCTGGAGGGCGCGATCAGCGAAATTGCGCGTACCCGTGAGATCATGGAAGGTACCGCGCCGCGTTACACCGCGGATAGCGAGCACCCGATTCGTTATGTTTTCCAGACCCTGTGCGACCGTATCAAACAAAGCCCGGAAGGTTTCTTTATTGGCAAACCGAGCAGCGATCGTTTTTACAAGCGTTGGATGTGGGCGCACGAGCTGTATTGGCAGGGCCTGGTGGACCAAGTTCGTACCAACGTGGAAGGTCGTAGCTACACCCGTCGTCCGGAGGAATATATGGCGATGCGTCGTGGTAGCCTGGGTGCGTACCCGGCGCTGGTTAACAACGAGTGGTGCTATGGCATCGACCTGCCGGAGGAAGTGGCGGATCACCCGAGCGTGTTCGAAATTATGGTTATCATTAGCGACCAAATCCTGCTGGTTAACGATATTCTGAGCTACGAGAAAGACCTGCGTCTGGGTGTGGATCACAACATGGTTCGTCTGCTGAAAGCGAAGGGCCACAGCACCCAGCAAGCGATCAACGAAGTGGGTGTTATGATTAACAACTGCTACCGTCGTTACTATCGTGCGCTGAGCAAGCTGCCGTGCTTCGGCGAGGAAGCGGATCGTGCGCTGCTGGGTTTCCTGGAAGTGGAGAAGAACCACGCGCTGGGTAGCCTGCTGTGGAGCTACAAGACCGGCCGTTATTTTAAAAGCAAAGAGGACGGTGCGCGTGTGCGTAAAACCCGTGAACTGCTGATCCCGAAGAGCCTGGCGGCGCTGTAA")

st.write("##### TIC:")
st.image('image/LT76.png')

st.write("##### Doi: [10.1021/jacs.9b12940](https://doi.org/10.1021/jacs.9b12940)")
st.write("##### Cite: Siemon, T., Wang, Z., Bian, G., Seitz, T., Ye, Z., Lu, Y., Cheng, S., Ding, Y., Huang, Y., Deng, Z., et al. (2020). Semisynthesis of Plant-Derived Englerin A Enabled by Microbe Engineering of Guaia-6,10(14)-diene as Building Block. Journal of the American Chemical Society 142:2760-2765. 10.1021/jacs.9b12940.")