import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT77")
st.write("##### Former name: Scl_C15-TPS25")
st.write("##### TPS original information: Scl_C15-TPS25_(-)-未-Cadinene_11.085min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces clavuligerus_")
st.write("##### UniProt ID or NCBI ID: [B5GS26](https://www.uniprot.org/uniprotkb/B5GS26/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT77\nMSTRPVEGSAIWDVLSPHSPHAAAADGKTLVWVEAGELCGHDTAESANLARIRPGLLAAFCHPKATEDDLTLITKWMAWLFLLDDRIDESDLGRDADLLDGHLQDLQGVALGIRTASGPMSRALEEIITQASAGMGDAWQLRFRRNISDYLLACVWQAAHRQAGEFPDPEVFPHWRRAFGAIMPSFDLIERTDGGALPSCVYYSRPYQSLLTAAADLVCWTNDLMTVDKEAAHGDLHNLVLVTEHDRHQDRRTASAAVSAACEQRMRAHTSARRDLTGLTAALGLPDTVRTHADDCAASLLVWVRGHLEWGLETPRYRPGTTGTGTD")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT77\nATGTCTACTAGACCAGTTGAAGGTTCTGCTATTTGGGATGTTTTATCTCCACATTCTCCACATGCTGCTGCTGCTGATGGTAAAACTTTGGTTTGGGTTGAAGCTGGTGAATTATGTGGTCATGATACTGCTGAATCTGCTAATTTGGCTAGAATTAGACCAGGTTTATTAGCTGCTTTTTGTCATCCAAAAGCTACTGAAGATGATTTGACATTGATTACAAAGTGGATGGCTTGGTTGTTTTTGTTGGATGATAGAATTGATGAGTCTGATTTGGGTAGAGATGCTGATTTGTTAGATGGTCATTTGCAAGATTTACAAGGTGTTGCTTTAGGTATTAGAACAGCTTCTGGTCCAATGTCTAGAGCTTTAGAAGAAATTATTACCCAAGCTTCTGCTGGTATGGGTGATGCTTGGCAATTAAGATTTAGAAGAAACATTTCCGACTACTTGTTAGCTTGTGTTTGGCAAGCTGCTCATAGACAAGCTGGTGAATTTCCAGATCCAGAAGTTTTTCCACATTGGAGAAGAGCTTTTGGTGCTATTATGCCATCTTTTGATTTAATTGAGAGGACAGATGGTGGTGCTTTGCCATCTTGTGTTTATTATTCTAGACCATATCAGTCTTTGTTGACTGCTGCTGCTGACTTAGTTTGTTGGACTAATGATTTGATGACAGTTGATAAAGAGGCTGCTCATGGTGATTTGCATAATTTGGTTTTGGTTACTGAACATGATAGACATCAAGATAGAAGAACTGCTTCTGCTGCTGTTTCTGCTGCTTGTGAACAAAGAATGAGAGCTCATACTTCTGCTAGAAGAGATTTGACTGGTTTAACAGCTGCTTTGGGTTTGCCAGATACTGTTAGAACACATGCTGATGATTGTGCTGCTTCTTTATTGGTTTGGGTCAGAGGTCATTTGGAATGGGGTTTGGAAACACCAAGATATAGACCAGGTACTACTGGTACAGGTACAGATTAA")

st.write("##### TIC:")
st.image('image/LT77.png')

st.write("##### Doi: No information")
st.write("##### Cite: No information")