import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT82")
st.write("##### Former name: V5-5")
st.write("##### TPS original information: V5-5_Protoillud-7-ene_8.835min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Dictyostelium discoideum_")
st.write("##### UniProt ID or NCBI ID: [XP_638489.1](https://www.ncbi.nlm.nih.gov/protein/XP_638489.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT82\nMSLSLGDIKFPDNWDLIPNEKNYIDYVYKESIELEVWRPNNKRDLMAHNNVVSLAKYFWPHVDFNRLVMGGELMVWFFSFDDVLDAGIYTDEKQMDLVKRMDNVFINGTVESDATGPEKMALHLRKKCEVMCGKRRKDTFNRFISSCVQWVDSIIPFNKLRSAQGTSPHLELYSYLRKVNIGAYPCVTLTEVMLDHEIEYYIWSDPKWIKMNEDIAIITTLINDLVSYEKEVNDQAGDLNPLYFLQNQKNIPLPDSYKQVVDLIDFWVKDYQTMEQSLLNEMEFKDSKQRSDMEFILEHLRYLASGSKKWSMQTPRYCSPTSPFIEMRTKPSTPVMNSTKKQKIDHVPSQSFISTPIDLNN")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT82\nATGTCCTTGTCCTTGGGCGACATCAAGTTCCCAGACAATTGGGACCTAATCCCAAACGAGAAGAACTACATCGACTACGTCTACAAGGAGTCCATCGAGTTGGAGGTTTGGAGGCCAAACAACAAGAGGGACTTGATGGCCCACAACAACGTCGTTTCCCTAGCCAAGTACTTTTGGCCACACGTTGACTTCAACAGATTGGTGATGGGCGGCGAACTTATGGTTTGGTTCTTCTCCTTCGACGACGTTTTGGACGCCGGTATTTACACAGACGAGAAGCAGATGGACTTGGTCAAGAGAATGGACAACGTCTTCATCAACGGCACCGTTGAATCCGACGCTACAGGTCCAGAAAAGATGGCCCTACACTTGAGAAAGAAGTGCGAAGTCATGTGCGGCAAGAGAAGAAAGGACACCTTCAACAGGTTCATCTCCTCTTGCGTTCAGTGGGTTGACTCCATCATCCCATTCAACAAGTTGAGGTCCGCTCAAGGTACTTCTCCACATTTGGAGTTGTACTCCTACTTGAGGAAGGTCAACATTGGCGCTTACCCTTGCGTTACTTTGACCGAGGTCATGTTGGACCACGAAATCGAGTACTACATCTGGAGCGACCCTAAGTGGATCAAGATGAACGAGGACATCGCCATCATCACCACCTTGATCAACGACTTGGTGTCCTACGAGAAGGAGGTTAACGATCAAGCCGGCGATTTGAACCCATTGTACTTCTTGCAGAACCAGAAGAACATCCCATTGCCAGACTCCTACAAGCAAGTCGTCGACTTGATCGACTTTTGGGTGAAGGACTACCAGACTATGGAACAGTCCTTGTTGAACGAGATGGAGTTCAAGGACAGCAAGCAGAGATCCGACATGGAGTTCATCCTAGAGCACTTGAGGTACTTGGCTTCCGGTTCTAAGAAGTGGTCCATGCAAACCCCAAGGTATTGCTCTCCAACCTCTCCATTCATCGAGATGAGGACCAAGCCATCTACTCCAGTCATGAACTCCACCAAGAAGCAGAAGATCGACCACGTTCCATCCCAATCCTTCATCTCCACCCCAATCGACTTGAACAAC")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")