import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT84")
st.write("##### Former name: V5-17")
st.write("##### TPS original information: V5-17_(Z)-纬-Bisabolene_10.930min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Cryptosporangium arvum_")
st.write("##### UniProt ID or NCBI ID: [WP_035857999.1](https://www.ncbi.nlm.nih.gov/protein/WP_035857999.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT84\nMIDVPVLRVPFPARINPHSTTLGARLRHWLQRSGLATPELNRQFERARFDLLVASLYPAAGAEELRTLAELVAWMFVYDDHFDVHRLGGSPANAARAADQVSAVLAGAPASGPLLTALSDLRRNRLSAVPAPLRQRLLGHLDDYCRSLVRELEFRAANRIPAPGAYFDLRMNTFAWPVLADLAEFADGIVLPAAVRDSPEFAALLSTSGHLMIVIQDLRSLDRELANGESHNVVLSLREERRCSLPEAVELAHRIFVERLGEFLSRRDAVLVAFDRLALDDRARRAAASYVVGLEHLLSGHLAWYARTDRYGRAGALESLGGTDDLIFEGMDR")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT84\nATGATCGACGTCCCAGTTTTGAGGGTTCCATTCCCAGCTAGGATCAACCCACATTCTACCACTTTGGGCGCTAGATTGAGGCATTGGTTGCAAAGATCCGGTTTGGCTACCCCAGAATTGAACAGACAGTTCGAGAGAGCCAGATTCGACTTGTTGGTTGCCTCTTTGTATCCAGCCGCAGGCGCAGAAGAATTGAGAACTTTGGCCGAATTGGTCGCTTGGATGTTCGTCTACGACGATCACTTCGACGTTCATAGATTGGGCGGTTCTCCAGCTAACGCAGCTAGAGCAGCCGATCAAGTTTCAGCAGTTTTGGCAGGTGCTCCAGCTTCAGGTCCATTGTTGACAGCTTTGTCCGACTTGAGGAGAAACAGATTGTCCGCCGTTCCAGCTCCATTGAGACAAAGGTTGTTGGGTCACTTGGACGACTATTGCAGGTCCTTGGTCAGAGAGTTGGAGTTCAGAGCCGCTAACAGAATCCCAGCTCCAGGAGCTTACTTCGATTTGAGAATGAACACCTTCGCTTGGCCAGTTTTGGCAGATTTGGCCGAATTTGCTGACGGTATCGTTTTGCCAGCAGCAGTTAGAGATTCCCCAGAATTTGCCGCTTTGTTGTCTACCTCCGGTCATTTGATGATCGTCATCCAGGACTTGAGGTCCTTGGACAGAGAATTGGCTAACGGCGAATCCCACAACGTTGTCTTGTCCTTGAGGGAGGAAAGGAGGTGTTCTTTGCCAGAAGCCGTTGAATTGGCCCATAGAATCTTCGTCGAGAGGTTGGGCGAATTTTTGTCTAGAAGAGACGCCGTTTTGGTTGCCTTCGATAGATTGGCCTTGGACGATAGAGCTAGAAGAGCCGCAGCTTCTTACGTTGTTGGTTTGGAGCACTTGTTGTCCGGTCATTTGGCTTGGTACGCTAGAACCGACAGATACGGTAGAGCAGGAGCTTTGGAATCCTTGGGCGGTACCGACGATTTGATTTTTGAAGGCATGGATAGG")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")