import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT85")
st.write("##### Former name: V5-12")
st.write("##### TPS original information: V5-12_Bungoene_9.920min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces bungoensis_")
st.write("##### UniProt ID or NCBI ID: [WP_061922997](https://www.ncbi.nlm.nih.gov/protein/WP_061922997)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT85\nMDTFRIPDLCIPVPAALNPELRTATAATDAWLDEFGLVPTEEARRHVQRTRVDRLTAWLCPNASAEAL TLITQWNAWLFQLDDQFDDDPVRGYQPERWREAFGPLFAVFDGTVAAGRLARSLADLWRRTTAVRSSA WQRRFVPHLLWYFDSYRADMIHREEGRVPGLQQYLAHRRASFAFDAVLDLMEIGTGVDLPDRLHANPA FADMREAVIYANACVNDLYSLRKELAHDYAFNAVTVIGHHHRCDLQEAVDRVAAMQAGYVQRILDLEQ VLPERLTRAGLADDVADDALRCVRDFHALTAGNVAWSKETGRYAEIEAQPTYLADLFIP")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT85\nATGGACACCTTCAGAATACCAGACCTTTGCATTCCAGTTCCAGCCGCTTTGAATCCAGAGTTGAGAACAGCTACAGCAGCTACAGACGCTTGGTTAGACGAATTTGGTTTGGTTCCAACCGAGGAAGCTAGAAGACACGTCCAAAGAACCAGGGTTGACAGATTGACCGCTTGGCTTTGTCCAAACGCTTCAGCAGAAGCCTTGACTTTGATCACCCAGTGGAACGCTTGGCTATTCCAGTTGGACGACCAATTCGACGACGATCCAGTTAGAGGTTACCAACCAGAGAGGTGGAGAGAAGCATTTGGTCCATTGTTCGCCGTTTTCGACGGTACAGTTGCAGCAGGTAGATTGGCTAGATCCTTGGCAGACCTTTGGAGAAGAACTACCGCCGTTAGATCCTCAGCTTGGCAAAGAAGATTCGTCCCACACTTGCTTTGGTACTTCGACTCCTACAGAGCCGATATGATCCACAGGGAAGAAGGTAGGGTTCCAGGTTTGCAACAGTACTTGGCCCACAGAAGAGCTTCTTTCGCTTTCGACGCCGTTTTGGACTTGATGGAAATCGGTACAGGCGTTGACTTGCCAGATAGATTGCACGCTAACCCAGCTTTTGCCGATATGAGGGAAGCCGTTATTTACGCTAACGCTTGCGTCAACGACTTGTACAGCTTGAGGAAGGAGTTGGCTCACGATTACGCTTTCAACGCCGTTACCGTTATCGGTCATCACCATAGGTGCGACTTGCAAGAAGCCGTTGACAGAGTTGCAGCTATGCAAGCCGGTTACGTTCAAAGGATCTTGGACTTGGAGCAGGTTTTGCCAGAGAGATTGACCAGAGCAGGTTTAGCAGACGACGTTGCAGACGACGCTTTGAGGTGCGTTAGAGATTTCCACGCATTGACCGCAGGTAACGTTGCTTGGTCTAAGGAAACCGGTAGATACGCCGAAATCGAAGCTCAACCAACCTACTTGGCCGACTTGTTCATCCCA")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")