import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT86")
st.write("##### Former name: V5-18")
st.write("##### TPS original information: V5-18_(+)-尾-himachalene_10.865min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Cryptosporangium arvum_")
st.write("##### UniProt ID or NCBI ID: [WP_035852539.1](https://www.ncbi.nlm.nih.gov/protein/WP_035852539.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT86\nMPRDPVPALYCPLPTRMHPESGPIGRRSVAWLERFGLLDDDRTRERIRATRPAEWACRIAPGGTGAGLQLVSDWTHLGFVIDDTRFDAGPIADRPGRLIPLMMRLMHALDHPEAPADDDPFAAAFRNLSARARAGAPAAVVRRWADGNLEWFFSVACLTAHRVAGTMPTLTEYLNLGPRDRAMRLTGSLIELAEGSVLTDADREEPTVRAVTQAANLLVTIGNDLFSFRKEADDDVLESNIVGVIRHRDGGTAEAALARTVELHDRVMCLYLGLRAQLDEDGSSTVRRHLTRLDHLIRGNLEWSVRVPRYGTGSASPWAETPADGRAAAPHLVPIDWWWDQLRTA")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT86\nATGCCAAGAGATCCAGTTCCAGCCTTGTATTGTCCATTGCCAACCAGAATGCACCCAGAATCAGGTCCAATCGGTAGAAGATCCGTTGCTTGGTTGGAGAGATTCGGATTGTTGGACGACGACAGAACCAGGGAAAGAATCAGAGCTACCAGACCAGCAGAGTGGGCTTGTAGAATTGCACCAGGAGGTACAGGAGCAGGTTTACAATTGGTTTCTGATTGGACCCATTTGGGTTTCGTTATCGACGATACTAGATTCGACGCAGGTCCAATTGCCGATAGACCAGGTAGGTTGATCCCACTAATGATGAGGTTGATGCACGCCTTGGACCATCCAGAAGCTCCAGCAGACGACGATCCATTTGCCGCCGCTTTTAGAAACTTGTCCGCTAGAGCTAGAGCAGGTGCTCCAGCAGCAGTTGTTAGAAGGTGGGCAGACGGTAATTTGGAGTGGTTCTTCTCCGTGGCTTGTTTGACAGCTCACAGAGTTGCAGGTACCATGCCAACTTTGACCGAGTACTTGAACTTGGGCCCAAGAGATAGAGCCATGAGATTGACCGGTAGCTTGATCGAATTGGCCGAAGGTTCAGTCTTGACAGACGCCGATAGAGAAGAACCAACCGTTAGAGCAGTTACTCAAGCCGCTAACTTGTTGGTCACCATCGGAAACGACTTGTTCTCCTTCAGGAAGGAAGCAGACGACGACGTTTTGGAATCCAACATCGTCGGCGTTATCAGACATAGAGACGGTGGTACAGCAGAAGCAGCTTTGGCTAGAACAGTGGAATTGCACGACAGAGTCATGTGCTTGTACTTGGGCTTGAGGGCACAATTGGACGAAGACGGTTCTTCCACCGTTAGAAGACACTTGACCAGGTTGGACCACTTGATCAGAGGTAACTTGGAGTGGTCCGTCAGAGTTCCAAGATACGGTACAGGTTCAGCTTCTCCTTGGGCAGAAACTCCAGCAGACGGTAGAGCAGCAGCTCCACATTTGGTCCCAATAGATTGGTGGTGGGACCAACTAAGAACCGCT")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")