import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT87")
st.write("##### Former name: V5-19")
st.write("##### TPS original information: V5-19_(4S,5S,7S)-discoidol_12.715min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Dictyostelium discoideum_")
st.write("##### UniProt ID or NCBI ID: [Q54BE5](https://www.uniprot.org/uniprotkb/Q54BE5/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT87\nMDYDIKFTWDKNQFLDQEIRIPKYTLPWDFKSSPFDKDFENQEMEYVKQFFQNYENAVNYVKKNEIGKIAALNFPLGEKDEYMVNSKLLDFLFILDDYIYESRNYEEDYVDNLMDRSSKSHDPFGREIWRLFDEYYRVGVKESVDLLIRDFEYWSRSAIKTNKYKSLNSSLSIEDYFNSRHGDFGMTITASSCTSTLYVENEIRESKNFKKFFKYFELCNLMINDCGSFKMEINEILLTNFVKVRAIQLGSIDLALKYCVGLLNKYIIKVDKYSTKLEQQYPNHSHLKKYIYTLKTFTAGHNKGYGHANRYN")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT87\nATGGACTACGACATCAAGTTCACTTGGGACAAGAACCAGTTCTTGGACCAGGAGATCAGAATACCAAAGTACACCTTGCCTTGGGACTTCAAGTCCTCTCCATTCGACAAGGACTTCGAGAACCAGGAGATGGAGTACGTCAAGCAGTTCTTCCAGAACTACGAGAACGCCGTCAACTACGTCAAGAAGAACGAGATCGGCAAGATCGCAGCTTTGAACTTCCCATTGGGCGAAAAGGACGAGTACATGGTCAACTCCAAGTTGTTGGACTTCTTGTTCATCTTGGACGACTACATCTACGAGTCCAGGAACTACGAGGAAGACTACGTTGACAACTTGATGGACAGGTCCTCCAAGTCTCACGATCCATTTGGTAGGGAGATTTGGAGGTTGTTCGACGAGTACTACAGGGTTGGCGTTAAGGAATCCGTGGACTTGTTGATCAGGGACTTCGAGTATTGGTCCAGATCCGCCATCAAGACCAACAAGTACAAGTCCTTGAACTCCTCCTTGTCCATCGAGGACTACTTCAACTCCAGGCACGGTGATTTCGGTATGACCATTACCGCTTCCTCTTGTACCTCCACCTTGTACGTCGAAAACGAGATCAGGGAGTCCAAGAACTTCAAGAAGTTCTTCAAGTACTTCGAGCTTTGCAACTTGATGATCAACGATTGCGGCTCCTTCAAGATGGAGATCAACGAGATCCTATTGACCAACTTCGTCAAGGTCAGGGCTATCCAATTGGGTTCCATCGACCTTGCCTTGAAGTATTGCGTCGGCTTGTTGAACAAGTACATCATCAAGGTCGACAAGTACTCCACCAAGTTGGAGCAACAGTACCCAAACCACTCCCACTTGAAGAAGTACATCTACACCTTGAAGACCTTCACCGCAGGTCATAACAAGGGTTACGGTCACGCTAACAGGTACAAC")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")