import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT88")
st.write("##### Former name: V5-20")
st.write("##### TPS original information: V5-20_7-epi-伪-eudesmol_12.815min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Streptomyces viridochromogenes DSM 40736_")
st.write("##### UniProt ID or NCBI ID: [ZP_07308339.1](https://www.ncbi.nlm.nih.gov/protein/ZP_07308339.1?report=genpept)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT88\nMPQDVRFDLPFETPVSKHLESARARHLRWVWEMRLVHSREGFEEYRSWDLPQAAARTYPHASADDMVVLMNWFSLAFLFDDQFDASRPDRADRIAEVARELIVTPLRPAGTPPRVACPITLAWTEVWKHLSHGMSLTWQSRFAASWGRFLEAHCEEVDLAARGLEGTLGLVEFTEFRRRTVGIHHSIDAGERSRGFEVPAQAMAHPVMERMRDLAADTIGFMNDIHSFEREKRRGDGHNLIAVLRRERGCSWQEATDEAYRMTIARLDEYLELQERVPQMCDELRLDEAQRDGVRLGVEAIQHWINGNYEWALTSGRYAAAKEGAVATAELAGRGSVDDLLTV")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT88\nATGCCACAAGACGTTAGGTTCGACTTGCCATTCGAGACTCCAGTTTCCAAGCACTTGGAGTCAGCTAGAGCTAGACACCTTAGGTGGGTTTGGGAAATGAGGTTGGTCCATTCCAGGGAAGGTTTCGAGGAGTACAGAAGTTGGGACTTGCCACAAGCAGCAGCTAGAACTTATCCACACGCTTCAGCCGACGATATGGTTGTCTTGATGAATTGGTTCTCCTTGGCCTTCTTGTTCGACGACCAATTCGACGCTTCTAGACCAGATAGGGCCGATAGAATTGCCGAAGTTGCTAGAGAGTTGATCGTCACTCCATTAAGACCAGCAGGTACTCCACCAAGAGTTGCTTGTCCAATCACCTTGGCTTGGACCGAAGTTTGGAAGCACTTGTCTCACGGTATGTCCTTGACTTGGCAGTCTAGATTCGCAGCTTCTTGGGGTAGGTTCTTGGAAGCTCATTGCGAAGAAGTGGATTTGGCCGCTAGAGGATTGGAAGGTACTTTGGGCTTGGTCGAATTTACTGAATTTAGAAGAAGGACCGTTGGTATTCATCATTCCATTGACGCCGGCGAAAGGTCTAGAGGTTTCGAAGTTCCAGCCCAAGCAATGGCTCATCCAGTTATGGAGAGGATGAGAGATTTGGCCGCAGATACCATCGGTTTCATGAACGACATCCACTCCTTCGAGAGAGAGAAGAGAAGAGGAGACGGTCACAACTTGATTGCCGTCTTGAGAAGGGAAAGAGGTTGCTCTTGGCAAGAAGCTACCGACGAAGCATATAGAATGACCATCGCTAGGTTGGACGAGTACTTGGAGTTGCAGGAAAGAGTCCCACAGATGTGCGACGAATTGAGATTGGACGAGGCTCAAAGAGACGGAGTTAGATTGGGCGTTGAAGCTATCCAGCATTGGATCAACGGCAACTACGAGTGGGCTTTGACTTCAGGTAGATACGCAGCAGCTAAGGAAGGAGCAGTTGCTACAGCAGAATTGGCAGGTAGAGGTTCCGTTGACGATTTGTTGACCGTT")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")