import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT91")
st.write("##### Former name: V5-15")
st.write("##### TPS original information: V5-15_(+)-Intermedeol_12.905min_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Termitomyces_")
st.write("##### UniProt ID or NCBI ID: [(Burkhardt, Kreuzenbeck et al. 2019)](https://doi.org/10.1039/c8ob02744g)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT91\nMVQFRIPDLLSCLPACIKATNADNDILQAGLVEVIDQCHLTDHYKKDLKRARIPHLAIRAFPNSDLKYLRICVEYLIAAFLLDRLTDKPATAAQAQEWADIYKQEFRKTLQGTKGPARINQYLTKKCDIYPQAFSKTFEKTKGPAEIIKYLTSHMSNTIKDPYWSCLVENNILLADGMAKEAVDRENPGTEMDLETYIKVRRDTIGARQLFDLGRWIHELNITPETLTHPDIVRMEEQFIDLISLANDLYSYKKEYLAKDAKHNYLTIALRDPTVDLHENDLQGAINYTYDKFCRVLADLEHQKKVLPRFRKSEEAKVDKYFWLMMNVVIGTIQWSLECERYGHFVDADGPNQGDVVFNL*")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT91\nATGGTCCAGTTCAGAATACCAGACTTGTTGTCTTGCTTGCCAGCTTGTATCAAGGCTACCAACGCCGATAACGACATCTTGCAAGCAGGTTTGGTGGAGGTCATCGATCAGTGTCACTTGACCGACCACTACAAGAAGGACTTGAAGAGGGCCGAAATTCCACACTTGGCCATTAGAGCTTTCCCAGAGTCCGACTTGAAGTACTTGAGGATTTGCGTGGAGTACTTGATCGCCGCTTTCCTATTGGACAGATTGACCGACAAGCCAGCTACAGCAGCTCAAGCTCAAGAGTGGGCAGATATCTACAAGCAGGAGTTCAGGAAGACCTTGCAAGGTACTAAGGGTCCAGCTAGGATCAACCAGTACTTGACCAAGAAGTGCGACATCTACCCACAAGCCTTCTCCAAGACCTTCGAAAAGACCAAGGGTCCAGCCGAAATCATCAAGTACTTGACCTCCCACATGTCCAACACCATCAAGGACCCATATTGGTCTTGCTTGGTCGAGAACAACATCTTGTTGGCCGACGGTATGGCAAAGGAAGCCGTTGACAGAGAAAACCCAGGTACAGAGATGGACTTGGAAACTTATATCAAGGTCAGGAGAGATACCATCGGCGCTAGACAATTGTTCGACCTAGGTAGGTGGATTCATGAATTGAACATCACCCCAGAAACTTTGACTCATCCAGACATCGTTAGGATGGAGGAGCAGTTCATCGACTTGATCTCCTTGGCCAACGACTTGTACAGCTACAAGAAGGAGTACTTGGCCAAGGACGCTAAGCACAACTACTTGACCATCGCCTTGAGAGATCCAACCGTTGATTTGCACGAGAACGACTTGCAAGGCGCTATCAACTACACCTACGACAAGTTTTGCAGGGTCTTGGCAGACTTGGAGCATCAGAAGAAGGTCTTGCCAAGGTTCAGGAAGTCCGAAGAAGCTAAGGTCGACAAGTACTTTTGGTTGATGATGAACGTCGTGATCGGTACCATTCAGTGGTCTTTGGAGTGCGAAAGGTACGGTCATTTTGTTGACGCAGACGGTCCAAACCAAGGCGACGTTGTCTTCAACTTG")

st.write("##### TIC: No information")
st.write("##### Doi: [10.1039/c8ob02744g](https://doi.org/10.1039/c8ob02744g)")
st.write("##### Cite: Burkhardt, I., Kreuzenbeck, N.B., Beemelmanns, C., and Dickschat, J.S. (2019). Mechanistic characterization of three sesquiterpene synthases from the termite-associated fungus Termitomyces. Organic & Biomolecular Chemistry 17:3348-3355. 10.1039/C8OB02744G.")