import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT93")
st.write("##### Former name: v5-24")
st.write("##### TPS original information: v5-24_10.930min_伪-Cuprenene_Standard")
st.write("##### TPS type: No information")

st.write("##### Species: _Coprinopsis cinerea okayama7_")
st.write("##### UniProt ID or NCBI ID: [XP_001832549.1](https://www.ncbi.nlm.nih.gov/protein/XP_001832549.1)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT93\nMPAALPYNVSRDNKWDIKKIIQDFFKRCDVPYQVIPYDTELWNACLKRAKEKGYPVEPDSPMSLYRSFKVGVVITRTSYGHIQDYEILIWVATFTAFVTYADDAFQEDIQHLHSFARTFLQNEKHEHPVLEAFAQFLRESSIRFSHFVANTVVSSALRFMMSIALEFEGQNVSVSTEAREYPGYIRILSGLSDIYALFAFPMDLPRSTYIQAFPEQIDYINGTNDLLSFYKEELDCETVNFISAAATSQQVSKLEVLRNAAEKAAYSYDVVVNVLKPYPEALAAWKSFARGFCYFHTSSPRYRLGEMFHDFEHDLVCKCASCTEI")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT93\nATGCCAGCAGCTTTGCCATACAACGTTTCCAGGGACAACAAGTGGGACATCAAGAAGATCATCCAGGACTTCTTCAAGAGGTGCGACGTTCCATACCAAGTCATCCCATACGACACCGAACTTTGGAACGCTTGCTTGAAGAGGGCTAAGGAGAAGGGTTACCCAGTTGAACCAGATTCCCCAATGTCCTTGTACAGGTCCTTCAAGGTGGGTGTTGTCATCACCAGAACCTCTTACGGTCACATCCAGGACTACGAGATCTTGATTTGGGTCGCTACCTTCACCGCTTTCGTTACTTACGCCGACGACGCTTTCCAAGAAGATATCCAACACTTGCACTCCTTCGCCAGAACATTCTTGCAGAACGAGAAGCACGAGCATCCAGTTTTGGAAGCCTTCGCCCAATTCTTGAGAGAAAGCTCCATCAGGTTCTCCCACTTCGTTGCTAACACCGTTGTTTCCTCCGCTTTGAGGTTCATGATGTCCATCGCTTTGGAGTTCGAGGGTCAAAACGTCTCCGTTTCTACCGAAGCCAGAGAATACCCAGGTTACATCAGGATCTTGTCCGGTTTGTCCGACATCTACGCTTTGTTCGCCTTCCCAATGGACTTGCCAAGATCCACCTACATCCAAGCCTTCCCAGAACAGATCGACTACATCAACGGCACCAACGACTTGTTGTCCTTCTACAAGGAGGAGTTGGATTGCGAAACTGTTAACTTCATTTCCGCCGCAGCTACTTCCCAACAAGTGTCCAAGTTGGAGGTTTTGAGAAACGCCGCCGAAAAAGCAGCTTACTCCTACGACGTTGTCGTGAACGTCTTGAAGCCATACCCAGAAGCATTGGCAGCTTGGAAATCCTTCGCTAGAGGTTTTTGCTACTTCCACACCTCCTCTCCAAGATACAGGTTGGGAGAGATGTTCCACGACTTCGAACACGACTTGGTTTGCAAGTGCGCATCTTGTACCGAGATC")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")