import streamlit as st
# st.set_page_config(layout="wide")
st.title("LT95")
st.write("##### Former name: v5-30")
st.write("##### TPS original information: v5-30_12.980min_(1S,6S,7R)-sesquipiperitol_NMR")
st.write("##### TPS type: No information")

st.write("##### Species: _Hemiptera: pentatomidae_")
st.write("##### UniProt ID or NCBI ID: [A0A343W969](https://www.uniprot.org/uniprotkb/A0A343W969/entry)")
st.write("##### Amino acid sequence:")
st.write("``` \n>LT95\nMVSIAAKSLPKLSGAVFGQFSRRKQLIQRHWLDTRTDQYYDVLRRIVVPECKNIASDVPEYPERIEKLLYYTNPAFSDAWNFTTELIYRTVADESHQTEENITKMYLIRATMDLLFTMSAVLDDISDRSEFRKGKKGWHMICQGGESTALYDGTQMGLFPLYLLKQYFKNDPGYSRLLETVVMTYIKLTIGQTIDVLGQFKKSPSMAEYKRINYYKAGQFVAAGSELAVIHAGITSQDLIDKTVEIFTIAGQIIQTWDDFNDYYSSSEQNGKLSCDFMNAGTTWVSAKAMEVFTPSQAVKFMECYGSDDQSKMKTVQELYDEIDMPKLYTEYVLENYNRCETLIKELPHDRLREACSSYMEWLVVRETPDEDSEHKVALCLNISG")
st.write("##### Nucleic acid sequence (Codon optimization):")
st.write("``` \n>LT95\nATGGTTTCCATCGCCGCTAAGTCTTTGCCAAAGTTGTCCGGAGCCGTTTTCGGTCAATTCTCCAGGAGGAAGCAGTTGATCCAGAGACATTGGCTAGACACCAGAACCGATCAGTACTACGACGTCTTGAGGAGAATCGTCGTTCCAGAATGCAAGAACATCGCCTCAGACGTTCCAGAATACCCAGAGAGGATCGAGAAGTTGTTGTACTACACCAACCCAGCTTTTTCAGACGCTTGGAACTTCACCACCGAGTTGATCTACAGGACCGTTGCCGACGAATCTCATCAAACCGAAGAGAACATCACCAAGATGTACTTGATCAGGGCCACTATGGATTTGTTGTTCACCATGTCCGCAGTCTTGGACGATATCTCCGACAGATCCGAATTTAGAAAGGGCAAGAAGGGTTGGCACATGATTTGCCAAGGCGGAGAATCCACAGCTTTGTACGACGGTACTCAGATGGGTTTGTTCCCATTGTACTTGTTGAAGCAGTACTTCAAGAACGACCCAGGTTACTCTAGATTGTTGGAAACTGTTGTCATGACCTACATCAAGTTGACCATCGGCCAAACCATTGACGTGTTGGGTCAATTCAAGAAGTCCCCATCTATGGCCGAGTACAAGAGGATCAACTACTACAAGGCCGGCCAATTCGTTGCAGCAGGTTCCGAATTGGCCGTTATTCACGCCGGTATTACCTCTCAAGACTTGATCGACAAGACCGTCGAAATCTTCACCATTGCCGGTCAAATCATCCAGACTTGGGACGACTTCAACGACTACTACTCCTCTTCCGAGCAGAACGGTAAGTTGTCTTGCGACTTCATGAACGCCGGTACTACTTGGGTTAGCGCTAAGGCTATGGAAGTCTTCACCCCATCTCAAGCCGTTAAGTTCATGGAGTGCTACGGTTCCGACGATCAATCCAAGATGAAGACCGTCCAGGAGTTGTACGACGAGATCGACATGCCAAAGTTGTACACCGAGTACGTCTTGGAGAACTACAACAGGTGCGAAACTTTGATCAAGGAGTTGCCACACGATAGGTTGAGAGAAGCATGTAGCTCCTACATGGAGTGGTTGGTTGTTAGAGAAACCCCAGACGAAGACTCCGAACATAAGGTTGCCCTTTGCTTGAACATCTCCGGT")

st.write("##### TIC: No information")
st.write("##### Doi: No information")
st.write("##### Cite: No information")